# Introduction

UCI has a complex google doc they've been using to track their samples so far.

https://docs.google.com/spreadsheets/d/13M6-Ry6oXgkx94BHZOGioYPI6F_hWDqjGgcaNu2JNYs/edit#gid=1838362486

Also there's a metadata spreadsheet for IGVF at
https://docs.google.com/spreadsheets/d/1BLMledzmqOqXnJHzpijgw91IOs-9tSlVeZDG_MtXddk/edit#gid=1284120531

In [1]:
import bz2
from collections import Counter, namedtuple
import datetime
from io import StringIO
import numpy
import os
import pandas
from pathlib import Path
import re
from subprocess import run, PIPE
import sys
import zoneinfo

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mousedemo.settings')
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

import django
from django.contrib.auth import get_user_model
from django.db import DEFAULT_DB_ALIAS

MOUSEDEMO = str(Path("mousedemo").absolute())
if MOUSEDEMO not in sys.path:
    sys.path.append(MOUSEDEMO)

# Pre-initialization setup

Backup the old ones and make a new database file before we initialize the database.

In [2]:
# Create a new database
result = run(["python3", "manage.py", "check"], capture_output=True)

if len(result.stderr) > 0:
    print(result.stderr.decode("utf-8"))
    
result.check_returncode()

In [3]:
initial = Path("igvf_mice/migrations/0001_initial.py")
if initial.exists():
    initial.unlink()
    
result = run(["python3", "manage.py", "makemigrations", "igvf_mice"], capture_output=True)

if len(result.stderr) > 0:
    print(result.stderr.decode("utf-8"))
    
result.check_returncode()

In [4]:
# Backup several old sqlite database files

db_name = Path("db.sqlite3")

backup_names = []
for i in range(0, 4):
    backup_names.append(Path("db{}.sqlite3".format(i+1)))

if backup_names[-1].exists():
    backup_names[-1].unlink()

if db_name.exists():    
    for i in reversed(range(0, 3)):
        if backup_names[i].exists():
            print("renaming {} to {}".format(backup_names[i], backup_names[i+1]))
            backup_names[i].rename(backup_names[i+1])

    db_name.rename(backup_names[0])
    print("renaming {} to {}".format(db_name, backup_names[0]))

renaming db3.sqlite3 to db4.sqlite3
renaming db2.sqlite3 to db3.sqlite3
renaming db1.sqlite3 to db2.sqlite3
renaming db.sqlite3 to db1.sqlite3

In [5]:
# Create a new database
result = run(["python3", "manage.py", "migrate"], capture_output=True)

if len(result.stderr) > 0:
    print(result.stderr.decode("utf-8"))
    
result.check_returncode()
    
assert Path("db.sqlite3").exists()

# Import django application code

We have to wait until the initial checks complete before we can start importing our application otherwise django has problems.

In [6]:
django.setup()

from django.contrib.auth.models import ContentType
from mousedemo import settings
from igvf_mice import models

from igvf_mice.io.validators import (
    validate_alias,
)
from igvf_mice.io.converters import (
    date_or_none,
    datetime_or_none,
    float_or_none,
    int_or_none,
    int_or_0,
    str_or_empty,
    str_or_none,
    normalize_plate_name,
    normalize_strain,
    normalize_subpool_submission_status,
    parse_mouse_name,
    parse_mouse_tissue,    
)

# Setup users

Now that we have a fresh clean database, lets create user accounts

In [7]:
# Create accounts.
with open("pw", "rt") as instream:
    pw = instream.read().strip()

user_model = get_user_model()
user_model._default_manager.db_manager(DEFAULT_DB_ALIAS).create_superuser(
    username="diane",
    password=pw,   
)

# load igvf_mice permissions    
permissions = set()
for ct in ContentType.objects.filter(app_label="igvf_mice"):
    permissions.update(ct.permission_set.all())

with open("guest.pw", "rt") as instream:
    pw = instream.read().strip()

user_model = get_user_model()
guest = user_model._default_manager.db_manager(DEFAULT_DB_ALIAS).create_user(
    username="guest",
    password=pw,
    is_staff=True,
)
guest.user_permissions.set(permissions)
print(guest)

guest

In [8]:
guest = user_model._default_manager.db_manager(DEFAULT_DB_ALIAS).get(username="guest")
diane = guest = user_model._default_manager.db_manager(DEFAULT_DB_ALIAS).get(username="diane")

In [9]:
assert guest.is_staff

In [10]:
guest.user_permissions.all()

# Load data

In [11]:
#spreadsheet_name = "IGVF_Split-seq_20230118.xlsx"
# Sorce document https://docs.google.com/spreadsheets/d/13M6-Ry6oXgkx94BHZOGioYPI6F_hWDqjGgcaNu2JNYs/edit#gid=2088730991
lizs_sheet_name = "https://woldlab.caltech.edu/nextcloud/index.php/s/eEtjBfDqQFnLpSS/download"
# Source document https://docs.google.com/spreadsheets/d/1OJ8HETiLXF26ztb2CHPYIsBCO5A049ZV5OrXywOPsdI/edit#gid=1997889547
founder_sheet_name = "https://woldlab.caltech.edu/nextcloud/index.php/s/G7Ri92rDAi6oo68/download"

book = pandas.ExcelFile(lizs_sheet_name)
for name in book.sheet_names:
    print(name)

schedule - all
Line information
mice
Dissection Notes
Samples - F1s
F1 Samples into experiment
Samples - F1s_6mo
Samples - CClines
Samples - Bridge
Bridge samples into experiment
PBMCs - F1
PBMCs - F1s_6mo
PBMCs - CClines
Plate setups
Experiment
Protocols_description
ONT Sequencing
DCC
Planning
tracking labels

# Sample sheet locations

In [12]:
sample_sheets = [
    (founder_sheet_name, "Samples - 8 founders"),
    (lizs_sheet_name, "Samples - Bridge"),
    (lizs_sheet_name, "Samples - F1s"),
    (lizs_sheet_name, "Samples - CClines"),
    (lizs_sheet_name, "Samples - F1s_6mo"),
]

# Load all submitted accession ids

In [13]:
def load_submitted_sheets():
    submitted_book_names = {
        # Sheets on sandbox
        "igvftst": {
            "IGVF_003": "https://woldlab.caltech.edu/nextcloud/index.php/s/nBnE6j2RBMkpM9i/download",
            "IGVF_b01": "https://woldlab.caltech.edu/nextcloud/index.php/s/5cJteSWgitN5BDM/download",
        },
        # Sheets on data. (production)
        "igvf": {
            "IGVF_b01": "https://woldlab.caltech.edu/nextcloud/index.php/s/HTbfN6btm3kqJXb/download",
            "IGVF_003": "https://woldlab.caltech.edu/nextcloud/index.php/s/wRFxdcknisFfM2t/download",
            "IGVF_004": "https://woldlab.caltech.edu/nextcloud/index.php/s/8ygLzeyjAQ9CxXn/download",
            "IGVF_005": "https://woldlab.caltech.edu/nextcloud/index.php/s/2Pba74eLFwmFfgS/download",
            # IGVF_006 failed.
            "IGVF_007": "https://woldlab.caltech.edu/nextcloud/index.php/s/7rQKGSTS7937kTW/download",
            "IGVF_008": "https://woldlab.caltech.edu/nextcloud/index.php/s/iECMTJF2iPMy3kT/download",
            "IGVF_008B": "https://woldlab.caltech.edu/nextcloud/index.php/s/YF46eNqSASJC8fr/download",
            "IGVF_009": "https://woldlab.caltech.edu/nextcloud/index.php/s/PtNn96zR9XbybFZ/download",
            "IGVF_010": "https://woldlab.caltech.edu/nextcloud/index.php/s/CocTP9pePJobyPs/download",
            "IGVF_011": "https://woldlab.caltech.edu/nextcloud/index.php/s/Sm72GtmdN4QsXJr/download",
            "IGVF_012": "https://woldlab.caltech.edu/nextcloud/index.php/s/MmatjmzQgofeM2Y/download",
            "IGVF_013": "https://woldlab.caltech.edu/nextcloud/index.php/s/EHret5a6Sjiro4q/download",
            "IGVF_014": "https://woldlab.caltech.edu/nextcloud/index.php/s/GRQCaSZ3WgeonzK/download",
        }
    }
    submitted_sheets = {}
    for accession_prefix in submitted_book_names:
        for book_name in submitted_book_names[accession_prefix]:
            print("reading {} {} {}".format(accession_prefix, book_name, submitted_book_names[accession_prefix][book_name]))
            book = pandas.ExcelFile(submitted_book_names[accession_prefix][book_name])

            for sheet_name in book.sheet_names:
                if sheet_name not in submitted_sheets.get(accession_prefix, {}):
                    submitted_sheets.setdefault(accession_prefix, {})[sheet_name] = book.parse(sheet_name)
                else:
                    previous_sheet = submitted_sheets[accession_prefix][sheet_name]
                    next_sheet = book.parse(sheet_name)
                    print("next_sheet {} {}".format(sheet_name, next_sheet.shape))
                    
                    already_seen = set(previous_sheet["accession"])
                    need_to_add = set(next_sheet["accession"]).difference(already_seen)
                    next_sheet = next_sheet[next_sheet["accession"].isin(need_to_add)]
                    print("next_sheet after duplicate filter {}".format(next_sheet.shape))
                    
                    submitted_sheets.setdefault(accession_prefix, {})[sheet_name] = pandas.concat([previous_sheet, next_sheet])
                print(accession_prefix, sheet_name, submitted_sheets[accession_prefix][sheet_name].shape)

    return submitted_sheets

submitted_sheets = load_submitted_sheets()

reading igvftst IGVF_003 https://woldlab.caltech.edu/nextcloud/index.php/s/nBnE6j2RBMkpM9i/download
igvftst rodent_donor (64, 25)
igvftst tissue (192, 9)
igvftst measurement_set (17, 12)
igvftst sequence_file (246, 14)
reading igvftst IGVF_b01 https://woldlab.caltech.edu/nextcloud/index.php/s/5cJteSWgitN5BDM/download
next_sheet rodent_donor (8, 25)
next_sheet after duplicate filter (8, 25)
igvftst rodent_donor (72, 25)
next_sheet tissue (8, 9)
next_sheet after duplicate filter (8, 9)
igvftst tissue (200, 9)
igvftst multiplexed_sample (8, 8)
next_sheet measurement_set (8, 13)
next_sheet after duplicate filter (8, 13)
igvftst measurement_set (25, 13)
next_sheet sequence_file (32, 14)
next_sheet after duplicate filter (32, 14)
igvftst sequence_file (278, 14)
igvftst configuration_file (16, 8)
reading igvf IGVF_b01 https://woldlab.caltech.edu/nextcloud/index.php/s/HTbfN6btm3kqJXb/download
igvf rodent_donor (8, 25)
igvf tissue (8, 9)
igvf multiplexed_sample (8, 7)
igvf measurement_set (8, 12)
igvf sequence_file (32, 20)
reading igvf IGVF_003 https://woldlab.caltech.edu/nextcloud/index.php/s/wRFxdcknisFfM2t/download
next_sheet rodent_donor (65, 25)
next_sheet after duplicate filter (65, 25)
igvf rodent_donor (73, 25)
next_sheet tissue (192, 9)
next_sheet after duplicate filter (192, 9)
igvf tissue (200, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (24, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (24, 13)
next_sheet sequence_file (246, 20)
next_sheet after duplicate filter (246, 20)
igvf sequence_file (278, 20)
reading igvf IGVF_004 https://woldlab.caltech.edu/nextcloud/index.php/s/8ygLzeyjAQ9CxXn/download
next_sheet rodent_donor (64, 25)
next_sheet after duplicate filter (0, 25)
igvf rodent_donor (73, 25)
next_sheet tissue (128, 9)
next_sheet after duplicate filter (64, 9)
igvf tissue (264, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (40, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (40, 13)
next_sheet sequence_file (246, 20)
next_sheet after duplicate filter (246, 20)
igvf sequence_file (524, 20)
reading igvf IGVF_005 https://woldlab.caltech.edu/nextcloud/index.php/s/2Pba74eLFwmFfgS/download
next_sheet rodent_donor (65, 25)
next_sheet after duplicate filter (0, 25)
igvf rodent_donor (73, 25)
next_sheet tissue (192, 9)
next_sheet after duplicate filter (128, 9)
igvf tissue (392, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (56, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (56, 13)
next_sheet sequence_file (242, 20)
next_sheet after duplicate filter (242, 20)
igvf sequence_file (766, 20)
reading igvf IGVF_007 https://woldlab.caltech.edu/nextcloud/index.php/s/7rQKGSTS7937kTW/download
next_sheet rodent_donor (65, 25)
next_sheet after duplicate filter (0, 25)
igvf rodent_donor (73, 25)
next_sheet tissue (256, 9)
next_sheet after duplicate filter (128, 9)
igvf tissue (520, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (72, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (72, 13)
next_sheet sequence_file (242, 20)
next_sheet after duplicate filter (242, 20)
igvf sequence_file (1008, 20)
reading igvf IGVF_008 https://woldlab.caltech.edu/nextcloud/index.php/s/iECMTJF2iPMy3kT/download
next_sheet rodent_donor (65, 25)
next_sheet after duplicate filter (1, 25)
igvf rodent_donor (74, 25)
next_sheet tissue (192, 9)
next_sheet after duplicate filter (64, 9)
igvf tissue (584, 9)
next_sheet multiplexed_sample (9, 7)
next_sheet after duplicate filter (9, 7)
igvf multiplexed_sample (81, 7)
next_sheet measurement_set (9, 13)
next_sheet after duplicate filter (9, 13)
igvf measurement_set (81, 13)
next_sheet sequence_file (76, 20)
next_sheet after duplicate filter (76, 20)
igvf sequence_file (1084, 20)
reading igvf IGVF_008B https://woldlab.caltech.edu/nextcloud/index.php/s/YF46eNqSASJC8fr/download
next_sheet rodent_donor (65, 25)
next_sheet after duplicate filter (0, 25)
igvf rodent_donor (74, 25)
next_sheet tissue (192, 9)
next_sheet after duplicate filter (0, 9)
igvf tissue (584, 9)
next_sheet multiplexed_sample (11, 7)
next_sheet after duplicate filter (11, 7)
igvf multiplexed_sample (92, 7)
next_sheet measurement_set (11, 13)
next_sheet after duplicate filter (11, 13)
igvf measurement_set (92, 13)
next_sheet sequence_file (86, 20)
next_sheet after duplicate filter (86, 20)
igvf sequence_file (1170, 20)
reading igvf IGVF_009 https://woldlab.caltech.edu/nextcloud/index.php/s/PtNn96zR9XbybFZ/download
next_sheet rodent_donor (65, 25)
next_sheet after duplicate filter (0, 25)
igvf rodent_donor (74, 25)
next_sheet tissue (128, 9)
next_sheet after duplicate filter (64, 9)
igvf tissue (648, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (108, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (108, 13)
next_sheet sequence_file (246, 20)
next_sheet after duplicate filter (246, 20)
igvf sequence_file (1416, 20)
reading igvf IGVF_010 https://woldlab.caltech.edu/nextcloud/index.php/s/CocTP9pePJobyPs/download
next_sheet rodent_donor (70, 25)
next_sheet after duplicate filter (5, 25)
igvf rodent_donor (79, 25)
next_sheet tissue (128, 9)
next_sheet after duplicate filter (64, 9)
igvf tissue (712, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (124, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (124, 13)
next_sheet sequence_file (246, 20)
next_sheet after duplicate filter (246, 20)
igvf sequence_file (1662, 20)
reading igvf IGVF_011 https://woldlab.caltech.edu/nextcloud/index.php/s/Sm72GtmdN4QsXJr/download
next_sheet rodent_donor (70, 25)
next_sheet after duplicate filter (0, 25)
igvf rodent_donor (79, 25)
next_sheet tissue (192, 9)
next_sheet after duplicate filter (0, 9)
igvf tissue (712, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (140, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (140, 13)
next_sheet sequence_file (246, 20)
next_sheet after duplicate filter (246, 20)
igvf sequence_file (1908, 20)
reading igvf IGVF_012 https://woldlab.caltech.edu/nextcloud/index.php/s/MmatjmzQgofeM2Y/download
next_sheet rodent_donor (11, 25)
next_sheet after duplicate filter (2, 25)
igvf rodent_donor (81, 25)
next_sheet tissue (14, 9)
next_sheet after duplicate filter (6, 9)
igvf tissue (718, 9)
next_sheet multiplexed_sample (8, 7)
next_sheet after duplicate filter (8, 7)
igvf multiplexed_sample (148, 7)
next_sheet measurement_set (8, 14)
next_sheet after duplicate filter (8, 14)
igvf measurement_set (148, 14)
next_sheet sequence_file (32, 20)
next_sheet after duplicate filter (32, 20)
igvf sequence_file (1940, 20)
reading igvf IGVF_013 https://woldlab.caltech.edu/nextcloud/index.php/s/EHret5a6Sjiro4q/download
next_sheet rodent_donor (96, 25)
next_sheet after duplicate filter (32, 25)
igvf rodent_donor (113, 25)
next_sheet tissue (96, 9)
next_sheet after duplicate filter (96, 9)
igvf tissue (814, 9)
next_sheet multiplexed_sample (15, 7)
next_sheet after duplicate filter (15, 7)
igvf multiplexed_sample (163, 7)
next_sheet measurement_set (15, 14)
next_sheet after duplicate filter (15, 14)
igvf measurement_set (163, 15)
next_sheet sequence_file (174, 20)
next_sheet after duplicate filter (174, 20)
igvf sequence_file (2114, 20)
reading igvf IGVF_014 https://woldlab.caltech.edu/nextcloud/index.php/s/GRQCaSZ3WgeonzK/download
next_sheet rodent_donor (8, 25)
next_sheet after duplicate filter (8, 25)
igvf rodent_donor (121, 25)
next_sheet tissue (8, 9)
next_sheet after duplicate filter (8, 9)
igvf tissue (822, 9)
next_sheet multiplexed_sample (8, 7)

next_sheet after duplicate filter (8, 7)
igvf multiplexed_sample (171, 7)
next_sheet measurement_set (8, 14)
next_sheet after duplicate filter (8, 14)
igvf measurement_set (171, 15)
next_sheet sequence_file (16, 20)
next_sheet after duplicate filter (16, 20)
igvf sequence_file (2130, 20)

# quick delete sql table

In [14]:
def truncate(model):
    table_name = model._meta.db_table
    assert "\\" not in table_name
    with django.db.connection.cursor() as cursor:
        # I don't know why the sql params didn't work. this is a sql vulnerability waiting to happen
        cursor.execute("delete from \"{}\"".format(table_name))
        cursor.execute("DELETE FROM SQLITE_SEQUENCE WHERE name=\"{}\"".format(table_name))
        cursor.fetchone()

# Initialize general use tables

These are fairly static tables that are mostly not currently coming from the spreadsheet.

Mouse strain used to but my and their needs drifted too far.

In [15]:
!{sys.executable} manage.py loaddata \
  source \
  platform \
  library_construction_reagent \
  librarybarcode \
  ontologyterm \
  mousestrain

Installed 472 object(s) from 6 fixture(s)

In [16]:
jax_source = models.Source.objects.get(name="jackson-labs")
unc_csbio_source = models.Source.objects.get(name="unc-csbio")

In [17]:
strain_code_to_name = {x.name: x.display_name for x in models.MouseStrain.objects.all()}
strain_name_to_code = {x.display_name: x.name for x in models.MouseStrain.objects.all()}

# Check for new tissue terms

In [18]:
tissue_dissection_to_ontology_map = {
    'Hypothalamus/Pituitary': [("UBERON:0001898","hypothalamus"), ("UBERON:0000007","pituitary gland")],
    'Cerebellum': [("UBERON:0002037","cerebellum")],
    # Hippocampus might be:
    #   Hippocampal formation UBERON:0002421 https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002421
    #   Layer of hippocampus UBERON:0002305 https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002305
    'Cortex/Hippocampus left': [("NTR:0000646","left cerebral cortex"), ("NTR:0000750", "Hippocampal formation left")],
    'Cortex/Hippocampus right': [("NTR:0000647","right cerebral cortex"), ("NTR:0000751", "Hippocampal formation right")],
    'Liver': [("UBERON:0002107", "liver")],
    'Heart': [("UBERON:0000948","heart")],
    'Lung': [("UBERON:0002048","lung")],
    'Adrenal': [("UBERON:0002369","adrenal gland")],
    'Kidney': [("UBERON:0002113","kidney")],
    'Kidney left': [("UBERON:0002113","kidney")],
    'Kidney right': [("UBERON:0002113","kidney")],
    "Ovary": [("UBERON:0000992", "ovary")],    
    'Gonads -1 Ovary': [("UBERON:0000992", "ovary")],
    'Gonads -1 (Ovary)': [("UBERON:0000992", "ovary")],
    'Oviduct': [("UBERON:0000993","oviduct")],
    'Gonads -2 Oviduct': [("UBERON:0000993","oviduct")],
    'Gonads -2 (Oviduct)': [("UBERON:0000993","oviduct")],
    'Gonads - 2 (Oviduct)': [("UBERON:0000993","oviduct")],
    'Perigonadal fat': [("UBERON:0003428", "gonadal fat pad")], #"is closer" to dissection
    'Brown fat': [("UBERON:0001348","brown adipose tissue")], 
    'Soleus': [("UBERON:0001389","soleus muscle")],
    'Plantaris': [("UBERON:0011905","plantaris")],
    'Gastrocnemius': [("UBERON:0001388","gastrocnemius")],
    'Gastrocnemius left': [("UBERON:0001388","gastrocnemius")],
    'Gastrocnemius right': [("UBERON:0001388","gastrocnemius")],
    'TA': [("UBERON:0001385","tibialis anterior")],
    'TA left': [("UBERON:0001385","tibialis anterior")],
    'TA right': [("UBERON:0001385","tibialis anterior")],
    'EDL': [("UBERON:0001386","extensor digitorum longus")],
    'Tail': [("UBERON:0002415","tail")],
    'PBMC - WBC': [("CL:2000001", "peripheral blood mononuclear cell")],
    'Gonads -1 Testis': [("UBERON:0000473","testis")],
    'Gonads -2 Epididymis': [("UBERON:0001301","epididymis")],
    "Left cortex": [("NTR:0000646","left cerebral cortex"),],
    "Cortex left": [("NTR:0000646","left cerebral cortex"),],
    "Right cortex": [("NTR:0000647","right cerebral cortex"),],
    "Cortex right": [("NTR:0000647","right cerebral cortex"),],
    "Left hippocampus": [("NTR:0000750", "Hippocampal formation left")],
    "Hippocampus left": [("NTR:0000750", "Hippocampal formation left")],
    "Right hippocampus": [("NTR:0000751", "Hippocampal formation right")],
    "Hippocampus right": [("NTR:0000751", "Hippocampal formation right")],
    # does left & right matter?
    "Testis left": [("UBERON:0000473", "Testis")],
    "Testis right": [("UBERON:0000473", "Testis")],
    "Epididymis left": [("UBERON:0001301", "Epididymis")],
    "Epididymis right": [("UBERON:0001301", "Epididymis")],
    "Pancreas": [("UBERON:0001264", "Pancreas")],
    "Lungs": [("UBERON:0002048", "Lung")],
}

In [19]:
# We need to map the names used in the spreadsheet to names in the database.

def check_for_new_tissues():
    #term_names = {record.name for record in models.OntologyTerm.objects.all()}
    
    for book_url, sample_sheet_name in sample_sheets:
        tissue_sheet = pandas.read_excel(
            book_url, 
            sample_sheet_name,
            usecols=["Tissue"]).dropna(axis=0, how='all')

        for i, row in tissue_sheet.iterrows():
            if not pandas.isnull(row["Tissue"]):
                if not row["Tissue"] in tissue_dissection_to_ontology_map:
                    print(f"{row['Tissue']} is new first seen in {sample_sheet_name}")
                    term_names.add(row['Tissue'])

check_for_new_tissues()

# Load protocol links

In [20]:
def load_protocols():
    from igvf_mice.io import read_sheet
    
    protocol_sheet = pandas.read_excel(
        lizs_sheet_name, 
        sheet_name="Protocols_description",
        header=0,
    ).dropna(axis=0, how="all")
    
    read_sheet.import_protocols(protocol_sheet)
    
    protocols = { x.name: x for x in models.ProtocolLink.objects.all()}
    return protocols

protocols = load_protocols()
print(len(protocols))

14

In [21]:
def load_submitted_mice():
    submitted_mice = {
    }

    for accession_prefix in submitted_sheets:
        for i, row in submitted_sheets[accession_prefix]["rodent_donor"].iterrows():
            if not pandas.isnull(row["accession"]):
                rodent_identifier = row["rodent_identifier"]
                if accession_prefix == "igvftst":
                    see_also_template = "https://api.sandbox.igvf.org/rodent-donors/{}/"
                elif accession_prefix == "igvf":
                    see_also_template = "https://api.data.igvf.org/rodent-donors/{}/"
                if pandas.notnull(row["accession"]):
                    submitted_mice.setdefault(rodent_identifier, []).append({
                        "accession_prefix": accession_prefix,
                        "name": row["accession"],
                        "uuid": row["uuid"],
                        "see_also": see_also_template.format(row["accession"]),
                    })

    print("Loaded {} submitted mice".format(len(submitted_mice)))
    return submitted_mice

In [22]:
def normalize_mice_date(date_column, time_column):
    #los_angeles_tz = zoneinfo.ZoneInfo("America/Los_Angeles")
    
    for date, time in zip(date_column, time_column):
        if pandas.isnull(date):
            yield None
        elif pandas.isnull(time):
            yield None
        else:
            yield datetime.datetime.combine(date, time)


def estrus_cycle(x):
    estrus_stage = {
        "unknown": str(models.EstrusCycle.UNKNOWN),
        "anestrus": str(models.EstrusCycle.ANESTRUS),
        "anestrus>proestrus": str(models.EstrusCycle.ANESTRUS_PROESTRUS),
        "proestrus": str(models.EstrusCycle.PROESTRUS),
        "proestrus/proestrus": str(models.EstrusCycle.PROESTRUS),
        "proestrus>estrus": str(models.EstrusCycle.PROESTRUS_ESTRUS),
        "estrus": str(models.EstrusCycle.ESTRUS),
        "estrus?": str(models.EstrusCycle.ESTRUS),
        "estrus/estrus": str(models.EstrusCycle.ESTRUS),
        "estrus/mestrus": str(models.EstrusCycle.ESTRUS_METESTRUS),
        "metestrus": str(models.EstrusCycle.METESTRUS),
        "metestrus/metestrus": str(models.EstrusCycle.METESTRUS),
        "metestrus>diestrus": str(models.EstrusCycle.METESTRUS_DIESTRUS),
        "metestrus/diestrus": str(models.EstrusCycle.METESTRUS_DIESTRUS),
        "diestrus/mestrus": str(models.EstrusCycle.METESTRUS_DIESTRUS),
        "diestrus": str(models.EstrusCycle.DIESTRUS),
        "diestrus/diestrus": str(models.EstrusCycle.DIESTRUS),
        "diestrus>proestrus": str(models.EstrusCycle.DIESTRUS_PROESTRUS),
    }
    
    if pandas.isnull(x):
        return "NA"
    else:
        return estrus_stage[x.lower()]

    
def get_sex_code(x):
    if pandas.isnull(x) or len(x) == 0:
        return str(models.SexEnum.UNKNOWN)
    else:
        return {
            "female": str(models.SexEnum.FEMALE),
            "male": str(models.SexEnum.MALE),
            "other": str(models.SexEnum.OTHER),
        }[x.lower()]


def normalize_mice_name(name):
    if pandas.isnull(name):
        return  name

    if name == "056_WSBJ_10F->PWKJ_9F":
        name = "056_PWKJ_9F"

    if not name[-1] in ("M", "F"):
        raise ValueError(f"Unrecognized sex field in {name}")        

    name_fields = name.split("_")

    # deal with TERM2R47HNSS_HO
    if len(name_fields) > 3:
        name_fields = [name_fields[0], "_".join(name_fields[1:-1]), name_fields[-1]]
        
    name_fields[1] = normalize_strain(name_fields[1])

    if not name_fields[1] in strain_code_to_name:
        raise ValueError(f"strain background in {name} not recognized line {i+1}")
        
    return "_".join(name_fields)


def normalize_mice_strain_name(x):
    if x in strain_name_to_code:
        return x
    elif x in strain_code_to_name:
        return strain_code_to_name[x]
    else:
        raise ValueError(f"Unrecognized strain name {x}")
        

def load_spreadsheet_mice():
    mice = pandas.read_excel(
        lizs_sheet_name, 
        sheet_name="mice", 
        usecols=range(0,16),
        converters={
            "Dissection ID": int,
            #"RMS number": int_or_none,
            "Sex": get_sex_code,
            "Strain": normalize_mice_strain_name,
        }
    )
    
    strain_name_to_code = {x.display_name: x.name for x in models.MouseStrain.objects.all()}

    print("Loaded", mice.shape[0])
    mice = mice[pandas.notnull(mice["Mouse Name"]) & pandas.notnull(mice["Dissection ID"]) & pandas.notnull(mice["Strain"])]
    print("Filtered null rows", mice.shape[0])
    mice["Mouse Name"] = mice["Mouse Name"].apply(normalize_mice_name)
    mouse_name_fields = mice["Mouse Name"].apply(parse_mouse_name)
    mice["Mouse code"] = [x[1] for x in mouse_name_fields]
    for field_name in ["Dissection start time", "Dissection finish time"]:
        mice[field_name] = list(normalize_mice_date(mice["Dissection Date"], mice[field_name]))
    mice["estrus_cycle"] = mice["Estres cycle stage"].apply(estrus_cycle)
    mice["Strain code"] = mice["Strain"].apply(strain_name_to_code.get)
    mice = mice.drop(columns=["Dissection Date", "Estres cycle stage"])
    
    for i, row in mice.iterrows():
        dissection_prefix = "{:03}".format(row["Dissection ID"])
        if not row["Mouse Name"].startswith(dissection_prefix):
            raise ValueError(f"mouse name {row['Mouse Name']} does not start with {dissection_prefix}")

        
    return mice

mice = load_spreadsheet_mice()
mice.head()

Loaded 997
Filtered null rows 690

,Dissection ID,Mouse Name,Strain,Sex,Timepoint,DOB,Operator,Dissection start time,Dissection finish time,Weight (g),Jax Stock number,RMS number,Housing number,Comments,Mouse code,estrus_cycle,Strain code
1,16,016_B6J_10F,C57BL/6J,F,10 weeks,2022-08-16,GM/SK/HL/ER/GF,2022-10-27 09:01:00,NaT,21.1,#000664,14669,400802.0,More fat around heart and lungs (in whole strain),B6J,D,B6J
2,17,017_B6J_10M,C57BL/6J,M,10 weeks,2022-08-16,GM/SK/HL/ER/GF,2022-10-27 11:44:00,NaT,26.3,#000664,14670,400803.0,NaN,B6J,NA,B6J
3,18,018_B6J_10F,C57BL/6J,F,10 weeks,2022-08-16,GM/SK/HL/ER/GF,2022-10-27 09:38:00,NaT,21.0,#000664,14669,400802.0,NaN,B6J,P,B6J
4,19,019_B6J_10M,C57BL/6J,M,10 weeks,2022-08-16,GM/SK/HL/ER/GF,2022-10-27 12:12:00,NaT,29.0,#000664,14670,400804.0,NaN,B6J,NA,B6J
5,20,020_B6J_10F,C57BL/6J,F,10 weeks,2022-08-16,GM/SK/HL/ER/GF,2022-10-27 10:14:00,NaT,18.5,#000664,14669,400802.0,NaN,B6J,D,B6J

In [104]:

los_angeles = zoneinfo.ZoneInfo("America/Los_Angeles")
dob_aug16 = datetime.datetime(2022, 8, 16)#, tzinfo=los_angeles)
dob_jun20 = datetime.datetime(2023, 6, 20)#, tzinfo=los_angeles)

start_016 = datetime.datetime(2022, 10, 27, 9, 1)#, tzinfo=los_angeles)
start_017 = datetime.datetime(2022, 10, 27, 11, 44)#, tzinfo=los_angeles)
start_144 = datetime.datetime(2023, 8, 28, 11, 15)#, tzinfo=los_angeles)
finish_144 = datetime.datetime(2023, 8, 28, 11, 33)#, tzinfo=los_angeles)



pandas.DataFrame(
            {
                "Mouse Name": ["016_B6J_10F", "017_B6J_10M", "144_B6129S1F1J_10F"],
                "Strain code": ["B6J", "B6J", "B6129S1F1J"],
                "Sex": ["M", "F", "F"],
                "Weight (g)": [21.1, 26.3, 19.9],
                "DOB": [dob_aug16, dob_aug16, dob_jun20],
                "Dissection start time": [start_016, start_017, start_144],
                "Dissection finish time": [None, None, finish_144],
                "Timepoint": ["10 weeks"] * 3,
                "estrus_cycle": ["D", "NA", "DP"],
                "Operator": ["T1", "T2", "T1"],
                "Comments": ["", "", ""],
                "Housing number": [14669, 14670, None],
            }
        )

,Mouse Name,Strain code,Sex,Weight (g),DOB,Dissection start time,Dissection finish time,Timepoint,estrus_cycle,Operator,Comments,Housing number
0,016_B6J_10F,B6J,M,21.1,2022-08-16,2022-10-27 09:01:00,NaT,10 weeks,D,T1,,14669.0
1,017_B6J_10M,B6J,F,26.3,2022-08-16,2022-10-27 11:44:00,NaT,10 weeks,NA,T2,,14670.0
2,144_B6129S1F1J_10F,B6129S1F1J,F,19.9,2023-06-20,2023-08-28 11:15:00,2023-08-28 11:33:00,10 weeks,DP,T1,,NaN

In [23]:
def los_angeles_or_none(value):
    los_angeles_tz = zoneinfo.ZoneInfo("America/Los_Angeles")
    
    if pandas.isnull(value):
        return None
    elif isinstance(value, pandas.Timestamp):
        return value.tz_localize("America/Los_Angeles")
    elif isinstance(value, datetime.datetime):
        return value.astimezone(los_angeles_tz)

def load_mouse_tables(mice, submitted_mice=None):
    if models.Mouse.objects.count() > 0:
        truncate(models.Mouse)

    failed = False
    for i, row in mice.iterrows():
        strain_code = strain_name_to_code[row["Strain"]]

        try:
            strain = models.MouseStrain.objects.get(name=strain_code)
        except models.MouseStrain.DoesNotExist as e:
            print(f"Unable to find {row['Strain']} for row {i+2} with code {strain_code}")
            failed = True
            continue

        housing_number = None if pandas.isnull(row["Housing number"]) else row["Housing number"]
        
        record = models.Mouse(
            # should i use liz's disection id?
            name=row["Mouse Name"],
            strain=strain,
            sex=row["Sex"],
            weight_g=row["Weight (g)"],
            date_of_birth=row["DOB"].date() if not pandas.isnull(row["DOB"]) else None,
            dissection_start_time=los_angeles_or_none(row["Dissection start time"]),
            dissection_end_time=los_angeles_or_none(row["Dissection finish time"]),
            timepoint_description=row["Timepoint"],
            life_stage=models.LifeStageEnum.ADULT,
            estrus_cycle=row["estrus_cycle"],
            operator=str_or_empty(row["Operator"]),
            notes=str_or_empty(row["Comments"]),
            housing_number=housing_number,
        )
        record.save()

        if name in submitted_mice:
            accessions = []
            for accession_record in submitted_mice[name]:
                accession = models.Accession(
                    accession_prefix=accession_record["accession_prefix"],
                    name=accession_record["name"],
                    uuid=accession_record["uuid"],
                    see_also=accession_record["see_also"],
                )
                accession.save()
                accessions.append(accession)
            record.accession.set(accessions)
            record.save()

    print("Currently have {} mice loaded".format(models.Mouse.objects.count()))
    assert not failed, "Check warning messages"
    
load_mouse_tables(mice, load_submitted_mice())

Loaded 121 submitted mice
Currently have 690 mice loaded

In [84]:
m = models.Mouse.objects.get(pk='016_B6J_10F')
m.accession.all()

# Tissues

In [24]:
def load_tissue_sheets(mice):
    tissues = []
    for book_url, tissue_sheet in sample_sheets:
        tissue = pandas.read_excel(
            book_url, 
            sheet_name=tissue_sheet,
            header=0,
        ).dropna(axis=0, how="all")
        if "tube+tissue wight (g)" in tissue.columns:
            print(f"{tissue_sheet} has typoed wight column, renaming to weight")
            tissue = tissue.rename(columns={
                "tube+tissue wight (g)": "tube+tissue weight (g)"
            })
        print(tissue_sheet, tissue.shape)
        tissues.append(tissue)

    combined = pandas.concat(tissues)
    combined = combined[pandas.notnull(combined["Tissue"]) & combined["IGVF Sample BOX"].apply(lambda x: x != "DNA Extraction Optimization")]
    print("Total after filtering", combined.shape)
    
    combined["Mouse_Tissue ID"] = combined["Mouse_Tissue ID"].apply(normalize_strain)

    mouse_tissue_name_fields = combined["Mouse_Tissue ID"].apply(parse_mouse_tissue)
    #for row in mouse_tissue_name_fields:
    #    if not row.mouse_strain in mouse_strain_code_to_name:
    #        raise ValueError(f"tissue strain field in {row} not recognized")

    combined["Mouse name"] = mouse_tissue_name_fields.apply(lambda x: "_".join(x[0:3]))
    mice = mice.set_index("Mouse Name")
    mice_name = set(mice.index)
    combined = combined[combined["Mouse name"].isin(mice_name)]
    print("Total after filtering for mice", combined.shape)

    for i, row in combined.iterrows():
        # this is the "label swap" on spreadsheet rows 602-605.
        if row["Mouse name"] == "092_CASTJ_10F":
            row["Genotype"] = "CASTJ"
            #combined.loc[i, "Genotype"] = "CASTJ"
        # this is the other half the swap on spreadsheet rows 1522-1525
        elif row["Mouse name"] == "046_NZOJ_10F":
            row["Genotype"] = 'NZOJ'
            #combined.loc[i, "Genotype"] = 'NZOJ'
            
        assert row["Genotype"] == mice.loc[row["Mouse name"], "Mouse code"]
    
    assert "tube+tissue wight (g)" not in combined.columns
    return combined

tissue_sheets = load_tissue_sheets(mice)
tissue_sheets.head()

Samples - 8 founders (1621, 16)
Samples - Bridge (416, 23)
Samples - F1s (2090, 18)
Samples - CClines (6488, 18)
Samples - F1s_6mo (1190, 18)
Total after filtering (11713, 30)
Total after filtering for mice (11345, 31)

,IGVF Sample BOX,Mouse_Tissue ID,Unnamed: 2,Tissue,Sex,Genotype,Tube label,tube weight (g),tube+tissue weight (g),tissue weight (mg) or blood volume (ul),...,cryopreserved PBMC location,Dissection Start,Dissection End,Body Weight (g),Collector,Photographer,ƒcast,Dissection start,Dissection end,Mouse name
0,IGVF_Sample_5,016_B6J_10F_01,NaN,Hypothalamus/Pituitary,F,B6J,016-01,1.046,1.118,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,016_B6J_10F
1,IGVF_Sample_5,016_B6J_10F_02,NaN,Cerebellum,F,B6J,016-02,1.046,NaN,-1046,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,016_B6J_10F
2,IGVF_Sample_5,016_B6J_10F_03,NaN,Cortex/Hippocampus left,F,B6J,016-03,1.040,1.181,141,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,016_B6J_10F
3,IGVF_Sample_5,016_B6J_10F_04,NaN,Cortex/Hippocampus right,F,B6J,016-04,1.048,NaN,-1048,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,016_B6J_10F
4,IGVF_Sample_5,016_B6J_10F_05,NaN,Liver,F,B6J,016-05,1.133,2.099,966,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,016_B6J_10F

In [25]:
def parse_timepoint(value):
    value, units = value.split(" ")
    value = float(value)
    
    unit_map = {
        "day": models.AgeUnitsEnum.DAY,
        "days": models.AgeUnitsEnum.DAY,
        "week": models.AgeUnitsEnum.WEEK,
        "weeks": models.AgeUnitsEnum.WEEK,
        "month": models.AgeUnitsEnum.MONTH,
        "months": models.AgeUnitsEnum.MONTH,
    }
    return (value, unit_map[units])

In [26]:
ontology_map = {}
for record in models.OntologyTerm.objects.all():
    ontology_map[record.curie] = record

In [27]:
def load_submitted_tissues():
    submitted_tissues = {}

    for accession_prefix in submitted_sheets:
        for i, row in submitted_sheets[accession_prefix]["tissue"].iterrows():
            if not pandas.isnull(row["accession"]):
                if accession_prefix == "igvftst":
                    see_also_template = "https://api.sandbox.igvf.org/tissues/{}/"
                elif accession_prefix == "igvf":
                    see_also_template = "https://api.data.igvf.org/tissues/{}/"

                aliases = row["aliases:array"].split(",")
                assert len(aliases) == 1
                alias_fields = aliases[0][len("ali-mortazavi:"):].split("_")
                tissue_id = "_".join(alias_fields[0:4])
                if pandas.notnull(row["accession"]):
                    submitted_tissues.setdefault(tissue_id, []).append({
                        "accession_prefix": accession_prefix,
                        "name": row["accession"],
                        "uuid": row["uuid"],
                        "see_also": see_also_template.format(row["accession"]),
                    })

    print(len(submitted_tissues))
    return submitted_tissues

submitted_tissues = load_submitted_tissues()
#len(submitted_tissues)

692

In [28]:
def validate_tissue_genotype(tissue, genotype):
    normalized_genotype = normalize_strain(genotype)
    assert tissue == normalized_genotype, f"{tissue} != {normalized_genotype} ({genotype})"

In [29]:
def load_tissues(tissue_sheets):
    if models.Tissue.objects.count() > 0:
        truncate(models.Tissue)

    submitted_tissues = load_submitted_tissues()
    los_angeles_tz = zoneinfo.ZoneInfo("America/Los_Angeles")
    
    failed = False
    for i, row in tissue_sheets.iterrows():
        mouse_name = row["Mouse name"]
        try:
            mouse = models.Mouse.objects.get(name=mouse_name)
        except models.Mouse.DoesNotExist:
            print("row {}, {} was not found".format(i+2, mouse_name))
            failed = True
            continue

        mouse_tissue = row["Mouse_Tissue ID"]

        genotype = row["Genotype"]

        # this is the "label swap" on spreadsheet rows 602-605.
        if mouse_name == "092_CASTJ_10F":
            genotype = "CASTJ"
        # this is the other half the swap on spreadsheet rows 1522-1525
        elif mouse_name == "046_NZOJ_10F":
            genotype = 'NZOJ'

        validate_tissue_genotype(mouse.strain.name, genotype)

        tissue_terms = []
        for term_curie, term_name in tissue_dissection_to_ontology_map[row["Tissue"]]:
            tissue_terms.append(ontology_map[term_curie])

        #age, age_units = parse_timepoint(row["Timepoint"])

        if pandas.isnull(row["Approx. sac time"]):
            sac_time = datetime.time(0,0,0)
        else:
            sac_time = datetime.time(
                row["Approx. sac time"].hour,
                row["Approx. sac time"].minute,
                row["Approx. sac time"].second,    
            )

        record = models.Tissue(
            mouse=mouse,
            name = mouse_tissue,
            description = row["Tissue"],
            #dissection_time=dissection,
            #age=age,
            #age_units=age_units,
            tube_label=row["Tube label"],
            dissector=str_or_empty(row["Dissector"]),
            dissection_notes=str_or_empty(row["Comment"]),
        )

        if not pandas.isnull(row["Dissection date"]):
            record.dissection = datetime.datetime(
                row["Dissection date"].year,
                row["Dissection date"].month,
                row["Dissection date"].day,
                sac_time.hour,
                sac_time.minute,
                sac_time.second,
                tzinfo=los_angeles_tz,
            )

        tube_weight_label = "tube weight (g)"
        if not pandas.isnull(row[tube_weight_label]):
            record.tube_weight_g = float(row[tube_weight_label])

        total_weight_label = "tube+tissue weight (g)"
        if not pandas.isnull(row[total_weight_label]):
            record.total_weight_g = float(row[total_weight_label])

        record.save()
        record.ontology_term.set(tissue_terms)

        if row["Mouse_Tissue ID"] in submitted_tissues:
            accessions = []
            for accession_row in submitted_tissues[row["Mouse_Tissue ID"]]:
                if pandas.notnull(accession_row["name"]):
                    accession = models.Accession(
                        accession_prefix=accession_row["accession_prefix"],
                        name=accession_row["name"],
                        uuid=accession_row["uuid"],
                        see_also=accession_row["see_also"],
                    )
                    accession.save()
                    accessions.append(accession)
            record.accession.set(accessions)
        record.save()

    assert not failed, "Check warning messages."
    
load_tissues(tissue_sheets)

692

In [30]:
models.Mouse.objects.count()

690

In [31]:
#submitted_tissues[row[mouse_tissue_id_label]], type(submitted_tissues[row[mouse_tissue_id_label]])

# Information from Samples into experiment

- Total barcoded nuclei (Samples into experiment)

Is this FixedTissue, FixedSample, FixedBiosample?

In [32]:
if models.FixedSample.objects.count() > 0:
    truncate(models.FixedSample)

In [33]:
def load_samples_into_experiment(book_name, sheet_name, header=0):
    samples_into_experiment = pandas.read_excel(
        book_name, 
        sheet_name=sheet_name,
        header=header,
        index_col=None,
    ).dropna(how="all")

    # was trying to normalize two row hierarchical headers, 
    #level0 = []
    #level1 = []
    #for header in samples_into_experiment.columns:
    #    level0.append("" if header[0].startswith("Unnamed: ") else header[0])
    #    level1.append(header[1])
    #samples_into_experiment.columns = pandas.MultiIndex.from_arrays([level0, level1], names=["phase", "name"])

    one_based = 1
    header_lines = 2
    failed = False
    for i, row in samples_into_experiment.iterrows():
        line_no = i + one_based + header_lines
        box_name = row["IGVF Fixation BOX"]
        if isinstance(box_name, str):
            box_name = box_name.strip()

        if box_name in ["IGVF_FIX_001", "IGVF_FIX_002"]:
            continue
            
        if pandas.isnull(row["Mouse_Tissue ID"]):
            continue

        tissue_id = normalize_strain(row["Mouse_Tissue ID"])
        pooled_from = row.get("pooled_from")

        if pandas.isnull(tissue_id):
            continue

        #if (tissue_id.endswith("_25") or tissue_id.endswith("_26")) and pandas.isnull(pooled_from):
        #    print(f"How are we going to merge these samples? {tissue_id}")
        #    continue

        if pandas.isnull(pooled_from):
            pooled_from = [tissue_id]
        else:
            pooled_from = [normalize_strain(pooled_id.strip()) for pooled_id in pooled_from.split(",")]

        tissues = []
        for pooled_id in pooled_from:
            try:
                tissues.append(models.Tissue.objects.get(name=pooled_id))
            except models.Tissue.DoesNotExist:
                print(f"Tissue {pooled_id} not found in tissue table on {line_no}")
                failed = True

        weight = row["weight (mg)"]
        fixation_date = row["Fixation date"]
        notes = row["Notes"]

        if weight == "#VALUE!":
            pass
        elif weight < 0:
            pass
        elif pandas.isnull(weight):
            pass
        else:
            total_weight = 0
            for tissue in tissues:
                if not pandas.isnull(tissue.weight_mg):
                    total_weight += tissue.weight_mg

            if not numpy.isclose(total_weight, weight):
                print(f"Sum of tissue weights from {pooled_from} {total_weight} doesn't match {weight}. {line_no}")

        sample_id = normalize_strain(row["Sample ID"]) if not pandas.isnull(row["Sample ID"]) else None
        if not (pandas.isnull(sample_id) or pandas.isnull(tissue_id)):
            if tissue_id != sample_id:
                print(f"If defined, {tissue_id} should equal {sample_id} line {line_no}")
                failed = True

        cap_label = row["Cap label"]
        if not (pandas.isnull(cap_label) or pandas.isnull(sample_id)):
            sample_fields = sample_id.split("_")
            predicted_label = "_".join([sample_fields[0], sample_fields[-1]])
            if predicted_label != cap_label:
                print(f"{cap_label} should equal {predicted_label} line {line_no}")
                failed = True

        well_id = row["wells in Barcoding plate"]

        record = models.FixedSample(
            name=tissue_id,
            tube_label=cap_label,
            fixation_name=box_name,
            fixation_date=date_or_none(row["Fixation date"]),
            starting_nuclei=int_or_none(row["Total nuclei (x10^6)"]),
            nuclei_into_fixation=int_or_none(row["Nuclei into fixation (x10^6)"]),
            fixed_nuclei=int_or_none(row["Total fixed nuclei (x10^6)"]),
            aliquots_made=int_or_none(row["# aliquots"]),
            aliquot_volume_ul=float_or_none(row["uL per aliquot"]),
        )
        record.save()
        record.tissue.set(tissues)
        record.save()

    #assert not failed, "Check warning messages"

In [34]:
load_samples_into_experiment(founder_sheet_name, "Founder Samples into experiment", header=1)

Sum of tissue weights from ['046_NZOJ_10F_17'] 116.0 doesn't match 190. 558
Sum of tissue weights from ['095_CASTJ_10M_08'] 11.0 doesn't match 15. 749

In [35]:
load_samples_into_experiment(lizs_sheet_name, "Bridge samples into experiment", header=0)

In [36]:
load_samples_into_experiment(lizs_sheet_name, "F1 Samples into experiment", header=1)

Sum of tissue weights from ['144_B6129S1F1J_10F_05'] 995.0 doesn't match 111.0. 222
Tissue 128_B6AF1J_10F_27 not found in tissue table on 414
Tissue 128_B6AF1J_10F_29 not found in tissue table on 414
Tissue 127_B6AF1J_10M_10 not found in tissue table on 415
Tissue 127_B6AF1J_10M_11 not found in tissue table on 415
Tissue 130_B6AF1J_10F_27 not found in tissue table on 416
Tissue 130_B6AF1J_10F_29 not found in tissue table on 416
Sum of tissue weights from ['130_B6AF1J_10F_27', '130_B6AF1J_10F_29'] 0 doesn't match 169.1. 416
Tissue 129_B6AF1J_10M_10 not found in tissue table on 417
Tissue 129_B6AF1J_10M_11 not found in tissue table on 417
Tissue 132_B6AF1J_10F_27 not found in tissue table on 418
Tissue 132_B6AF1J_10F_29 not found in tissue table on 418
Tissue 131_B6AF1J_10M_10 not found in tissue table on 419
Tissue 131_B6AF1J_10M_11 not found in tissue table on 419
Tissue 138_B6AF1J_10F_27 not found in tissue table on 420
Tissue 138_B6AF1J_10F_29 not found in tissue table on 420
Tissue 133_B6AF1J_10M_10 not found in tissue table on 421
Tissue 133_B6AF1J_10M_11 not found in tissue table on 421
Tissue 144_B6129S1F1J_10F_27 not found in tissue table on 422
Tissue 144_B6129S1F1J_10F_29 not found in tissue table on 422
Sum of tissue weights from ['144_B6129S1F1J_10F_27', '144_B6129S1F1J_10F_29'] 0 doesn't match 953.0. 422
Tissue 143_B6129S1F1J_10M_10 not found in tissue table on 423
Tissue 143_B6129S1F1J_10M_11 not found in tissue table on 423
Tissue 150_B6129S1F1J_10F_27 not found in tissue table on 424
Tissue 150_B6129S1F1J_10F_29 not found in tissue table on 424
Tissue 153_B6129S1F1J_10M_10 not found in tissue table on 425
Tissue 153_B6129S1F1J_10M_11 not found in tissue table on 425
Sum of tissue weights from ['153_B6129S1F1J_10M_10', '153_B6129S1F1J_10M_11'] 0 doesn't match 1055.0. 425
Tissue 152_B6129S1F1J_10F_27 not found in tissue table on 426
Tissue 152_B6129S1F1J_10F_29 not found in tissue table on 426
Tissue 155_B6129S1F1J_10M_10 not found in tissue table on 427
Tissue 155_B6129S1F1J_10M_11 not found in tissue table on 427
Tissue 156_B6129S1F1J_10F_27 not found in tissue table on 428
Tissue 156_B6129S1F1J_10F_29 not found in tissue table on 428
Tissue 157_B6129S1F1J_10M_10 not found in tissue table on 429
Tissue 157_B6129S1F1J_10M_11 not found in tissue table on 429
Tissue 164_B6NODF1J_10F_27 not found in tissue table on 430
Tissue 164_B6NODF1J_10F_29 not found in tissue table on 430
Tissue 159_B6NODF1J_10M_10 not found in tissue table on 431
Tissue 159_B6NODF1J_10M_11 not found in tissue table on 431
Tissue 166_B6NODF1J_10F_27 not found in tissue table on 432
Tissue 166_B6NODF1J_10F_29 not found in tissue table on 432
Tissue 161_B6NODF1J_10M_10 not found in tissue table on 433
Tissue 161_B6NODF1J_10M_11 not found in tissue table on 433
Tissue 170_B6NODF1J_10F_27 not found in tissue table on 434
Tissue 170_B6NODF1J_10F_29 not found in tissue table on 434
Sum of tissue weights from ['170_B6NODF1J_10F_27', '170_B6NODF1J_10F_29'] 0 doesn't match 1083.0. 434
Tissue 165_B6NODF1J_10M_10 not found in tissue table on 435
Tissue 165_B6NODF1J_10M_11 not found in tissue table on 435
Tissue 172_B6NODF1J_10F_27 not found in tissue table on 436
Tissue 172_B6NODF1J_10F_29 not found in tissue table on 436
Tissue 167_B6NODF1J_10M_10 not found in tissue table on 437
Tissue 167_B6NODF1J_10M_11 not found in tissue table on 437
Tissue 178_B6NZOF1J_10F_27 not found in tissue table on 438
Tissue 178_B6NZOF1J_10F_29 not found in tissue table on 438
Tissue 175_B6NZOF1J_10M_10 not found in tissue table on 439
Tissue 175_B6NZOF1J_10M_11 not found in tissue table on 439
Tissue 180_B6NZOF1J_10F_27 not found in tissue table on 440
Tissue 180_B6NZOF1J_10F_29 not found in tissue table on 440
Tissue 177_B6NZOF1J_10M_10 not found in tissue table on 441
Tissue 177_B6NZOF1J_10M_11 not found in tissue table on 441
Tissue 188_B6NZOF1J_10F_27 not found in tissue table on 442
Tissue 188_B6NZOF1J_10F_29 not found in tissue table on 442
Tissue 181_B6NZOF1J_10M_10 not found in tissue table on 443
Tissue 181_B6NZOF1J_10M_11 not found in tissue table on 443
Sum of tissue weights from ['181_B6NZOF1J_10M_10', '181_B6NZOF1J_10M_11'] 0 doesn't match 1134.0. 443
Tissue 190_B6NZOF1J_10F_27 not found in tissue table on 444
Tissue 190_B6NZOF1J_10F_29 not found in tissue table on 444
Sum of tissue weights from ['190_B6NZOF1J_10F_27', '190_B6NZOF1J_10F_29'] 0 doesn't match 937.0. 444
Tissue 185_B6NZOF1J_10M_10 not found in tissue table on 445
Tissue 185_B6NZOF1J_10M_11 not found in tissue table on 445
Tissue 194_B6CASTF1J_10F_27 not found in tissue table on 446
Tissue 194_B6CASTF1J_10F_29 not found in tissue table on 446
Tissue 191_B6CASTF1J_10M_10 not found in tissue table on 447
Tissue 191_B6CASTF1J_10M_11 not found in tissue table on 447
Tissue 196_B6CASTF1J_10F_27 not found in tissue table on 448
Tissue 196_B6CASTF1J_10F_29 not found in tissue table on 448
Tissue 193_B6CASTF1J_10M_10 not found in tissue table on 449
Tissue 193_B6CASTF1J_10M_11 not found in tissue table on 449
Tissue 202_B6CASTF1J_10F_27 not found in tissue table on 450
Tissue 202_B6CASTF1J_10F_29 not found in tissue table on 450
Tissue 195_B6CASTF1J_10M_10 not found in tissue table on 451
Tissue 195_B6CASTF1J_10M_11 not found in tissue table on 451
Tissue 204_B6CASTF1J_10F_27 not found in tissue table on 452
Tissue 204_B6CASTF1J_10F_29 not found in tissue table on 452
Tissue 197_B6CASTF1J_10M_10 not found in tissue table on 453
Tissue 197_B6CASTF1J_10M_11 not found in tissue table on 453
Sum of tissue weights from ['197_B6CASTF1J_10M_10', '197_B6CASTF1J_10M_11'] 0 doesn't match 1174.0. 453
Tissue 210_B6PWKF1J_10F_27 not found in tissue table on 454
Tissue 210_B6PWKF1J_10F_29 not found in tissue table on 454
Tissue 207_B6PWKF1J_10M_10 not found in tissue table on 455
Tissue 207_B6PWKF1J_10M_11 not found in tissue table on 455
Sum of tissue weights from ['207_B6PWKF1J_10M_10', '207_B6PWKF1J_10M_11'] 0 doesn't match 981.0. 455
Tissue 212_B6PWKF1J_10F_27 not found in tissue table on 456
Tissue 212_B6PWKF1J_10F_29 not found in tissue table on 456
Tissue 213_B6PWKF1J_10M_10 not found in tissue table on 457
Tissue 213_B6PWKF1J_10M_11 not found in tissue table on 457
Tissue 216_B6PWKF1J_10F_27 not found in tissue table on 458
Tissue 216_B6PWKF1J_10F_29 not found in tissue table on 458
Sum of tissue weights from ['216_B6PWKF1J_10F_27', '216_B6PWKF1J_10F_29'] 0 doesn't match 973.0. 458
Tissue 215_B6PWKF1J_10M_10 not found in tissue table on 459
Tissue 215_B6PWKF1J_10M_11 not found in tissue table on 459
Tissue 218_B6PWKF1J_10F_27 not found in tissue table on 460
Tissue 218_B6PWKF1J_10F_29 not found in tissue table on 460
Tissue 217_B6PWKF1J_10M_10 not found in tissue table on 461
Tissue 217_B6PWKF1J_10M_11 not found in tissue table on 461
Sum of tissue weights from ['217_B6PWKF1J_10M_10', '217_B6PWKF1J_10M_11'] 0 doesn't match 944.0. 461
Tissue 228_B6WSBF1J_10F_27 not found in tissue table on 462
Tissue 228_B6WSBF1J_10F_29 not found in tissue table on 462
Tissue 223_B6WSBF1J_10M_10 not found in tissue table on 463
Tissue 223_B6WSBF1J_10M_11 not found in tissue table on 463
Sum of tissue weights from ['223_B6WSBF1J_10M_10', '223_B6WSBF1J_10M_11'] 0 doesn't match 1757.0. 463
Tissue 232_B6WSBF1J_10F_27 not found in tissue table on 464
Tissue 232_B6WSBF1J_10F_29 not found in tissue table on 464
Tissue 225_B6WSBF1J_10M_10 not found in tissue table on 465
Tissue 225_B6WSBF1J_10M_11 not found in tissue table on 465
Tissue 234_B6WSBF1J_10F_27 not found in tissue table on 466
Tissue 234_B6WSBF1J_10F_29 not found in tissue table on 466
Tissue 227_B6WSBF1J_10M_10 not found in tissue table on 467
Tissue 227_B6WSBF1J_10M_11 not found in tissue table on 467
Tissue 238_B6WSBF1J_10F_27 not found in tissue table on 468
Tissue 238_B6WSBF1J_10F_29 not found in tissue table on 468
Tissue 229_B6WSBF1J_10M_10 not found in tissue table on 469
Tissue 229_B6WSBF1J_10M_11 not found in tissue table on 469
Tissue 698_B6J_10F_27 not found in tissue table on 470
Tissue 698_B6J_10F_29 not found in tissue table on 470
Tissue 701_B6J_10M_10 not found in tissue table on 471
Tissue 701_B6J_10M_11 not found in tissue table on 471

Tissue 700_B6J_10F_27 not found in tissue table on 472
Tissue 700_B6J_10F_29 not found in tissue table on 472
Tissue 703_B6J_10M_10 not found in tissue table on 473
Tissue 703_B6J_10M_11 not found in tissue table on 473
Tissue 702_B6J_10F_27 not found in tissue table on 474
Tissue 702_B6J_10F_29 not found in tissue table on 474
Tissue 705_B6J_10M_10 not found in tissue table on 475
Tissue 705_B6J_10M_11 not found in tissue table on 475
Tissue 706_B6J_10F_27 not found in tissue table on 476
Tissue 706_B6J_10F_29 not found in tissue table on 476
Tissue 707_B6J_10M_10 not found in tissue table on 477
Tissue 707_B6J_10M_11 not found in tissue table on 477
Sum of tissue weights from ['707_B6J_10M_10', '707_B6J_10M_11'] 0 doesn't match 238.0. 477

In [37]:
# According to Liz this sheet isn't ready yet.
# load_samples_into_experiment(lizs_sheet_name, "CC Samples into experiment", header=1)

# Plate layout

(the hard thing)

In [38]:
WellContent = namedtuple("well_content", ["genotype", "tissue_id"])

def get_genotype_from_tissue(tissue_id):
    assert pandas.notnull(tissue_id)

    fields = tissue_id.split("_")
    assert len(fields) == 4, f"Field label validation fail {tissue_id}, not enough fields {len(fields)}"

    return normalize_strain(fields[1])

assert get_genotype_from_tissue("016_B6J_10F_20") == "B6J"
assert get_genotype_from_tissue("046_NZOJ_10F_03") == "NZOJ"
assert get_genotype_from_tissue("198_B6CASTF1/J_10F_20") == "B6CASTF1J"



def validate_tissue_ids(contents, expected_genotypes):
    for expected, (row_index, row) in zip(expected_genotypes, contents.iterrows()):
        for cell in row:
            fields = cell.split("_")
            assert len(fields) == 4, f"Field label validation fail {cell}"
            # there's a few sample swaps, don't validate them.
            if expected == "Mixed":
                continue
            elif fields[1] not in ("092_CASTJ_10F_03"):
                assert fields[1] == expected, f"{fields[1]} failed to match {expected}"


def is_plate_name(name):
    return not pandas.isnull(name) and name.startswith("IGVF_")

def find_plate_start(sheet, offsets):
    block_headers = [
        "M","F","Mixed","B6J","NODJ","AJ","PWKJ","129S1J","CASTJ","WSBJ","NZOJ","B6CASTF1/J","B6PWKF1/J","B6WSBF1/J","B6NODF1/J"
    ]
    for plate_id_row in sheet[sheet[offsets["plate_label"]].apply(is_plate_name)].index:
        plate_name = normalize_plate_name(sheet.loc[plate_id_row, offsets["plate_label"]])
        for i in range(plate_id_row, plate_id_row + 4):
            cell = sheet.loc[i, offsets["well_start"]]
            if isinstance(cell, str) and (cell.startswith("Tissue") or cell in block_headers):
                yield (plate_name, i)
                
def get_plate_genotype(sheet, start, offsets):
    plate_tissues = []
    for cell in sheet.loc[start+2:start+9, offsets["tissue_label"]].tolist():
        if not pandas.isnull(cell):
            match = re.match("(B6J|NODJ|AJ|PWKJ|129S1J|CASTJ|WSBJ|NZOJ|Mixed)", cell, re.IGNORECASE)
            if match is not None:
                plate_tissues.append(match.group(0))
            else:
                print("Diffculty matching {} in {} {}".format(cell, start+2, start+9))
    
    return plate_tissues


def validate_plate_column_ids(plate_column_ids):
    expected_column_ids = set(range(1,13))
    for column_id in plate_column_ids:
        assert column_id in expected_column_ids, f"{column_id} {type(column_id)} not in expected_column_ids"
    
def validate_plate_row_ids(plate_row_labels):
    expected_row_labels = set(("A", "B", "C", "D", "E", "F", "G", "H"))
    for row_label in plate_row_labels:
        assert row_label in expected_row_labels, f"{row_label} not in expected labels"
    
def parse_single_well_block(sheet, plate_start, offsets):
    # column ids
    simple_plate_column_ids = sheet.loc[plate_start+1, offsets["well_range"]].tolist()
    validate_plate_column_ids(simple_plate_column_ids)

    plate_row_labels = sheet.loc[plate_start+2:plate_start+9, offsets["well_row_label"]].dropna().tolist()
    validate_plate_row_ids(plate_row_labels)

    contents = sheet.loc[plate_start+2:plate_start+len(plate_row_labels)+1, offsets["well_range"]].copy()
    contents.index = plate_row_labels
    contents.columns = simple_plate_column_ids
    contents = contents.dropna()

    genotypes = get_plate_genotype(sheet, plate_start, offsets)
    validate_tissue_ids(contents, genotypes)

    well_contents = {}
    for well_row, row in contents.iterrows():
        for well_column, tissue_cell in zip(simple_plate_column_ids, row):
            genotype = get_genotype_from_tissue(tissue_cell)
            well_contents[(well_row, str(well_column))] = [WellContent(genotype, tissue_cell)]

    return well_contents

def parse_multiplexed_well_block(sheet, start, expected_genotypes, offsets):
    well_re = re.compile("^[A-H]1?[\d]$")
    wells = sheet.loc[start+3, offsets["well_range"]].tolist()
    for cell in wells:
        if pandas.isnull(cell) or well_re.match(cell) is None:
            raise ValueError(f"well value {cell} in row {start+3} does not look correct")

    contents = sheet.loc[start+0:start+1, offsets["well_range"]]
    contents.columns = [(x[0], x[1:]) for x in wells]
    validate_tissue_ids(contents, expected_genotypes)
    contents.index = expected_genotypes

    well_contents = {}
    for expected_genotype, row in contents.dropna().iterrows():
        for well, tissue_id in row.iteritems():
            genotype = get_genotype_from_tissue(tissue_id)
            well_contents.setdefault(well, []).append(WellContent(genotype, tissue_id))

    return well_contents

def parse_plate(sheet):
    max_rows_from_plate_name_to_well_names = 4

    offsets = {
        "plate_label": 1,
        "tissue_label": 1,
        "well_row_label": 2,
        "well_start": 3,
        "well_range": slice(3, 10),
    }
    offsets_simple = offsets.copy()
    offsets_simple["well_range"] = slice(3, 14)

    for plate_name, plate_start in find_plate_start(sheet, offsets):
        if plate_name.endswith("XX"):
            return

        well_contents = {}
        genotypes = get_plate_genotype(sheet, plate_start, offsets)
        
        if plate_name in ("IGVF_B01", "IGVF_012", "IGVF_013", "IGVF_014"):
            well_contents.update(parse_single_well_block(sheet, plate_start, offsets_simple))
            complex_blocks = []        
        else:
            well_contents.update(parse_single_well_block(sheet, plate_start, offsets))

            complex_blocks = [
                (plate_start + 12, slice(0, 2)),
                (plate_start + 12 + 5, slice(2, 4)),
                (plate_start + 12 + 10, slice(4, 6)),
                (plate_start + 12 + 15, slice(6, 8)),
            ]

            for complex_start, genotype_slice in complex_blocks:
                expected_genotypes = genotypes[genotype_slice]
                well_contents.update(parse_multiplexed_well_block(sheet, complex_start, expected_genotypes, offsets))
        
        yield (plate_name, well_contents)
        
offsets = {
    "plate_label": 1,
    "tissue_label": 1,
    "well_row_label": 2,
    "well_start": 3,
    "well_range": slice(3, 14),
}

In [39]:
        
plate_layout = pandas.read_excel(
    lizs_sheet_name, 
    sheet_name="Plate setups",
    header=None,
)


for plate_name, plate_contents in parse_plate(plate_layout):
    print(plate_name, len(plate_contents))

IGVF_003 96
IGVF_004 96
IGVF_005 96
IGVF_006 96
IGVF_007 96
IGVF_008 96
IGVF_008B 96
IGVF_B01 48
IGVF_009 96
IGVF_010 96
IGVF_011 96
IGVF_012 48
Diffculty matching Tissue1_F_rep1 in 408 415
Diffculty matching Tissue1_M_rep1 in 408 415
Diffculty matching Tissue1_F_rep2 in 408 415
Diffculty matching Tissue1_M_rep2 in 408 415
Diffculty matching Tissue1_F_rep3 in 408 415
Diffculty matching Tissue1_M_rep3 in 408 415
Diffculty matching Tissue1_F_rep4 in 408 415
Diffculty matching Tissue1_M_rep4 in 408 415
Diffculty matching Tissue1_F_rep1 in 408 415
Diffculty matching Tissue1_M_rep1 in 408 415
Diffculty matching Tissue1_F_rep2 in 408 415
Diffculty matching Tissue1_M_rep2 in 408 415
Diffculty matching Tissue1_F_rep3 in 408 415
Diffculty matching Tissue1_M_rep3 in 408 415
Diffculty matching Tissue1_F_rep4 in 408 415
Diffculty matching Tissue1_M_rep4 in 408 415
IGVF_013 96

In [40]:
# half height 4 row plates
well_contents = parse_single_well_block(plate_layout, 257, offsets)
assert len(well_contents) == 48, f"{len(well_contents)}"

well_contents = parse_single_well_block(plate_layout, 395, offsets)
assert len(well_contents) == 48, f"{len(well_contents)}"

# Full length 8 row plate
well_contents = parse_single_well_block(plate_layout, 406, offsets)
assert len(well_contents) == 96, f"{len(well_contents)}"
#print(well_contents)

Diffculty matching Tissue1_F_rep1 in 408 415
Diffculty matching Tissue1_M_rep1 in 408 415
Diffculty matching Tissue1_F_rep2 in 408 415
Diffculty matching Tissue1_M_rep2 in 408 415
Diffculty matching Tissue1_F_rep3 in 408 415
Diffculty matching Tissue1_M_rep3 in 408 415
Diffculty matching Tissue1_F_rep4 in 408 415
Diffculty matching Tissue1_M_rep4 in 408 415

In [41]:
models.LibraryConstructionReagent.objects.all()

In [42]:
def guess_barcode_reagent_from_plate(plate_name):
    # Depend on a global to avoid hitting the database a bunch
    wt_mega_2_reagent = models.LibraryConstructionReagent.objects.get(name="wt-mega-v2")
    wt_regular_2_reagent = models.LibraryConstructionReagent.objects.get(name="wt-v2")    
    
    if plate_name in ("IGVF_B01", "IGVF_012"):
        reagent = wt_regular_2_reagent
    else:
        reagent = wt_mega_2_reagent

    return reagent

assert str(guess_barcode_reagent_from_plate("IGVF_003")) == "Parse WT Mega v2"
assert str(guess_barcode_reagent_from_plate("IGVF_012")) == "Parse WT v2"

def load_plates(plate_layout):
    # Validate tissue references:
    failed = False
    for plate_name, plate_contents in parse_plate(plate_layout):
        for well_id in plate_contents:
            well_contents = plate_contents[well_id]

            for well_fraction in well_contents:
                tissue_id = normalize_strain(well_fraction.tissue_id)
                try:
                    biosample = models.FixedSample.objects.get(name=tissue_id)
                except models.FixedSample.DoesNotExist:
                    print(f"Unable to find {tissue_id} on plate {plate_name}")
                    failed = True

    #assert not failed, "Resolve tissues"

    # populate database
    if models.SplitSeqWell.biosample.through.objects.count() > 0:
        truncate(models.SplitSeqWell.biosample.through)

    if models.SplitSeqWell.objects.count() > 0:
        truncate(models.SplitSeqWell)

    if models.SplitSeqPlate.objects.count() > 0:
        truncate(models.SplitSeqPlate)

    errors = 0
    plates_loaded = set()

    for plate_name, plate_contents in parse_plate(plate_layout):
        plates_loaded.add(plate_name)
        plate_record = models.SplitSeqPlate(
            name=plate_name,
            size=models.PlateSizeEnum.size_96,
            pool_location=None,
            date_performed=None,
        )
        plate_record.save()

        for well_id in plate_contents:
            well_contents = plate_contents[well_id]

            biosamples = []
            for well_content in well_contents:
                tissue_id = normalize_strain(well_content.tissue_id)
                try:
                    biosamples.append(models.FixedSample.objects.get(name=tissue_id))
                except models.FixedSample.DoesNotExist:
                    print(f"unable to find tissue {tissue_id} for {plate_name} {well_id}")
                    errors += 1


            reagent = guess_barcode_reagent_from_plate(plate_name)

            barcodes = models.LibraryBarcode.objects.filter(
                reagent=reagent,
                code="{}{}".format(well_id[0], well_id[1]),
            )

            well_record = models.SplitSeqWell(
                plate=plate_record,
                row=well_id[0],
                column=well_id[1],
            )
            well_record.save()
            well_record.biosample.set(biosamples)
            well_record.barcode.set(barcodes)
            well_record.save()

    assert not errors, "Check error messages"
    assert "IGVF_008B" in plates_loaded, "Remember to make copied IGVF_008B plate"
    assert "IGVF_012" in plates_loaded, "Still having trouble with IGVF_012"
    
load_plates(plate_layout)

Diffculty matching Tissue1_F_rep1 in 408 415
Diffculty matching Tissue1_M_rep1 in 408 415
Diffculty matching Tissue1_F_rep2 in 408 415
Diffculty matching Tissue1_M_rep2 in 408 415
Diffculty matching Tissue1_F_rep3 in 408 415
Diffculty matching Tissue1_M_rep3 in 408 415
Diffculty matching Tissue1_F_rep4 in 408 415
Diffculty matching Tissue1_M_rep4 in 408 415
Diffculty matching Tissue1_F_rep1 in 408 415
Diffculty matching Tissue1_M_rep1 in 408 415
Diffculty matching Tissue1_F_rep2 in 408 415
Diffculty matching Tissue1_M_rep2 in 408 415
Diffculty matching Tissue1_F_rep3 in 408 415
Diffculty matching Tissue1_M_rep3 in 408 415
Diffculty matching Tissue1_F_rep4 in 408 415
Diffculty matching Tissue1_M_rep4 in 408 415
Diffculty matching Tissue1_F_rep1 in 408 415
Diffculty matching Tissue1_M_rep1 in 408 415
Diffculty matching Tissue1_F_rep2 in 408 415
Diffculty matching Tissue1_M_rep2 in 408 415
Diffculty matching Tissue1_F_rep3 in 408 415
Diffculty matching Tissue1_M_rep3 in 408 415
Diffculty matching Tissue1_F_rep4 in 408 415
Diffculty matching Tissue1_M_rep4 in 408 415
Diffculty matching Tissue1_F_rep1 in 408 415
Diffculty matching Tissue1_M_rep1 in 408 415
Diffculty matching Tissue1_F_rep2 in 408 415
Diffculty matching Tissue1_M_rep2 in 408 415
Diffculty matching Tissue1_F_rep3 in 408 415
Diffculty matching Tissue1_M_rep3 in 408 415
Diffculty matching Tissue1_F_rep4 in 408 415
Diffculty matching Tissue1_M_rep4 in 408 415

In [43]:
str(guess_barcode_reagent_from_plate("IGVF_003"))

'Parse WT Mega v2'

In [44]:
[x for x in models.Tissue.objects.all() if x.name.startswith("191_B6CAST")]

[<Tissue: 191_B6CASTF1J_10M_01 Hypothalamus/Pituitary>,
 <Tissue: 191_B6CASTF1J_10M_03 Cortex/Hippocampus left>,
 <Tissue: 191_B6CASTF1J_10M_04 Cortex/Hippocampus right>,
 <Tissue: 191_B6CASTF1J_10M_05 Liver>,
 <Tissue: 191_B6CASTF1J_10M_06 Heart>,
 <Tissue: 191_B6CASTF1J_10M_08 Adrenal>,
 <Tissue: 191_B6CASTF1J_10M_19 Tail>,
 <Tissue: 191_B6CASTF1J_10M_20 PBMC - WBC>,
 <Tissue: 191_B6CASTF1J_10M_27 Testis left>,
 <Tissue: 191_B6CASTF1J_10M_28 Testis right>,
 <Tissue: 191_B6CASTF1J_10M_29 Epididymis left>,
 <Tissue: 191_B6CASTF1J_10M_30 Epididymis right>,
 <Tissue: 191_B6CASTF1J_10M_31 Kidney left>,
 <Tissue: 191_B6CASTF1J_10M_32 Kidney right>,
 <Tissue: 191_B6CASTF1J_10M_33 Gastrocnemius left>,
 <Tissue: 191_B6CASTF1J_10M_34 Gastrocnemius right>]

# Submitted measurement sets

In [45]:
def load_submitted_measurement_sets():
    measurement_sets = {}

    for accession_prefix in submitted_sheets:
        for i, row in submitted_sheets[accession_prefix]["measurement_set"].iterrows():
            if not pandas.isnull(row["accession"]):
                aliases = row["aliases:array"].split(',')
                name = aliases[0].replace("ali-mortazavi:", "")

                try:
                    record = models.MeasurementSet.objects.get(name=name)
                except models.MeasurementSet.DoesNotExist:
                    record = models.MeasurementSet(
                        name=name,
                    )
                    record.save()

                    if accession_prefix == "igvftst":
                        see_also_template = "https://api.sandbox.igvf.org/measurment-sets/{}/"
                    elif accession_prefix == "igvf":
                        see_also_template = "https://api.data.igvf.org/measurement-sets/{}/"

                    accession = models.Accession(
                        accession_prefix=accession_prefix,
                        name=row["accession"],
                        uuid=row["uuid"],
                        see_also=see_also_template.format(row["accession"]),
                    )
                    accession.save()
                    record.accession.add(accession)
                    record.save()
                measurement_sets[name] = record
    print("loaded", len(measurement_sets), "measurement_sets")
    return measurement_sets

# Subpool

## Extract meaning from the Experiments tab

- number of nuclei per subpool (Experiment) 
- cDNA amp # PCR cycles (Experiment)
- cDNA ng/ul in 25ul (experiment)
- total cDNA ng (experiment)
- Bioanalyzer cDNA ave bp length (expierment)
- Sub library Index PCR # (experiment)
- Sublibrary Index (experiment)
- Sequence for SampleSheet (experiment)
- library ng/ul (experiment)
- Bioanalyzer library ave bp length (experiment)
- Nextseq run number (experiment)

- number of 67k aliquots  (experiment)
- number of 8k aliquots (experiment)

- QC # raw reads (1 mismatch) (experiment)

In [46]:
experiment = pandas.read_excel(
    lizs_sheet_name, 
    sheet_name="Experiment",
    header=0,
    index_col=None,
    #usecols=range(0, 49)
)
experiment

,Experiment,mice,Fixation Box,Split-seq prep start date,Submit,Submit.1,Protocol,Sublibrary,[Barcoded Nuclei] (nuclei/uL),Barcoded Nuclei Vol. (uL),...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,IGVF_Splitseq_002,B6 (2F+2M),IGVF_FIX_001,2022-08-24,0.0,No,NaN,002_4A,4540,240,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,CAST (2F+2M),IGVF_FIX_002,NaT,0.0,No,NaN,002_4B,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fixation V1,NaN,NaN,NaT,0.0,No,NaN,002_64A,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1M V1,NaN,NaN,NaT,0.0,No,NaN,002_64B,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaT,0.0,No,NaN,002_64C,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
experiment = pandas.read_excel(
    lizs_sheet_name, 
    sheet_name="Experiment",
    header=0,
    index_col=None,
    #usecols=range(0, 49)
).rename(columns={
    # Unnamed: 42 seems like an index or reference to the sample sheet?
    "Unnamed: 43": "Novaseq raw reads",
    "Unnamed: 44": "Novaseq1 L001",
    "Unnamed: 45": "Novaseq1 L002",
    "Unnamed: 46": "Novaseq1 L003",
    "Unnamed: 47": "Novaseq1 L004",
    "Unnamed: 48": "Novaseq2 L001",
    "Unnamed: 49": "Novaseq2 L002",
    "Unnamed: 50": "Novaseq2 L003",
    "Unnamed: 51": "Novaseq2 L004",
})

experiment

,Experiment,mice,Fixation Box,Split-seq prep start date,Submit,Submit.1,Protocol,Sublibrary,[Barcoded Nuclei] (nuclei/uL),Barcoded Nuclei Vol. (uL),...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,IGVF_Splitseq_002,B6 (2F+2M),IGVF_FIX_001,2022-08-24,0.0,No,NaN,002_4A,4540,240,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,CAST (2F+2M),IGVF_FIX_002,NaT,0.0,No,NaN,002_4B,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fixation V1,NaN,NaN,NaT,0.0,No,NaN,002_64A,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1M V1,NaN,NaN,NaT,0.0,No,NaN,002_64B,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaT,0.0,No,NaN,002_64C,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
def is_experiment_name(name):
    not_submittable = ["IGVF_Splitseq_EX"]
    return not pandas.isnull(name) and name.startswith("IGVF_Splitseq")

experiment[experiment["Experiment"].apply(is_experiment_name) & (pandas.notnull(experiment["mice"]))]

,Experiment,mice,Fixation Box,Split-seq prep start date,Submit,Submit.1,Protocol,Sublibrary,[Barcoded Nuclei] (nuclei/uL),Barcoded Nuclei Vol. (uL),...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,IGVF_Splitseq_002,B6 (2F+2M),IGVF_FIX_001,2022-08-24,0.0,No,NaN,002_4A,4540,240,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,IGVF_Splitseq_003,8 founders (4M+4F),IGVF_FIX_003,2022-12-01,0.0,No,NaN,003_8A,6860,250,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
34,IGVF_Splitseq_004,8 founders (4M+4F),IGVF_FIX_005,2022-12-15,0.0,No,NaN,004_8A,2460,640,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
51,IGVF_Splitseq_005,8 founders (4M+4F),IGVF_FIX_010,2023-01-23,0.0,No,NaN,005_8A,4675,390,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
68,IGVF_Splitseq_006,8 founders (4M+4F),IGVF_FIX_006,2023-02-10,0.0,No,NaN,006_8A,3160,780,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
87,IGVF_Splitseq_007,8 founders (4M+4F),IGVF_FIX_006,2023-03-07,0.0,No,NaN,007_8A,2810,580,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
105,IGVF_Splitseq_008,8 founders (4M+4F),IGVF_FIX_008,2023-03-24,0.0,No,NaN,008_8A,2600,250,...,NaN,Total,L001,L002,L003,L004,NaN,NaN,NaN,NaN
117,IGVF_Splitseq_B01,CASTJ + B6J (2M+2F),NaN,2023-04-03,1.0,Yes,"splitseq_100k_v2, left_cortex_nuclei_prep",B01_13A,4920,83.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,IGVF_Splitseq_008B,8 founders (4M+4F),IGVF_FIX_008,2023-04-19,1.0,Yes,"splitseq_1M_v2, male_gonads_nuclei_prep, femal...",008B_67A,3330,250,...,2,1417529714,355914199,355917666,358863075,346834774,NaN,NaN,NaN,NaN
137,IGVF_Splitseq_009,8 founders (4M+4F),IGVF_FIX_004,2023-05-02,1.0,Yes,"splitseq_1M_v2, adrenal_nuclei_prep, kidney_nu...",009_67A,3370,285,...,2,1474101220,177858630,182128617,178436907,177628982,189105418,193500915,191649075,183792676
153,IGVF_Splitseq_010,8 founders (4M+4F),IGVF_FIX_011,NaT,1.0,Yes,"splitseq_1M_v2, kidney_nuclei_prep, gastroc_nu...",010_67A,5440,250,...,2,1276835447,173224540,171233145,172829595,168517796,145490904,150435757,148667669,146436041
169,IGVF_Splitseq_011,8 founders (4M+4F),IGVF_FIX_012,NaT,1.0,Yes,"splitseq_1M_v2, gastroc_nuclei_prep, cortex_hi...",011_67A,6620,250,...,2,1316269124,173623468,170663719,172876343,165573211,158569678,162211611,156551618,156199476
185,IGVF_Splitseq_EX,8 founders (4M+4F),NaN,NaT,1.0,Yes,"splitseq_1M_v2, cortex_hipp_nuclei_prep, heart...",003_13A,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,IGVF_Splitseq_012,B6J,IGVF_Repeats,NaT,1.0,Yes,"splitseq_100k_v2, gastroc_nuclei_prep, cortex_...",012_13A,3220,81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,IGVF_Splitseq_013,8 founders + 4 F1s (4M+4F),IGVF_FIX_021,2023-09-08,1.0,Yes,"splitseq_1M_v2, pbmc_cell_prep, cdna_exome_cap...",013_13A,4160,225,...,NaN,Total,L001,L002,L003,L004,NaN,NaN,NaN,NaN
225,IGVF_Splitseq_014,B6J,IGVF_FIX_021,2023-09-25,1.0,Yes,"splitseq_100k_v2, pbmc_cell_prep",014_13A,1040,97.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,IGVF_Splitseq_015,TREM2R47HNSS_HO,IGVF015_TREM2,2023-11-28,0.0,NaN,"splitseq_1M_v2, gastroc_nuclei_prep, cortex_hi...",015_13A,6620,225,...,Total,L001,L002,L003,L004,L001,L002,L003,L004,L004
253,IGVF_Splitseq_016,8 F1s (4M+4F),IGVF_FIX_013,NaT,0.0,NaN,"splitseq_1M_v2, gastroc_nuclei_prep, cortex_hi...",016_13A,7010,240,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
271,IGVF_Splitseq_017,8 F1s (4M+4F),IGVF_FIX_016,NaT,0.0,NaN,NaN,017_13A,NaN,250,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
289,IGVF_Splitseq_018,8 F1s (4M+4F),IGVF_FIX_013,NaT,0.0,NaN,NaN,018_13A,NaN,250,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
307,IGVF_Splitseq_019,8 F1s (4M+4F),IGVF_FIX_013,NaT,0.0,NaN,NaN,019_13A,NaN,250,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
325,IGVF_Splitseq_020,8 F1s (4M+4F),IGVF_FIX_013,NaT,0.0,NaN,NaN,020_13A,NaN,250,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
343,IGVF_Splitseq_021,8 F1s (4M+4F),IGVF_FIX_013,NaT,0.0,NaN,NaN,021_13A,NaN,250,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
361,IGVF_Splitseq_022,8 F1s (4M+4F),IGVF_FIX_013,NaT,0.0,NaN,NaN,022_13A,NaN,250,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
379,IGVF_Splitseq_023,8 F1s (4M+4F),IGVF_FIX_013,NaT,0.0,NaN,NaN,023_13A,NaN,250,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004

In [49]:
def find_fixation_start(sheet):
    def is_experiment_name(name):
        not_submittable = ["IGVF_Splitseq_EX"]
        return not pandas.isnull(name) and name.startswith("IGVF_Splitseq") # and not name in not_submittable

    has_experiment_name = sheet["Experiment"].apply(is_experiment_name)
    has_mice = pandas.notnull(sheet["mice"])
    has_counts = pandas.notnull(sheet["[Barcoded Nuclei] (nuclei/uL)"])
    for fixation_id_row in sheet[has_experiment_name & has_mice & has_counts].index:
        name = sheet.loc[fixation_id_row, "Experiment"]

        start = fixation_id_row

        stop = sheet.shape[0]
        for i, value in sheet.iloc[start:]["Sublibrary"].iteritems():
            if pandas.isnull(value):
                stop = i - 1
                break

        yield (name, start, stop)

for name, start, stop in find_fixation_start(experiment):
    print(name, start, stop)

IGVF_Splitseq_002 0 15
IGVF_Splitseq_003 17 32
IGVF_Splitseq_004 34 49
IGVF_Splitseq_005 51 66
IGVF_Splitseq_006 68 85
IGVF_Splitseq_007 87 102
IGVF_Splitseq_008 105 114
IGVF_Splitseq_B01 117 124
IGVF_Splitseq_008B 126 135
IGVF_Splitseq_009 137 151
IGVF_Splitseq_010 153 167
IGVF_Splitseq_011 169 183
IGVF_Splitseq_012 196 203
IGVF_Splitseq_013 208 222
IGVF_Splitseq_014 225 232
IGVF_Splitseq_015 235 250
IGVF_Splitseq_016 253 268

In [50]:
def parse_selection_type(value):
    if value is None:
        return None
    elif value.lower() in ("normal", "no"):
        return models.SublibrarySelectionTypeEnum.no_selection
    elif value in ("capture", "EX"):
        return models.SublibrarySelectionTypeEnum.exome_capture
    else:
        raise ValueError(f"Unrecognized capture type {value}")
        
def parse_sample_type(value):
    if value is None:
        return None
    elif value.lower() in ("nuclei",):
        return models.SubcellularComponentEnum.nuclei
    elif value.lower() in ("cells",):
        return models.SubcellularComponentEnum.cellular
    else:
        raise ValueError(f"Unrecognized sample type {value}")


def parse_fixation(sheet, experiment_name, start, stop):
    block = sheet.loc[start:stop]

    experiment_name_fields = experiment_name.split("_")
    plate_name = f"{experiment_name_fields[0]}_{experiment_name_fields[-1]}"
    
    aliquots = {}
    for i, row in block.iterrows():
        count = row["# of backup aliquots"]
        size = row["Backup Aliquot Size"]
        if not (pandas.isnull(count) or pandas.isnull(size)):
            if isinstance(size, str) and size.endswith("k"):
                size = size[:-1]
            size = int(size) * 1000
            aliquots[size] = int(count)
    
    experiment = {
        "experiment_name": experiment_name,
        "plate_name": plate_name,
        "prep_date": block.loc[start, "Split-seq prep start date"],
        "unused_aliquots": aliquots,
        "subpool": [],
    }

    for i, row in block.iterrows():
        if not pandas.isnull(row["Sublibrary"]):
            if pandas.isnull(row["NovaSeq Sequencing date"]):
                novaseq_run_id = None
            else:
                novaseq_run_id = row["NovaSeq Sequencing date"].isoformat().split("T")[0]

            if pandas.isnull(row.get("Novaseq raw reads")):
                novaseq_raw_reads = None
                novaseq1_raw_reads = None
                novaseq2_raw_reads = None
            elif row["Novaseq raw reads"] == "Total":
                novaseq_raw_reads = None
                novaseq1_raw_reads = None
                novaseq2_raw_reads = None
            else:
                novaseq_raw_reads = int_or_none(row.get("Novaseq raw reads"))
                novaseq1_raw_reads = sum([int_or_none(row.get(x)) for x in["Novaseq1 L001", "Novaseq1 L002", "Novaseq1 L003", "Novaseq1 L004"]])
                novaseq2_raw_reads = sum([int_or_none(row.get(x)) for x in["Novaseq2 L001", "Novaseq2 L002", "Novaseq2 L003", "Novaseq2 L004"]])

            if pandas.isnull(row['Protocol']):
                experiment_protocols = None
            else:
                experiment_protocols = []
                for name in row["Protocol"].split(","):
                    name = name.strip()
                    if name in protocols:
                         experiment_protocols.append(protocols[name.strip()])
                    else:
                        print(f"Unable to find protocol for key {name} on {i+1} {row['Sublibrary']}")

            plate_name, subname = row["Sublibrary"].split("_")
            print(row["Sublibrary Type"], row["Sublibrary"])
            subpool = {
                "name": row["Sublibrary"],
                "plate_name": "IGVF_{}".format(plate_name),
                "subpool_subname": subname,
                "submit": row["Submit"],
                "protocols": experiment_protocols,
                "nuclei": int_or_none(row["Nuclei / Sublibrary"]),
                "selection_type": parse_selection_type(row["Sublibrary Type"]),
                "subcellular_component": parse_sample_type(row["Sample Type"]),
                "cdna_pcr_rounds": row["cDNA Amp # PCR Cycles"],
                "cdna_ng_per_ul": row["[cDNA] (ng/uL)"],
                "cdna_volume": row["cDNA Vol. (uL)"],
                #total_cdna = cdna_ng_per_ul_in_25ul * 25
                "bioanalyzer_date": row["BA date"],
                "cdna_average_bp_length": int_or_none(row["cDNA Ave. Length (bp)"]),
                "index_pcr_no": int_or_none(row["Sub library Index PCR #"]),
                "index": str_or_none(row["Sublibrary Index"]),
                "i7_barcode": row["i7 Forward Sequence"],
                "i5_barcode": row["i5 Forward Sequence"],
                "library_ng_per_ul": float_or_none(row["[Library] (ng/ul)"]),
                "library_average_bp_length": float_or_none(row["Library Ave. Length (bp)"]),
                "nextseq_run_date": date_or_none(row["QC Sequencing date"]),
                "nextseq_run_id": str_or_none(int_or_none(row["Nextseq run #"])),
                "nextseq_run_raw_reads": int_or_none(row["QC # raw reads  (1 mismatch)"]),
                "novaseq_run_date": date_or_none(row["NovaSeq Sequencing date"]),
                "novaseq_run_id": novaseq_run_id,
                "novaseq_run_raw_reads": novaseq_raw_reads,
                "novaseq1_raw_reads": novaseq1_raw_reads,
                "novaseq2_raw_reads": novaseq2_raw_reads,
            }
            experiment["subpool"].append(subpool)
            #if not pandas.isnull(subpool["nuclei"]):
            #    nuclei = subpool["nuclei"]
            #    aliquots[nuclei] = aliquots.get(nuclei) + 1

    return experiment

#parse_fixation(experiment, "IGVF_Splitseq_003", 17, 32)
#parse_fixation(experiment, "IGVF_Splitseq_008", 108, 117)
#parse_fixation(experiment, "IGVF_Splitseq_B01", 124, 131)
#parse_fixation(experiment, "IGVF_Splitseq_008B", 133, 143)
#parse_fixation(experiment, "IGVF_Splitseq_EX", 186, 197)
parse_fixation(experiment, 'IGVF_Splitseq_015', 235, 250)

NO 015_13A
NO 015_67A
NO 015_67B
NO 015_67C
NO 015_67D
NO 015_67E
NO 015_67F
NO 015_67G
NO 015_67H
NO 015_67I
NO 015_67J
NO 015_67K
NO 015_67L
NO 015_67M
NO 015_67N
NO 015_67O

{'experiment_name': 'IGVF_Splitseq_015',
 'plate_name': 'IGVF_015',
 'prep_date': Timestamp('2023-11-28 00:00:00'),
 'unused_aliquots': {67000: 7, 13000: 0},
 'subpool': [{'name': '015_13A',
   'plate_name': 'IGVF_015',
   'subpool_subname': '13A',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 13000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 8',
   'cdna_ng_per_ul': 73.5,
   'cdna_volume': 25.0,
   'bioanalyzer_date': Timestamp('2023-12-04 00:00:00'),
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': None,
   'i7_barcode': nan,
   'i5_barcode': nan,
   'library_ng_per_ul': None,
   'library_average_bp_length': None,
   'nextseq_run_date': None,
   'nextseq_run_id': None,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67A',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67A',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 67000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 7',
   'cdna_ng_per_ul': 139.0,
   'cdna_volume': 25.0,
   'bioanalyzer_date': Timestamp('2023-12-04 00:00:00'),
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': None,
   'i7_barcode': nan,
   'i5_barcode': nan,
   'library_ng_per_ul': None,
   'library_average_bp_length': None,
   'nextseq_run_date': None,
   'nextseq_run_id': None,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67B',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67B',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 67000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 7',
   'cdna_ng_per_ul': 142.0,
   'cdna_volume': 25.0,
   'bioanalyzer_date': Timestamp('2023-12-04 00:00:00'),
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': None,
   'i7_barcode': nan,
   'i5_barcode': nan,
   'library_ng_per_ul': None,
   'library_average_bp_length': None,
   'nextseq_run_date': None,
   'nextseq_run_id': None,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67C',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67C',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 67000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 7',
   'cdna_ng_per_ul': 159.0,
   'cdna_volume': 25.0,
   'bioanalyzer_date': Timestamp('2023-12-04 00:00:00'),
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': 'UDI_WT_25',
   'i7_barcode': 'CTCTATCG',
   'i5_barcode': 'CCACCGAT',
   'library_ng_per_ul': 31.6,
   'library_average_bp_length': 458.0,
   'nextseq_run_date': datetime.date(2023, 12, 4),
   'nextseq_run_id': 1082,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67D',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67D',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 67000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 7',
   'cdna_ng_per_ul': 169.0,
   'cdna_volume': 25.0,
   'bioanalyzer_date': Timestamp('2023-12-04 00:00:00'),
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': 'UDI_WT_26',
   'i7_barcode': 'TCCTCATG',
   'i5_barcode': 'CAAGACCT',
   'library_ng_per_ul': 29.8,
   'library_average_bp_length': 473.0,
   'nextseq_run_date': datetime.date(2023, 12, 4),
   'nextseq_run_id': 1082,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67E',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67E',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 67000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 7',
   'cdna_ng_per_ul': 263.0,
   'cdna_volume': 25.0,
   'bioanalyzer_date': Timestamp('2023-12-04 00:00:00'),
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': 'UDI_WT_27',
   'i7_barcode': 'AACAACCG',
   'i5_barcode': 'CGCTTCCT',
   'library_ng_per_ul': 24.6,
   'library_average_bp_length': 468.0,
   'nextseq_run_date': datetime.date(2023, 12, 11),
   'nextseq_run_id': 1083,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67F',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67F',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 67000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 7',
   'cdna_ng_per_ul': 161.0,
   'cdna_volume': 25.0,
   'bioanalyzer_date': Timestamp('2023-12-04 00:00:00'),
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': 'UDI_WT_28',
   'i7_barcode': 'GCCAATGT',
   'i5_barcode': 'ACACATGT',
   'library_ng_per_ul': 23.2,
   'library_average_bp_length': 451.0,
   'nextseq_run_date': datetime.date(2023, 12, 11),
   'nextseq_run_id': 1083,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67G',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67G',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 67000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 7',
   'cdna_ng_per_ul': 83.0,
   'cdna_volume': 25.0,
   'bioanalyzer_date': NaT,
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': None,
   'i7_barcode': nan,
   'i5_barcode': nan,
   'library_ng_per_ul': None,
   'library_average_bp_length': None,
   'nextseq_run_date': None,
   'nextseq_run_id': None,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67H',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67H',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 67000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 7',
   'cdna_ng_per_ul': 30.1,
   'cdna_volume': 25.0,
   'bioanalyzer_date': NaT,
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': None,
   'i7_barcode': nan,
   'i5_barcode': nan,
   'library_ng_per_ul': None,
   'library_average_bp_length': None,
   'nextseq_run_date': None,
   'nextseq_run_id': None,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67I',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67I',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 67000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 7',
   'cdna_ng_per_ul': 99.0,
   'cdna_volume': 25.0,
   'bioanalyzer_date': Timestamp('2023-12-04 00:00:00'),
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': None,
   'i7_barcode': nan,
   'i5_barcode': nan,
   'library_ng_per_ul': None,
   'library_average_bp_length': None,
   'nextseq_run_date': None,
   'nextseq_run_id': None,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67J',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67J',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 67000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 7',
   'cdna_ng_per_ul': 106.0,
   'cdna_volume': 25.0,
   'bioanalyzer_date': Timestamp('2023-12-04 00:00:00'),
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': None,
   'i7_barcode': nan,
   'i5_barcode': nan,
   'library_ng_per_ul': None,
   'library_average_bp_length': None,
   'nextseq_run_date': None,
   'nextseq_run_id': None,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67K',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67K',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 67000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 7',
   'cdna_ng_per_ul': 87.0,
   'cdna_volume': 25.0,
   'bioanalyzer_date': Timestamp('2023-12-04 00:00:00'),
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': None,
   'i7_barcode': nan,
   'i5_barcode': nan,
   'library_ng_per_ul': None,
   'library_average_bp_length': None,
   'nextseq_run_date': None,
   'nextseq_run_id': None,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67L',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67L',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>],
   'nuclei': 67000,
   'selection_type': <SublibrarySelectionTypeEnum.no_selection: 'NO'>,
   'subcellular_component': <SubcellularComponentEnum.cellular: 'C'>,
   'cdna_pcr_rounds': '5 + 7',
   'cdna_ng_per_ul': 89.5,
   'cdna_volume': 25.0,
   'bioanalyzer_date': Timestamp('2023-12-04 00:00:00'),
   'cdna_average_bp_length': None,
   'index_pcr_no': 12,
   'index': None,
   'i7_barcode': nan,
   'i5_barcode': nan,
   'library_ng_per_ul': None,
   'library_average_bp_length': None,
   'nextseq_run_date': None,
   'nextseq_run_id': None,
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '015_67M',
   'plate_name': 'IGVF_015',
   'subpool_subname': '67M',
   'submit': 0.0,
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,

In [51]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.

In [52]:
platforms = {x.name: x for x in models.Platform.objects.all()}
platforms

{'minion': <Platform: Oxford Nanopore MinION>,
 'nextseq2000': <Platform: Nextseq 2000>,
 'novaseq6000': <Platform: Novaseq 6000>,
 'pacbio': <Platform: Pac Bio>,
 'promethion': <Platform: Oxford Nanopore PromethION>}

In [53]:
class SubpoolName:
    def __init__(self, name=None):
        if isinstance(name, str):
            self._normalized = SubpoolName.subpool_name_to_numbers(name)
        elif isinstance(name, list):
            self._normalized = name
        elif name is None:
            self._normalized = None
        else:
            raise ValueError("Unrecognized type {} for {}".format(type(name), name))

    def __str__(self):
        if self._normalized is None:
            return "None"
        else:
            return SubpoolName.numbers_to_subpool_name(self._normalized)
        
    def __repr__(self):
        if self._normalized is None:
            return str("{}()".format(self.__class__.__name__))
        else:
            return str("{}('{}')".format(self.__class__.__name__, str(self)))
        
    def __eq__(self, cmp):
        if self._normalized is None and cmp is None:
            return True
        elif self._normalized is None and cmp._normalized is None:
            return True
        elif self._normalized is None or cmp._normalized is None:
            return False
        elif len(self._normalized) != len(cmp._normalized):
            return False
        else:
            for left, right in zip(self._normalized, cmp._normalized):
                if left != right:
                    return False
                
        return True
    
    def __lt__(self, cmp):
        if self._normalized is None and cmp is None:
            return False
        elif self._normalized is None and cmp._normalized is None:
            return False
        elif self._normalized is None:
            return True
        elif cmp is None or cmp._normalized is None:
            return False
        elif self._normalized[0] < cmp._normalized[0]:
            return True
        elif len(self._normalized) < len(cmp._normalized):
            return True
        elif len(self._normalized) > len(cmp._normalized):
            return False
        else:
            for left, right in zip(self._normalized, cmp._normalized):
                if left == right:
                    continue
                elif left < right:
                    return True
                else:
                    return False
                
        return False
                
    def __gt__(self, cmp):
        if self._normalized is None and cmp is None:
            return False
        elif self._normalized is None and cmp._normalized is None:
            return False
        elif cmp is None or cmp._normalized is None:
            return True
        elif self._normalized[0] > cmp._normalized[0]:
            return True
        elif len(self._normalized) < len(cmp._normalized):
            return False
        elif len(self._normalized) > len(cmp._normalized):
            return True
        else:
            for left, right in zip(self._normalized, cmp._normalized):
                if left == right:
                    continue
                elif left < right:
                    return False
                else:
                    return True
            
        return False
        
    @classmethod
    def subpool_name_to_numbers(cls, name):
        STATE_DIGITS = 1
        STATE_LETTERS = 2
        STATE_ERROR = -1

        digits = []
        letters = []
        state = STATE_DIGITS
        for char in name:
            if state == STATE_DIGITS:
                if char.isdigit():
                    digits.append(char)
                elif char.isalpha():
                    state = STATE_LETTERS
                    letters.append(char)
                else:
                    raise ValueError("Unrecognized symbol {} in {}".format(char, name))
            elif state == STATE_LETTERS:
                if char.isdigit():
                    raise ValueError("Unexpected digit {} in {}".format(char, name))
                elif char.isalpha():
                    letters.append(char)
                else:
                    raise ValueError("Unrecognized symbol {} in {}".format(char, name))

        result = [int("".join(digits))]
        for number in letters:
            if number < "A" or number > "Z":
                raise ValueError("out of bounds letter code in {}".format(name))
            else:
                result.append(ord(number) - ord("A"))

        return result

    @classmethod
    def numbers_to_subpool_name(cls, subpool_list):

        result = [str(subpool_list[0])]
        for char in subpool_list[1:]:
            result.append(chr(char + ord("A")))

        return "".join(result)

    def next_code(self):
        if self._normalized is None:
            return None

        carry = 0
        advancable = []
        for i, place in enumerate(reversed(self._normalized[1:])):
            if i == 0:
                place += 1
            else:
                place += carry
                carry = 0

            if place > 25:
                carry = 1
                place = 0

            advancable.append(place)

        if carry > 0:
            advancable.append(0)

        result = [self._normalized[0]]
        result.extend(reversed(advancable))
        
        return SubpoolName(result)

s = SubpoolName("8ACZ")
print(s)

decoded = SubpoolName.subpool_name_to_numbers("8ACZ") 
print("decoded", decoded)
encoded = SubpoolName.numbers_to_subpool_name(decoded)
print("encoded", encoded)

print(SubpoolName("8ACZ").next_code())



for pairs in [("8A", "8B"), ("8AA", "8Z"), ("8B", "8E"), ("8B", "8A"), ("8Z", "8AA"), ("67A", "67A"), ("8AA", "8AB")]:
    left = SubpoolName(pairs[0])
    right = SubpoolName(pairs[1])
    print(left, right, left < right, left == right, left > right)
    
print(max(SubpoolName("8A"), SubpoolName("8B")))
print(max(None, SubpoolName("8B")))
print(max(SubpoolName("8A"), None))

8ACZ
decoded [8, 0, 2, 25]
encoded 8ACZ
8ADA
8A 8B True False False
8AA 8Z False False True
8B 8E True False False
8B 8A False False True
8Z 8AA True False False
67A 67A False True False
8AA 8AB True False False
8B
8B
8A

# load subpools, sequencing runs and subpools in sequencing run

In [54]:
def load_submitted_multiplexed_samples():
    multiplexed_samples = {}

    for accession_prefix in submitted_sheets:
        for i, row in submitted_sheets[accession_prefix]["multiplexed_sample"].iterrows():
            if not pandas.isnull(row["accession"]):
                aliases = row["aliases:array"].split(',')
                name = aliases[0].replace("ali-mortazavi:", "")
                if accession_prefix == "igvftst":
                    see_also_template = "https://api.sandbox.igvf.org/multiplexed-samples/{}/"
                elif accession_prefix == "igvf":
                    see_also_template = "https://api.data.igvf.org/multiplexed-samples/{}/"

                multiplexed_samples.setdefault(name, []).append({
                    "accession_prefix": accession_prefix,
                    "name": row["accession"],
                    "uuid": row["uuid"],
                    "see_also": see_also_template.format(row["accession"]),
                })
    print(len(multiplexed_samples))
    
    return multiplexed_samples

In [55]:
def load_split_seq_plates_as_dict():
    plates = {}
    for current_plate in models.SplitSeqPlate.objects.all():
        plates[current_plate.name] = current_plate
    return plates

In [56]:
load_split_seq_plates_as_dict()

{'IGVF_003': <SplitSeqPlate: IGVF_003>,
 'IGVF_004': <SplitSeqPlate: IGVF_004>,
 'IGVF_005': <SplitSeqPlate: IGVF_005>,
 'IGVF_006': <SplitSeqPlate: IGVF_006>,
 'IGVF_007': <SplitSeqPlate: IGVF_007>,
 'IGVF_008': <SplitSeqPlate: IGVF_008>,
 'IGVF_008B': <SplitSeqPlate: IGVF_008B>,
 'IGVF_B01': <SplitSeqPlate: IGVF_B01>,
 'IGVF_009': <SplitSeqPlate: IGVF_009>,
 'IGVF_010': <SplitSeqPlate: IGVF_010>,
 'IGVF_011': <SplitSeqPlate: IGVF_011>,
 'IGVF_012': <SplitSeqPlate: IGVF_012>,
 'IGVF_013': <SplitSeqPlate: IGVF_013>}

In [57]:
for experiment_name, experiment_start, experiment_stop in find_fixation_start(experiment):
    fixation = parse_fixation(experiment, experiment_name, experiment_start, experiment_stop)

NO 002_4A
NO 002_4B
NO 002_64A
NO 002_64B
NO 002_64C
NO 002_64D
NO 002_64E
NO 002_64F
NO 002_64G
NO 002_64H
NO 002_64I
NO 002_64J
NO 002_64K
NO 002_64L
NO 002_64M
NO 002_64N
NO 003_8A
NO 003_67A
NO 003_67B
NO 003_67C
NO 003_67D
NO 003_67E
NO 003_67F
NO 003_67G
NO 003_67H
NO 003_67I
NO 003_67J
NO 003_67K
NO 003_67L
NO 003_67M
NO 003_67N
NO 003_67O
NO 004_8A
NO 004_67A
NO 004_67B
NO 004_67C
NO 004_67D
NO 004_67E
NO 004_67F
NO 004_67G
NO 004_67H
NO 004_67I
NO 004_67J
NO 004_67K
NO 004_67L
NO 004_67M
NO 004_67N
NO 004_67O
NO 005_8A
NO 005_67A
NO 005_67B
NO 005_67C
NO 005_67D
NO 005_67E
NO 005_67F
NO 005_67G
NO 005_67H
NO 005_67I
NO 005_67J
NO 005_67K
NO 005_67L
NO 005_67M
NO 005_67N
NO 005_67O
NO 006_8A
NO 006_67A
NO 006_67B
NO 006_67C
NO 006_67D
NO 006_67E
NO 006_67F
NO 006_67G
NO 006_67H
NO 006_67I
NO 006_67J
NO 006_67K
NO 006_67L
NO 006_67M
NO 006_67N
NO 006_67O
NO 006_67P
NO 006_67Q
NO 007_8A
NO 007_67A
NO 007_67B
NO 007_67C
NO 007_67D
NO 007_67E
NO 007_67F
NO 007_67G
NO 007_67H
NO 007_67I
NO 007_67J
NO 007_67K
NO 007_67L
NO 007_67M
NO 007_67N
NO 007_67O
NO 008_8A
NO 008_67A
NO 008_67B
NO 008_67C
NO 008_67D
NO 008_67E
NO 008_67F
NO 008_67G
NO 008_67H
NO 008_67I
NO B01_13A
NO B01_13B
NO B01_13C
NO B01_13D
NO B01_13E
NO B01_13F
EX B01_13G
NO B01_13H
NO 008B_67A
NO 008B_67B
NO 008B_67C
NO 008B_67D
NO 008B_67E
NO 008B_67F
NO 008B_67G
NO 008B_67H
NO 008B_67I
NO 008B_67J
NO 009_67A
NO 009_67B
NO 009_67C
NO 009_67D
NO 009_67E
NO 009_67F
NO 009_67G
NO 009_67H
NO 009_67I
NO 009_67J
NO 009_67K
NO 009_67L
NO 009_67M
NO 009_67N
NO 009_67O
NO 010_67A
NO 010_67B
NO 010_67C
NO 010_67D
NO 010_67E
NO 010_67F
NO 010_67G
NO 010_67H
NO 010_67I
NO 010_67J
NO 010_67K
NO 010_67L
NO 010_67M
NO 010_67N
NO 010_67O
NO 011_67A
NO 011_67B
NO 011_67C
NO 011_67D
NO 011_67E
NO 011_67F
NO 011_67G
NO 011_67H
NO 011_67I
NO 011_67J
NO 011_67K
NO 011_67L
NO 011_67M
NO 011_67N
NO 011_67O
NO 012_13A
NO 012_13B
NO 012_13C
NO 012_13D
NO 012_13E
NO 012_13F
NO 012_13G
NO 012_13H
EX 013_13A
NO 013_67A
NO 013_67B
NO 013_67C
NO 013_67D
NO 013_67E
NO 013_67F
NO 013_67G
NO 013_67H
NO 013_67I
NO 013_67J
NO 013_67K
NO 013_67L
NO 013_67M
NO 013_67N
NO 014_13A
NO 014_13B
NO 014_13C
NO 014_13D
NO 014_13E
NO 014_13F
NO 014_13G
NO 014_13H
NO 015_13A
NO 015_67A
NO 015_67B
NO 015_67C
NO 015_67D
NO 015_67E
NO 015_67F
NO 015_67G
NO 015_67H
NO 015_67I
NO 015_67J
NO 015_67K
NO 015_67L
NO 015_67M
NO 015_67N
NO 015_67O
Unable to find protocol for key gonads_nuclei_prep on 254 016_13A
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 254 016_13A
EX 016_13A
Unable to find protocol for key gonads_nuclei_prep on 255 016_67A
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 255 016_67A
NO 016_67A
Unable to find protocol for key gonads_nuclei_prep on 256 016_67B
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 256 016_67B
NO 016_67B
Unable to find protocol for key gonads_nuclei_prep on 257 016_67C
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 257 016_67C
NO 016_67C
Unable to find protocol for key gonads_nuclei_prep on 258 016_67D
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 258 016_67D
NO 016_67D
Unable to find protocol for key gonads_nuclei_prep on 259 016_67E
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 259 016_67E
NO 016_67E
Unable to find protocol for key gonads_nuclei_prep on 260 016_67F
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 260 016_67F
NO 016_67F
Unable to find protocol for key gonads_nuclei_prep on 261 016_67G
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 261 016_67G
NO 016_67G
Unable to find protocol for key gonads_nuclei_prep on 262 016_67H
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 262 016_67H
NO 016_67H
Unable to find protocol for key gonads_nuclei_prep on 263 016_67I
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 263 016_67I
NO 016_67I
Unable to find protocol for key gonads_nuclei_prep on 264 016_67J
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 264 016_67J
NO 016_67J
Unable to find protocol for key gonads_nuclei_prep on 265 016_67K
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 265 016_67K
NO 016_67K
Unable to find protocol for key gonads_nuclei_prep on 266 016_67L
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 266 016_67L
NO 016_67L
Unable to find protocol for key gonads_nuclei_prep on 267 016_67M
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 267 016_67M
NO 016_67M
Unable to find protocol for key gonads_nuclei_prep on 268 016_67N
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 268 016_67N
NO 016_67N
Unable to find protocol for key gonads_nuclei_prep on 269 016_67O
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 269 016_67O
NO 016_67O

In [58]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.

In [59]:
def load_experiments_return_submittable_subpools():
    compression=r"(?<compression>gz|bz2|xz|zstd)"
    nanopore_library_name_re_template = r"igvf(?P<run>[\d]+)_(?P<library_id>{library_name})_.*_(?P<fragment>[\d]+)\.fastq\.{compression}"
    nextseq_library_name_re_template = r"(?P<run>[\d]+)_(?P<library_id>{library_name})_(?P<read_id>[RI][\d])\.fastq\.{compression}"
    nextseq_library_index_re_template = r"Sublibrary_(?P<library_id>{library_index})_S(?P<sample_id>[\d]+)_(?P<lane_id>L[\d]+)_(?P<read_id>[RI][\d])_(?P<fragment>[\d]+)\.fastq\.{compression}"
    novaseq_library_index_re_template = r"Sublibrary_(?P<library_id>{library_index})_S(?P<sample_id>[\d]+)_(?P<lane_id>L[\d]+)_(?P<read_id>[RI][\d])_(?P<fragment>[\d]+)\.fastq\.{compression}"

    multiplexed_samples = load_submitted_multiplexed_samples()
    split_seq_plates = load_split_seq_plates_as_dict()

    failed_plates = {"IGVF_006",}
    failed = False
    submittable_subpools = {}
    for experiment_name, experiment_start, experiment_stop in find_fixation_start(experiment):
        fixation = parse_fixation(experiment, experiment_name, experiment_start, experiment_stop)

        if fixation["plate_name"] in failed_plates:
            print(f"Skipping failed plate {plate_name}")
            continue

        last_subpools = {}

        reagent = guess_barcode_reagent_from_plate(fixation["plate_name"])

        for line_offset, subpool in enumerate(fixation["subpool"]):
            if subpool["plate_name"] not in split_seq_plates:
                print("Unable to find plate for {}".format(subpool["plate_name"]))
                continue

            try:
                barcodes = models.LibraryBarcode.objects.filter(
                    reagent=reagent, 
                    barcode_type=None, 
                    code=subpool["index"])
            except models.LibraryBarcode.DoesNotExist:
                print(f"Unable to find barcode {subpool['index']}")
                
            if len(barcodes) == 0:
                print(f"Unable to find barcodes with {reagent} None {subpool['index']}")

            # validate i7 barcodes
            library_i7_barcodes_sequence = {b.i7_sequence for b in barcodes if pandas.notnull(b.i7_sequence)}
            if not pandas.isnull(subpool["i7_barcode"]):
                i7_expected_sequence = set(subpool["i7_barcode"].split(","))
            else:
                i7_expected_sequence = set()
            if library_i7_barcodes_sequence != i7_expected_sequence:
                print(f"{subpool['name']} Database lookup of {subpool['index']} i7_barcodes {library_i7_barcodes_sequence} doesn't match human entry {i7_expected_sequence}")
                print(reagent, subpool["index"], barcodes)
                failed = True
                continue

            # validate i5 barcodes
            library_i5_barcodes_sequence = {b.i5_sequence for b in barcodes if pandas.notnull(b.i5_sequence)}
            if len(library_i5_barcodes_sequence) > 0:
                if not pandas.isnull(subpool["i5_barcode"]):
                    i5_expected_sequence = set(subpool["i5_barcode"].split(","))
                else:
                    i5_expected_sequence = set()
                if library_i5_barcodes_sequence != i5_expected_sequence:
                    print(f"{subpool['name']} Database lookup of i5_barcodes {library_i5_barcodes_sequence} doesn't match human entry {i5_expected_sequence}")
                    failed = True
                    continue

            plate = split_seq_plates[subpool["plate_name"]]
            subpool_prefix = subpool["name"].split("_")[0]
            last_subpools[subpool["nuclei"]] = max(
                last_subpools.get(subpool["nuclei"]), 
                SubpoolName(subpool["subpool_subname"]))

            record = models.Subpool(
                name=subpool["name"],
                plate=plate,
                nuclei=subpool["nuclei"],
                selection_type=subpool["selection_type"],
                cdna_pcr_rounds=subpool["cdna_pcr_rounds"],
                cdna_ng_per_ul=float_or_none(subpool["cdna_ng_per_ul"]),
                cdna_volume=float_or_none(subpool["cdna_volume"]),
                bioanalyzer_date=date_or_none(subpool["bioanalyzer_date"]),
                cdna_average_bp_length=int_or_none(subpool["cdna_average_bp_length"]),
                index_pcr_number=int_or_none(subpool["index_pcr_no"]),
                index=str_or_none(subpool["index"]),
                library_ng_per_ul=float_or_none(subpool["library_ng_per_ul"]),
                library_average_bp_length=int_or_none(subpool["library_average_bp_length"]),
            )
            record.save()
            if subpool["protocols"] is not None and len(subpool["protocols"]) > 0:
                record.protocols.set(subpool["protocols"])
            record.barcode.set(barcodes)
            record.save()

            if pandas.notnull(subpool["submit"]):
                submittable_subpools[subpool["name"]] = subpool["submit"]

            name = "subpool_{}".format(subpool["name"].lower())
            if name in multiplexed_samples:
                for accession_row in multiplexed_samples[name]:
                    if pandas.notnull(accession_row["name"]):
                        print(name, record.name, multiplexed_samples[name])
                        accession = models.Accession(**accession_row)
                        accession.save()
                        record.accession.add(accession)
                        record.save()            

        for nuclei in fixation["unused_aliquots"]:
            if nuclei in last_subpools:
                subpool_name = last_subpools[nuclei]
                for i in range(fixation["unused_aliquots"][nuclei]):
                    subpool_name = subpool_name.next_code()

                    record = models.Subpool(
                        name="{}_{}".format(subpool_prefix, subpool_name),
                        plate=plate,
                        nuclei=nuclei,
                    )
                    print(record.name)
                    record.save()
            else:
                print("No unused aliquots {} {}".format(nuclei, last_subpools))

    #assert not failed
    return submittable_subpools
    
submittable_subpools = load_experiments_return_submittable_subpools()

171
NO 002_4A
NO 002_4B
NO 002_64A
NO 002_64B
NO 002_64C
NO 002_64D
NO 002_64E
NO 002_64F
NO 002_64G
NO 002_64H
NO 002_64I
NO 002_64J
NO 002_64K
NO 002_64L
NO 002_64M
NO 002_64N
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
No unused aliquots 67000 {}
NO 003_8A
NO 003_67A
NO 003_67B
NO 003_67C
NO 003_67D
NO 003_67E
NO 003_67F
NO 003_67G
NO 003_67H
NO 003_67I
NO 003_67J
NO 003_67K
NO 003_67L
NO 003_67M
NO 003_67N
NO 003_67O
003_67P
003_67Q
003_67R
003_67S
003_67T
003_67U
003_67V
003_8B
003_8C
NO 004_8A
NO 004_67A
NO 004_67B
NO 004_67C
NO 004_67D
NO 004_67E
NO 004_67F
NO 004_67G
NO 004_67H
NO 004_67I
NO 004_67J
NO 004_67K
NO 004_67L
NO 004_67M
NO 004_67N
NO 004_67O
004_67P
004_67Q
004_67R
004_67S
004_67T
004_8B
004_8C
NO 005_8A
NO 005_67A
NO 005_67B
NO 005_67C
NO 005_67D
NO 005_67E
NO 005_67F
NO 005_67G
NO 005_67H
NO 005_67I
NO 005_67J
NO 005_67K
NO 005_67L
NO 005_67M
NO 005_67N
NO 005_67O
005_67P
005_67Q
005_67R
005_67S
005_67T
005_67U
005_8B
005_8C
005_8D
005_8E
005_8F
005_8G
005_8H
NO 006_8A
NO 006_67A
NO 006_67B
NO 006_67C
NO 006_67D
NO 006_67E
NO 006_67F
NO 006_67G
NO 006_67H
NO 006_67I
NO 006_67J
NO 006_67K
NO 006_67L
NO 006_67M
NO 006_67N
NO 006_67O
NO 006_67P
NO 006_67Q
Skipping failed plate IGVF_013
NO 007_8A
NO 007_67A
NO 007_67B
NO 007_67C
NO 007_67D
NO 007_67E
NO 007_67F
NO 007_67G
NO 007_67H
NO 007_67I
NO 007_67J
NO 007_67K
NO 007_67L
NO 007_67M
NO 007_67N
NO 007_67O
007_67P
007_67Q
007_67R
007_67S
007_67T
007_67U
007_67V
007_67W
007_8B
007_8C
007_8D
007_8E
007_8F
007_8G
007_8H
007_8I
NO 008_8A
NO 008_67A
NO 008_67B
NO 008_67C
NO 008_67D
NO 008_67E
NO 008_67F
NO 008_67G
NO 008_67H
NO 008_67I
NO B01_13A
NO B01_13B
NO B01_13C
NO B01_13D
NO B01_13E
NO B01_13F
EX B01_13G
NO B01_13H
subpool_b01_13a B01_13A [{'accession_prefix': 'igvftst', 'name': 'TSTSM35366348', 'uuid': '77a93b75-f44a-4aa5-937b-a6788051bc18', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM35366348/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM1676SYRC', 'uuid': 'efad3fdd-f466-4c59-94e0-8791e2bfaa93', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM1676SYRC/'}]
subpool_b01_13a B01_13A [{'accession_prefix': 'igvftst', 'name': 'TSTSM35366348', 'uuid': '77a93b75-f44a-4aa5-937b-a6788051bc18', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM35366348/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM1676SYRC', 'uuid': 'efad3fdd-f466-4c59-94e0-8791e2bfaa93', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM1676SYRC/'}]
subpool_b01_13b B01_13B [{'accession_prefix': 'igvftst', 'name': 'TSTSM99018100', 'uuid': '6cac6a8b-7750-4df6-92cf-fae41082813d', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM99018100/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM1955RVUC', 'uuid': 'f45edb75-5e28-4578-a2d5-395546f64b2a', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM1955RVUC/'}]
subpool_b01_13b B01_13B [{'accession_prefix': 'igvftst', 'name': 'TSTSM99018100', 'uuid': '6cac6a8b-7750-4df6-92cf-fae41082813d', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM99018100/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM1955RVUC', 'uuid': 'f45edb75-5e28-4578-a2d5-395546f64b2a', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM1955RVUC/'}]
subpool_b01_13c B01_13C [{'accession_prefix': 'igvftst', 'name': 'TSTSM36900951', 'uuid': '01858fa2-3c3d-476a-8d81-e82a0612c0e8', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM36900951/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM8093RPKR', 'uuid': '33b1fa8c-53ac-4db9-81e2-df137881c434', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM8093RPKR/'}]
subpool_b01_13c B01_13C [{'accession_prefix': 'igvftst', 'name': 'TSTSM36900951', 'uuid': '01858fa2-3c3d-476a-8d81-e82a0612c0e8', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM36900951/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM8093RPKR', 'uuid': '33b1fa8c-53ac-4db9-81e2-df137881c434', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM8093RPKR/'}]
subpool_b01_13d B01_13D [{'accession_prefix': 'igvftst', 'name': 'TSTSM27245068', 'uuid': 'b69b021b-aa90-41cf-8d1f-cfc59c726b20', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM27245068/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM9603DIDI', 'uuid': 'abb7e2a6-c08b-4a15-88fe-94c5c38a3400', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM9603DIDI/'}]
subpool_b01_13d B01_13D [{'accession_prefix': 'igvftst', 'name': 'TSTSM27245068', 'uuid': 'b69b021b-aa90-41cf-8d1f-cfc59c726b20', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM27245068/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM9603DIDI', 'uuid': 'abb7e2a6-c08b-4a15-88fe-94c5c38a3400', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM9603DIDI/'}]
subpool_b01_13e B01_13E [{'accession_prefix': 'igvftst', 'name': 'TSTSM90710268', 'uuid': '8d44590d-bcb5-46f9-8c87-ea375db12ea9', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM90710268/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM6958ESMJ', 'uuid': '92fcc1a8-9170-4a7c-90f8-5ec339a987d1', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM6958ESMJ/'}]
subpool_b01_13e B01_13E [{'accession_prefix': 'igvftst', 'name': 'TSTSM90710268', 'uuid': '8d44590d-bcb5-46f9-8c87-ea375db12ea9', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM90710268/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM6958ESMJ', 'uuid': '92fcc1a8-9170-4a7c-90f8-5ec339a987d1', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM6958ESMJ/'}]
subpool_b01_13f B01_13F [{'accession_prefix': 'igvftst', 'name': 'TSTSM57985101', 'uuid': '2f34272a-6603-41e0-9820-cf2dd432244b', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM57985101/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM6546CQJB', 'uuid': 'b2e62292-5163-4a73-9861-23a535a97dac', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM6546CQJB/'}]
subpool_b01_13f B01_13F [{'accession_prefix': 'igvftst', 'name': 'TSTSM57985101', 'uuid': '2f34272a-6603-41e0-9820-cf2dd432244b', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM57985101/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM6546CQJB', 'uuid': 'b2e62292-5163-4a73-9861-23a535a97dac', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM6546CQJB/'}]
subpool_b01_13g B01_13G [{'accession_prefix': 'igvftst', 'name': 'TSTSM10953505', 'uuid': 'b0e63479-2caf-4aac-9c98-2ff823f92c74', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM10953505/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM8722YQAW', 'uuid': '00179685-55cf-4dc1-a00a-3f5fb9133288', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM8722YQAW/'}]
subpool_b01_13g B01_13G [{'accession_prefix': 'igvftst', 'name': 'TSTSM10953505', 'uuid': 'b0e63479-2caf-4aac-9c98-2ff823f92c74', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM10953505/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM8722YQAW', 'uuid': '00179685-55cf-4dc1-a00a-3f5fb9133288', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM8722YQAW/'}]
subpool_b01_13h B01_13H [{'accession_prefix': 'igvftst', 'name': 'TSTSM89995437', 'uuid': '5484bec6-4b0e-4488-b3b1-fd4def0022df', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM89995437/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM2294BOOU', 'uuid': 'f25eb07b-ed33-496f-a8d7-83814b4b642f', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM2294BOOU/'}]

subpool_b01_13h B01_13H [{'accession_prefix': 'igvftst', 'name': 'TSTSM89995437', 'uuid': '5484bec6-4b0e-4488-b3b1-fd4def0022df', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM89995437/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM2294BOOU', 'uuid': 'f25eb07b-ed33-496f-a8d7-83814b4b642f', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM2294BOOU/'}]
B01_13I
B01_13J
B01_13K
B01_13L
B01_13M
B01_13N
B01_13O
B01_13P
B01_13Q
B01_13R
NO 008B_67A
NO 008B_67B
NO 008B_67C
NO 008B_67D
NO 008B_67E
NO 008B_67F
NO 008B_67G
NO 008B_67H
NO 008B_67I
NO 008B_67J
No unused aliquots 13000 {67000: SubpoolName('67J')}
NO 009_67A
NO 009_67B
NO 009_67C
NO 009_67D
NO 009_67E
NO 009_67F
NO 009_67G
NO 009_67H
NO 009_67I
NO 009_67J
NO 009_67K
NO 009_67L
NO 009_67M
NO 009_67N
NO 009_67O
No unused aliquots 13000 {67000: SubpoolName('67O')}
NO 010_67A
NO 010_67B
NO 010_67C
NO 010_67D
NO 010_67E
NO 010_67F
NO 010_67G
NO 010_67H
NO 010_67I
NO 010_67J
NO 010_67K
NO 010_67L
NO 010_67M
NO 010_67N
NO 010_67O
010_67P
010_67Q
010_67R
No unused aliquots 13000 {67000: SubpoolName('67O')}
NO 011_67A
NO 011_67B
NO 011_67C
NO 011_67D
NO 011_67E
NO 011_67F
NO 011_67G
NO 011_67H
NO 011_67I
NO 011_67J
NO 011_67K
NO 011_67L
NO 011_67M
NO 011_67N
NO 011_67O
011_67P
011_67Q
011_67R
011_67S
011_67T
011_67U
011_67V
No unused aliquots 13000 {67000: SubpoolName('67O')}
NO 012_13A
NO 012_13B
NO 012_13C
NO 012_13D
NO 012_13E
NO 012_13F
NO 012_13G
NO 012_13H
012_13I
012_13J
012_13K
012_13L
012_13M
012_13N
012_13O
012_13P
012_13Q
012_13R
012_13S
012_13T
EX 013_13A
NO 013_67A
NO 013_67B
NO 013_67C
NO 013_67D
NO 013_67E
NO 013_67F
NO 013_67G
NO 013_67H
NO 013_67I
NO 013_67J
NO 013_67K
NO 013_67L
NO 013_67M
NO 013_67N
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_01
013_13A Database lookup of UDI_WT_01 i7_barcodes set() doesn't match human entry {'CAGATCAC'}
Parse WT Mega v2 UDI_WT_01 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_02
013_67A Database lookup of UDI_WT_02 i7_barcodes set() doesn't match human entry {'ACTGATAG'}
Parse WT Mega v2 UDI_WT_02 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_03
013_67B Database lookup of UDI_WT_03 i7_barcodes set() doesn't match human entry {'GATCAGTC'}
Parse WT Mega v2 UDI_WT_03 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_04
013_67C Database lookup of UDI_WT_04 i7_barcodes set() doesn't match human entry {'CTTGTAAT'}
Parse WT Mega v2 UDI_WT_04 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_05
013_67D Database lookup of UDI_WT_05 i7_barcodes set() doesn't match human entry {'AGTCAAGA'}
Parse WT Mega v2 UDI_WT_05 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_06
013_67E Database lookup of UDI_WT_06 i7_barcodes set() doesn't match human entry {'CCGTCCTA'}
Parse WT Mega v2 UDI_WT_06 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_07
013_67F Database lookup of UDI_WT_07 i7_barcodes set() doesn't match human entry {'GTAGAGTA'}
Parse WT Mega v2 UDI_WT_07 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_08
013_67G Database lookup of UDI_WT_08 i7_barcodes set() doesn't match human entry {'GTCCGCCT'}
Parse WT Mega v2 UDI_WT_08 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_09
013_67H Database lookup of UDI_WT_09 i7_barcodes set() doesn't match human entry {'GTGAAACT'}
Parse WT Mega v2 UDI_WT_09 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_10
013_67I Database lookup of UDI_WT_10 i7_barcodes set() doesn't match human entry {'TCATTCCT'}
Parse WT Mega v2 UDI_WT_10 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_11
013_67J Database lookup of UDI_WT_11 i7_barcodes set() doesn't match human entry {'GGTAGCAT'}
Parse WT Mega v2 UDI_WT_11 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_12
013_67K Database lookup of UDI_WT_12 i7_barcodes set() doesn't match human entry {'ACTTGATC'}
Parse WT Mega v2 UDI_WT_12 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_13
013_67L Database lookup of UDI_WT_13 i7_barcodes set() doesn't match human entry {'ATGAGCAT'}
Parse WT Mega v2 UDI_WT_13 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_14
013_67M Database lookup of UDI_WT_14 i7_barcodes set() doesn't match human entry {'GCGCTATC'}
Parse WT Mega v2 UDI_WT_14 <QuerySet []>
Unable to find barcodes with Parse WT Mega v2 None UDI_WT_15
013_67N Database lookup of UDI_WT_15 i7_barcodes set() doesn't match human entry {'TGACCAGT'}
Parse WT Mega v2 UDI_WT_15 <QuerySet []>
No unused aliquots 67000 {}
No unused aliquots 13000 {}
NO 014_13A
NO 014_13B
NO 014_13C
NO 014_13D
NO 014_13E
NO 014_13F
NO 014_13G
NO 014_13H
Unable to find plate for IGVF_014
Unable to find plate for IGVF_014
Unable to find plate for IGVF_014
Unable to find plate for IGVF_014
Unable to find plate for IGVF_014
Unable to find plate for IGVF_014
Unable to find plate for IGVF_014
Unable to find plate for IGVF_014
No unused aliquots 13000 {}
NO 015_13A
NO 015_67A
NO 015_67B
NO 015_67C
NO 015_67D
NO 015_67E
NO 015_67F
NO 015_67G
NO 015_67H
NO 015_67I
NO 015_67J
NO 015_67K
NO 015_67L
NO 015_67M
NO 015_67N
NO 015_67O
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
Unable to find plate for IGVF_015
No unused aliquots 67000 {}
No unused aliquots 13000 {}
Unable to find protocol for key gonads_nuclei_prep on 254 016_13A
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 254 016_13A
EX 016_13A
Unable to find protocol for key gonads_nuclei_prep on 255 016_67A
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 255 016_67A
NO 016_67A
Unable to find protocol for key gonads_nuclei_prep on 256 016_67B
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 256 016_67B
NO 016_67B
Unable to find protocol for key gonads_nuclei_prep on 257 016_67C
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 257 016_67C
NO 016_67C
Unable to find protocol for key gonads_nuclei_prep on 258 016_67D
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 258 016_67D
NO 016_67D
Unable to find protocol for key gonads_nuclei_prep on 259 016_67E
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 259 016_67E
NO 016_67E
Unable to find protocol for key gonads_nuclei_prep on 260 016_67F
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 260 016_67F
NO 016_67F
Unable to find protocol for key gonads_nuclei_prep on 261 016_67G
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 261 016_67G
NO 016_67G
Unable to find protocol for key gonads_nuclei_prep on 262 016_67H
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 262 016_67H
NO 016_67H
Unable to find protocol for key gonads_nuclei_prep on 263 016_67I
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 263 016_67I
NO 016_67I
Unable to find protocol for key gonads_nuclei_prep on 264 016_67J
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 264 016_67J
NO 016_67J
Unable to find protocol for key gonads_nuclei_prep on 265 016_67K
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 265 016_67K
NO 016_67K
Unable to find protocol for key gonads_nuclei_prep on 266 016_67L
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 266 016_67L
NO 016_67L
Unable to find protocol for key gonads_nuclei_prep on 267 016_67M
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 267 016_67M
NO 016_67M

Unable to find protocol for key gonads_nuclei_prep on 268 016_67N
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 268 016_67N
NO 016_67N
Unable to find protocol for key gonads_nuclei_prep on 269 016_67O
Unable to find protocol for key kidney_nuclei_prep_liver_nuclei_prep on 269 016_67O
NO 016_67O
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
Unable to find plate for IGVF_016
No unused aliquots 67000 {}
No unused aliquots 13000 {}

In [60]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.

In [61]:
models.LibraryBarcode.objects.get(i7_sequence="TAATCGAC")

In [62]:
# Old creating runs from the sample sheet

#    expected_names = {
#        "IGVF_Splitseq_003": {
#            "nanopore": nanopore_library_name_re_template,
#            "nextseq": nextseq_library_name_re_template,
#            "novaseq": novaseq_library_index_re_template,
#        },
#        "IGVF_Splitseq_004": {
#            "nanopore": nanopore_library_name_re_template,
#            "nextseq": nextseq_library_name_re_template,
#            "novaseq": novaseq_library_index_re_template,
#        },
#        "IGVF_Splitseq_005": {
#            "nanopore": nanopore_library_name_re_template,
#            "nextseq": nextseq_library_index_re_template,
#            "novaseq": novaseq_library_index_re_template,
#        },
#        "IGVF_Splitseq_006": {
#            "nanopore": nanopore_library_name_re_template,
#            "nextseq": nextseq_library_index_re_template,
#            "novaseq": novaseq_library_index_re_template,
#        },
#
#    }
#
#    nanopore_runs = {
#        "IGVF_Splitseq_003": {
#            "name": "2023-01-03-8A",
#            "run_date": datetime.datetime(2023,1,3),
#            "raw_reads": 87784162,
#        }
#    }

#        if experiment_name in nanopore_runs and subpool["nuclei"] == 8000:
#            measurement = get_or_create_sequencing_run(
#                # nanopore_runs[experiment_name]["name"]
#                name="{}/{}".format(plate.name.lower(), "nanopore"),
#                run_date=nanopore_runs[experiment_name]["run_date"],
#                platform=platforms["nanopore"],
#                plate=plate,
#            )
#            
#            pattern = expected_names[experiment_name]["nanopore"].format(
#                library_name=subpool["subpool_subname"],
#                library_index=line_offset+1,
#                compression=compression,
#            )
#            
#            run = models.SubpoolInRun(
#                subpool=record,
#                sequencing_run=measurement,
#                raw_reads=nanopore_runs[experiment_name]["raw_reads"],
#                status=models.RunStatus.PASS,
#            )
#            run.save()            
#
#        if subpool["nextseq_run_date"] is not None:
#            measurement = get_or_create_sequencing_run(
#                #sublibrary["nextseq_run_id"]
#                name="{}/{}".format(plate.name.lower(), "nextseq"),
#                run_date=subpool["nextseq_run_date"],
#                platform=platforms["nextseq"],
#                plate=plate,
#            )
#
#            pattern = expected_names[experiment_name]["nextseq"].format(
#                library_name=subpool["subpool_subname"],
#                library_index=line_offset+1,
#                compression=compression,
#            )            
#            
#            run = models.SubpoolInRun(
#                subpool=record,
#                sequencing_run=measurement,
#                raw_reads=subpool["nextseq_run_raw_reads"],
#                status=models.RunStatus.PASS,
#            )
#            run.save()
#            
#        if subpool["novaseq_run_date"] is not None:
#            for i, nova_raw_reads in enumerate([subpool["novaseq1_raw_reads"], subpool["novaseq2_raw_reads"]]):
#                #nova_run_name = "{}-{}".format(sublibrary["novaseq_run_id"], i+1)
#                nova_run_name = "{}/{}".format(plate.name.lower(), "nova{}".format(i+1))
#                measurement = get_or_create_sequencing_run(
#                    name=nova_run_name,
#                    run_date=subpool["novaseq_run_date"],
#                    platform=platforms["novaseq"],
#                    plate=plate,
#                )
#
#                pattern = expected_names[experiment_name]["novaseq"].format(
#                    library_name=subpool["subpool_subname"],
#                    library_index=line_offset+1,
#                    compression=compression,
#                )
#
#                run = models.SubpoolInRun(
#                    subpool=record,
#                    sequencing_run=measurement,
#                    raw_reads=nova_raw_reads,
#                    status=models.RunStatus.PASS,                    
#                )
#                run.save()

In [63]:
def load_fastq_csv():
    fastqs = pandas.read_csv(
        "fastq_metadata.tsv", sep="\t",
        dtype={
            "sample_id": str,
            "read_id": str,
            "fragment": str,
            "sequencer_run": str,
            "lane": str,
        }).sort_values(["experiment", "subpool_name", "index_id", "lane", "read"])
    return fastqs

fastqs = load_fastq_csv()
fastqs.head()

,experiment,family,filename,md5sum,size,ctime,plate_id,subpool_name,fragment,compression,sequencer,sequencer_run,flowcell_id,nuclei,read,barcode,index_id,sample_id,lane,exome_capture
378,igvf_003,illumina,igvf_003/nextseq2/003_13A_R1.fastq.gz,57e977fdfe32850db83ee5f7addb7165,17707636592,2023-10-02,003,13A,NaN,gz,VH00582,6,AAC3V7HHV,13,R1,CAGATC,1,NaN,NaN,EX
377,igvf_003,illumina,igvf_003/nextseq2/003_13A_R2.fastq.gz,148c181e7d81e4aa15611fb2086d5971,10322410034,2023-10-02,003,13A,NaN,gz,VH00582,6,AAC3V7HHV,13,R2,CAGATC,1,NaN,NaN,EX
13,igvf_003,illumina,igvf_003/nextseq/003_67A_R1.fastq.gz,35350d53cf858267d294bce69e475c83,48483277280,2023-09-08,003,67A,NaN,gz,VH00582,1,AAATMGFHV,67,R1,ACTTGA,2,NaN,NaN,NaN
12,igvf_003,illumina,igvf_003/nextseq/003_67A_R2.fastq.gz,00c68ff0f9e0217d422c57e8948d4bb4,32327542019,2023-09-08,003,67A,NaN,gz,VH00582,1,AAATMGFHV,67,R2,ACTTGA,2,NaN,NaN,NaN
14,igvf_003,illumina,igvf_003/nextseq/003_67B_R1.fastq.gz,79db765143bb23e14c613c9e1339e9f7,44182320136,2023-09-08,003,67B,NaN,gz,VH00582,1,AAATMGFHV,67,R1,GATCAG,3,NaN,NaN,NaN

In [64]:
def fastq_metadata_row_to_subpool_name(row):
    if pandas.isnull(row.subpool_name):
        return None
    else:
        return "{}_{}".format(row.plate_id, row.subpool_name)

def get_subpool_from_fastq_row(row):
    plate_name = normalize_plate_name(row.experiment)
    subpool_name = fastq_metadata_row_to_subpool_name(row)

    query = {
        "plate__name": plate_name,
    }
    
    if pandas.notnull(subpool_name):
        query["name"] = subpool_name
    if pandas.notnull(row.index_id):
        query["index"] = str_or_none(row.index_id)
    
    # these are labeled as having X nuclei but actually have fewer nuclei. 
    # Not that you can tell that from the filename
    nuclei_dont_match = {"013_67N", "014_13H"}
    if pandas.notnull(row.nuclei) and subpool_name not in nuclei_dont_match:
        query["nuclei"] = int(row.nuclei)*1000
    if pandas.notnull(row.exome_capture):
        query["selection_type"] = row.exome_capture

    subpools = models.Subpool.objects.filter(**query)
    
    if len(subpools) == 0:
        print("Nothing found for {} {}".format(query, row.filename))
    elif len(subpools) > 1:
        print("Multiple hits for {}: {} {}".format(query, subpools, row.filename))
    else:
        return subpools[0]

from Bio.Seq import Seq
def check_fastq_barcode_is_equal(i7_sequence, i5_sequence, barcode):
    if pandas.isnull(i5_sequence):
        return i7_sequence == barcode
    
    sequences = barcode.split("+")
    if len(sequences) != 2:
        print("Warning: database says dual index, file says single index: {} {} {}".format(i7_sequence, i5_sequence, barcode))
        return False

    i7, i5 = sequences
    # barcodes in the fastq file are reverse complimented.
    i5 = Seq(i5).reverse_complement()
    return i7_sequence == i7 and i5_sequence == i5
    
assert check_fastq_barcode_is_equal("ACTTGA", None, "ACTTGA")
assert not check_fastq_barcode_is_equal("ACTTGA", None, "CTTGTA")
assert check_fastq_barcode_is_equal("GTGAAACT", "AGTCTGTA", "GTGAAACT+TACAGACT")
assert not check_fastq_barcode_is_equal("GTGAAACT", "AGTCTGTA", "ACTTGATC+TTTGGGTG")
assert not check_fastq_barcode_is_equal("GTGAAACT", "AGTCTGTA", "CTTGTA")
print("Finish check_fastq_barcode_is_equal test assertions")

def test_subpool_lookup(fastqs):
    for i, row in fastqs.iterrows():
        subpool = get_subpool_from_fastq_row(row)
        if subpool is None:
            continue
        barcodes = subpool.barcode.filter(barcode_type=None)
        if barcodes.count() != 1:
            print("Barcode count wrong {}".format(barcode))

        barcode = barcodes[0]
        if not check_fastq_barcode_is_equal(barcode.i7_sequence, barcode.i5_sequence, row["barcode"]):
            print(f"Barcode mismatch {subpool.plate_name()} {subpool.index} {barcode.i7_sequence} {barcode.i5_sequence} {row.barcode} {row.filename}")

test_subpool_lookup(fastqs)

Warning: database says dual index, file says single index: GTGAAACT AGTCTGTA CTTGTA
Finish check_fastq_barcode_is_equal test assertions
Nothing found for {'plate__name': 'IGVF_003', 'name': '003_13A', 'index': '1', 'nuclei': 13000, 'selection_type': 'EX'} igvf_003/nextseq2/003_13A_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_003', 'name': '003_13A', 'index': '1', 'nuclei': 13000, 'selection_type': 'EX'} igvf_003/nextseq2/003_13A_R2.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_11.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_4.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_7.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_6.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_8.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_5.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_1.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_2.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_10.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_9.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_3.fastq.gz
Nothing found for {'plate__name': 'IGVF_004', 'name': '004_13A', 'index': '2', 'nuclei': 13000, 'selection_type': 'EX'} igvf_004/nextseq2/004_13A_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_004', 'name': '004_13A', 'index': '2', 'nuclei': 13000, 'selection_type': 'EX'} igvf_004/nextseq2/004_13A_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_005', 'name': '005_13A', 'index': '3', 'nuclei': 13000, 'selection_type': 'EX'} igvf_005/nextseq2/005_13A_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_005', 'name': '005_13A', 'index': '3', 'nuclei': 13000, 'selection_type': 'EX'} igvf_005/nextseq2/005_13A_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_007', 'name': '007_13A', 'index': '4', 'nuclei': 13000, 'selection_type': 'EX'} igvf_007/nextseq2/007_13A_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_007', 'name': '007_13A', 'index': '4', 'nuclei': 13000, 'selection_type': 'EX'} igvf_007/nextseq2/007_13A_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_008B', 'name': '008B_13A', 'index': '5', 'nuclei': 13000, 'selection_type': 'EX'} igvf_008b/nextseq2/008B_13A_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_008B', 'name': '008B_13A', 'index': '5', 'nuclei': 13000, 'selection_type': 'EX'} igvf_008b/nextseq2/008B_13A_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_009', 'name': '009_13A', 'index': '6', 'nuclei': 13000, 'selection_type': 'EX'} igvf_009/nextseq2/009_13A_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_009', 'name': '009_13A', 'index': '6', 'nuclei': 13000, 'selection_type': 'EX'} igvf_009/nextseq2/009_13A_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_010', 'name': '010_13A', 'index': '7', 'nuclei': 13000, 'selection_type': 'EX'} igvf_010/nextseq2/010_13A_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_010', 'name': '010_13A', 'index': '7', 'nuclei': 13000, 'selection_type': 'EX'} igvf_010/nextseq2/010_13A_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_011', 'name': '011_13A', 'index': '8', 'nuclei': 13000, 'selection_type': 'EX'} igvf_011/nextseq2/011_13A_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_011', 'name': '011_13A', 'index': '8', 'nuclei': 13000, 'selection_type': 'EX'} igvf_011/nextseq2/011_13A_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_13A', 'index': 'UDI01', 'nuclei': 13000} igvf_013/nextseq/013_13A_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_13A', 'index': 'UDI01', 'nuclei': 13000} igvf_013/nextseq/013_13A_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L002_R2_001.fastq.gz

Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L002_I2_001.fastq.gz

Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L001_R2_001.fastq.gz

Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000} igvf_013/nextseq/013_67H_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000} igvf_013/nextseq/013_67H_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L004_R2_001.fastq.gz

Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000} igvf_013/nextseq/013_67J_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000} igvf_013/nextseq/013_67J_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L003_R2_001.fastq.gz

Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L001_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L001_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L001_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L001_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L002_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L002_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L002_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L002_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L003_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L003_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L003_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L003_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L004_I1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L004_I2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L004_R1_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L004_R2_001.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13A', 'index': 'UDI17', 'nuclei': 13000} igvf_014/nextseq/014_13A_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13A', 'index': 'UDI17', 'nuclei': 13000} igvf_014/nextseq/014_13A_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13B', 'index': 'UDI18', 'nuclei': 13000} igvf_014/nextseq/014_13B_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13B', 'index': 'UDI18', 'nuclei': 13000} igvf_014/nextseq/014_13B_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13C', 'index': 'UDI19', 'nuclei': 13000} igvf_014/nextseq/014_13C_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13C', 'index': 'UDI19', 'nuclei': 13000} igvf_014/nextseq/014_13C_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13D', 'index': 'UDI20', 'nuclei': 13000} igvf_014/nextseq/014_13D_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13D', 'index': 'UDI20', 'nuclei': 13000} igvf_014/nextseq/014_13D_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13E', 'index': 'UDI21', 'nuclei': 13000} igvf_014/nextseq/014_13E_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13E', 'index': 'UDI21', 'nuclei': 13000} igvf_014/nextseq/014_13E_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13F', 'index': 'UDI22', 'nuclei': 13000} igvf_014/nextseq/014_13F_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13F', 'index': 'UDI22', 'nuclei': 13000} igvf_014/nextseq/014_13F_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13G', 'index': 'UDI23', 'nuclei': 13000} igvf_014/nextseq/014_13G_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13G', 'index': 'UDI23', 'nuclei': 13000} igvf_014/nextseq/014_13G_R2.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13H', 'index': 'UDI24'} igvf_014/nextseq/014_13H_R1.fastq.gz
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13H', 'index': 'UDI24'} igvf_014/nextseq/014_13H_R2.fastq.gz

In [65]:
[(x.index, x.nuclei, x.selection_type) for x in models.Subpool.objects.filter(plate__name="IGVF_013")]

[]

Load information about previously submitted records

In [66]:
submitted_sequence_file = {}

for accession_prefix in submitted_sheets:
    for i, row in submitted_sheets[accession_prefix]["sequence_file"].iterrows():
        if not pandas.isnull(row["accession"]):
            if accession_prefix == "igvftst":
                see_also_template = "https://api.sandbox.igvf.org/sequence-files/{}/"
            elif accession_prefix == "igvf":
                see_also_template = "https://api.data.igvf.org/sequence-files/{}/"
            
            if pandas.notnull(row["accession"]):
                submitted_sequence_file.setdefault(row["submitted_file_name"], []).append({
                    "accession_prefix": accession_prefix,
                    "name": row["accession"],
                    "uuid": row["uuid"],
                    "see_also": see_also_template.format(row["accession"]),
                })
        
print("loaded {} submitted sequence_file records".format(len(submitted_sequence_file)))

loaded 2132 submitted sequence_file records

In [67]:
submitted_sheets.keys()

dict_keys(['igvftst', 'igvf'])

In [68]:
def built_in_cache(a, b, cache={}):
    cache.setdefault(a, b)
    print(cache)
    
built_in_cache('a', 1)
built_in_cache('b', 3)
built_in_cache('c', 4)
built_in_cache('a', 2)

{'a': 1}
{'a': 1, 'b': 3}
{'a': 1, 'b': 3, 'c': 4}
{'a': 1, 'b': 3, 'c': 4}

In [69]:
sequencing_experiments = {}
sequencing_subpools = {}

In [70]:
def get_or_create_sequencing_run(name, run_date, platform, plate, accessions=None):
    if name in sequencing_experiments:
        return sequencing_experiments[name]
    
    try:
        sequencing_run = models.SequencingRun.objects.get(name=name)
    except models.SequencingRun.DoesNotExist:
        sequencing_run = models.SequencingRun(
            name=name,
            run_date=run_date,
            platform=platform,
            plate=plate,
            stranded=models.StrandedEnum.REVERSE,
        )
        sequencing_run.save()
        if accessions is not None:
            sequencing_run.accession.set(accessions)
            sequencing_run.save
        
    sequencing_experiments[name] = sequencing_run
    return sequencing_run

def get_or_create_subpool_in_run(subpool, sequencing_run, status, raw_reads=None, measurement_set=None):
    try:
        subpool_in_run = models.SubpoolInRun.objects.get(subpool=subpool, sequencing_run=sequencing_run)
    except models.SubpoolInRun.DoesNotExist:
        subpool_in_run = models.SubpoolInRun(
            subpool=subpool, 
            sequencing_run=sequencing_run,
            raw_reads=None,
            status=status,
            measurement_set=measurement_set,
        )
        subpool_in_run.save()
        
    sequencing_subpools[name] = subpool_in_run
    return subpool_in_run


def lane_or_none(value):
    if pandas.isnull(value):
        return None
    elif isinstance(value, float):
        return int(value)
    elif value.startswith("L"):
        return int(value[1:])
    else:
        return int(value)

def load_fastqs(submittable_subpools):
    fastqs = load_fastq_csv()
    measurement_sets = load_submitted_measurement_sets()

    for i, row in fastqs.iterrows():
        #plate_name = normalize_plate_name(row.experiment)
        #subpool_name = "{}_{}".format(row.plate_id, row.subpool_name)
        #index_id = int(row.index_id)
        fastq_relative = Path(row.filename)
        sequencing_run_name = str(Path(fastq_relative.parts[0])/fastq_relative.parts[1])
        sequencer = row.get("sequencer")
        run_date = row["ctime"]
        md5sum = row["md5sum"]

        #if row["read_id"] in ('I1',):
        #    continue

        subpool = get_subpool_from_fastq_row(row)

        if subpool is None:
            print("Unable to import {row.filename}")
            continue

        current_plate = subpool.plate

        platform = {
            "A00850": models.Platform.objects.get(display_name="Novaseq 6000"),
            "VH00582": models.Platform.objects.get(display_name="Nextseq 2000"),
            "minion": models.Platform.objects.get(name="minion"),
            "promethion": models.Platform.objects.get(name="promethion"),
        }[sequencer]

        subpool_status = normalize_subpool_submission_status(submittable_subpools.get(subpool.name))

        sequencing_run = get_or_create_sequencing_run(sequencing_run_name, run_date, platform, current_plate, accessions=None)
        subpool_run = get_or_create_subpool_in_run(subpool=subpool, sequencing_run=sequencing_run, status=subpool_status)

        for accession_prefix in ["igvftst", "igvf"]:
            file_set_name = None
            submitted_md5s = submitted_sheets[accession_prefix]["sequence_file"].set_index("md5sum")
            if row.md5sum in submitted_md5s.index:
                file_set_alias = submitted_md5s.loc[row.md5sum]["file_set"]
                file_set_name = file_set_alias.split(":")[1]

        if file_set_name is None:
            pass
        elif file_set_name not in measurement_sets:
            # skip if there hasn't been a submitted measurement_set
            pass
        elif subpool_run.measurement_set is None:
            subpool_run.measurement_set = measurement_sets[file_set_name]
            subpool_run.save()
            print(f"updating {subpool_run} measurement set to {measurement_sets[file_set_name]}")
        else:
            assert subpool_run.measurement_set.name == file_set_name, f"SubpoolInRun measurement_set mismatch {subpool_run.measurement_set.name} {file_set_name}"


        subpool_file = models.SubpoolInRunFile(
            sequencing_run=sequencing_run,
            subpool_run=subpool_run,
            md5sum=md5sum,
            filename=str(fastq_relative),
            flowcell_id=row["flowcell_id"],
        )
        if not pandas.isnull(row["lane"]):
            subpool_file.lane = lane_or_none(row["lane"])
        if not pandas.isnull(row["read"]):
            subpool_file.read = row["read"]
        subpool_file.save()

        for accession_info in submitted_sequence_file.get(str(fastq_relative), []):
            if pandas.notnull(accession_info["name"]):
                accession = models.Accession(
                    accession_prefix=accession_info["accession_prefix"],
                    name=accession_info["name"],
                    uuid=accession_info["uuid"],
                    see_also=accession_info["see_also"],
                )
                accession.save()                
                subpool_file.accession.add(accession)
                subpool_file.save()

load_fastqs(submittable_subpools)

print("total plates", models.SplitSeqPlate.objects.count())
print("total sequencing runs", models.SequencingRun.objects.count())
print("total subpools", models.Subpool.objects.count())
print("total subpool in run", models.SubpoolInRun.objects.count())
print("total subpool in run files", models.SubpoolInRunFile.objects.count())

loaded 173 measurement_sets
Nothing found for {'plate__name': 'IGVF_003', 'name': '003_13A', 'index': '1', 'nuclei': 13000, 'selection_type': 'EX'} igvf_003/nextseq2/003_13A_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_003', 'name': '003_13A', 'index': '1', 'nuclei': 13000, 'selection_type': 'EX'} igvf_003/nextseq2/003_13A_R2.fastq.gz
Unable to import {row.filename}
updating 003_67A igvf_003/nextseq measurement set to 003_67A_illumina
updating 003_67B igvf_003/nextseq measurement set to 003_67B_illumina
updating 003_67I igvf_003/nova1 measurement set to 003_67I_illumina
updating 003_67I igvf_003/nova2 measurement set to 003_67I_illumina
updating 003_67J igvf_003/nova1 measurement set to 003_67J_illumina
updating 003_67J igvf_003/nova2 measurement set to 003_67J_illumina
updating 003_67K igvf_003/nova1 measurement set to 003_67K_illumina
updating 003_67K igvf_003/nova2 measurement set to 003_67K_illumina
updating 003_67L igvf_003/nova1 measurement set to 003_67L_illumina
updating 003_67L igvf_003/nova2 measurement set to 003_67L_illumina
updating 003_67M igvf_003/nova1 measurement set to 003_67M_illumina
updating 003_67M igvf_003/nova2 measurement set to 003_67M_illumina
updating 003_67N igvf_003/nova1 measurement set to 003_67N_illumina
updating 003_67N igvf_003/nova2 measurement set to 003_67N_illumina
updating 003_67O igvf_003/nova1 measurement set to 003_67O_illumina
updating 003_67O igvf_003/nova2 measurement set to 003_67O_illumina
updating 003_67A igvf_003/nova1 measurement set to 003_67A_illumina
updating 003_67A igvf_003/nova2 measurement set to 003_67A_illumina
updating 003_67B igvf_003/nova1 measurement set to 003_67B_illumina
updating 003_67B igvf_003/nova2 measurement set to 003_67B_illumina
updating 003_67C igvf_003/nova1 measurement set to 003_67C_illumina
updating 003_67C igvf_003/nova2 measurement set to 003_67C_illumina
updating 003_67D igvf_003/nova1 measurement set to 003_67D_illumina
updating 003_67D igvf_003/nova2 measurement set to 003_67D_illumina
updating 003_67E igvf_003/nova1 measurement set to 003_67E_illumina
updating 003_67E igvf_003/nova2 measurement set to 003_67E_illumina
updating 003_67F igvf_003/nova1 measurement set to 003_67F_illumina
updating 003_67F igvf_003/nova2 measurement set to 003_67F_illumina
updating 003_67G igvf_003/nova1 measurement set to 003_67G_illumina
updating 003_67G igvf_003/nova2 measurement set to 003_67G_illumina
updating 003_67H igvf_003/nova1 measurement set to 003_67H_illumina
updating 003_67H igvf_003/nova2 measurement set to 003_67H_illumina
Nothing found for {'plate__name': 'IGVF_004', 'name': '004_13A', 'index': '2', 'nuclei': 13000, 'selection_type': 'EX'} igvf_004/nextseq2/004_13A_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_004', 'name': '004_13A', 'index': '2', 'nuclei': 13000, 'selection_type': 'EX'} igvf_004/nextseq2/004_13A_R2.fastq.gz
Unable to import {row.filename}
updating 004_67A igvf_004/nextseq measurement set to 004_67A_illumina
updating 004_67B igvf_004/nextseq measurement set to 004_67B_illumina
updating 004_67I igvf_004/nova1 measurement set to 004_67I_illumina
updating 004_67I igvf_004/nova2 measurement set to 004_67I_illumina
updating 004_67J igvf_004/nova1 measurement set to 004_67J_illumina
updating 004_67J igvf_004/nova2 measurement set to 004_67J_illumina
updating 004_67K igvf_004/nova1 measurement set to 004_67K_illumina
updating 004_67K igvf_004/nova2 measurement set to 004_67K_illumina
updating 004_67L igvf_004/nova1 measurement set to 004_67L_illumina
updating 004_67L igvf_004/nova2 measurement set to 004_67L_illumina
updating 004_67M igvf_004/nova1 measurement set to 004_67M_illumina
updating 004_67M igvf_004/nova2 measurement set to 004_67M_illumina
updating 004_67N igvf_004/nova1 measurement set to 004_67N_illumina
updating 004_67N igvf_004/nova2 measurement set to 004_67N_illumina
updating 004_67O igvf_004/nova1 measurement set to 004_67O_illumina
updating 004_67O igvf_004/nova2 measurement set to 004_67O_illumina
updating 004_67A igvf_004/nova1 measurement set to 004_67A_illumina
updating 004_67A igvf_004/nova2 measurement set to 004_67A_illumina
updating 004_67B igvf_004/nova1 measurement set to 004_67B_illumina
updating 004_67B igvf_004/nova2 measurement set to 004_67B_illumina
updating 004_67C igvf_004/nova1 measurement set to 004_67C_illumina
updating 004_67C igvf_004/nova2 measurement set to 004_67C_illumina
updating 004_67D igvf_004/nova1 measurement set to 004_67D_illumina
updating 004_67D igvf_004/nova2 measurement set to 004_67D_illumina
updating 004_67E igvf_004/nova1 measurement set to 004_67E_illumina
updating 004_67E igvf_004/nova2 measurement set to 004_67E_illumina
updating 004_67F igvf_004/nova1 measurement set to 004_67F_illumina
updating 004_67F igvf_004/nova2 measurement set to 004_67F_illumina
updating 004_67G igvf_004/nova1 measurement set to 004_67G_illumina
updating 004_67G igvf_004/nova2 measurement set to 004_67G_illumina
updating 004_67H igvf_004/nova1 measurement set to 004_67H_illumina
updating 004_67H igvf_004/nova2 measurement set to 004_67H_illumina
Nothing found for {'plate__name': 'IGVF_005', 'name': '005_13A', 'index': '3', 'nuclei': 13000, 'selection_type': 'EX'} igvf_005/nextseq2/005_13A_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_005', 'name': '005_13A', 'index': '3', 'nuclei': 13000, 'selection_type': 'EX'} igvf_005/nextseq2/005_13A_R2.fastq.gz
Unable to import {row.filename}
updating 005_67I igvf_005/nova1 measurement set to 005_67I_illumina
updating 005_67I igvf_005/nova2 measurement set to 005_67I_illumina
updating 005_67J igvf_005/nova1 measurement set to 005_67J_illumina
updating 005_67J igvf_005/nova2 measurement set to 005_67J_illumina
updating 005_67K igvf_005/nova1 measurement set to 005_67K_illumina
updating 005_67K igvf_005/nova2 measurement set to 005_67K_illumina
updating 005_67L igvf_005/nova1 measurement set to 005_67L_illumina
updating 005_67L igvf_005/nova2 measurement set to 005_67L_illumina
updating 005_67M igvf_005/nova1 measurement set to 005_67M_illumina
updating 005_67M igvf_005/nova2 measurement set to 005_67M_illumina
updating 005_67N igvf_005/nova1 measurement set to 005_67N_illumina
updating 005_67N igvf_005/nova2 measurement set to 005_67N_illumina
updating 005_67O igvf_005/nova1 measurement set to 005_67O_illumina
updating 005_67O igvf_005/nova2 measurement set to 005_67O_illumina
updating 005_67A igvf_005/nova1 measurement set to 005_67A_illumina
updating 005_67A igvf_005/nova2 measurement set to 005_67A_illumina
updating 005_67B igvf_005/nova1 measurement set to 005_67B_illumina
updating 005_67B igvf_005/nova2 measurement set to 005_67B_illumina
updating 005_67C igvf_005/nova1 measurement set to 005_67C_illumina
updating 005_67C igvf_005/nova2 measurement set to 005_67C_illumina
updating 005_67D igvf_005/nova1 measurement set to 005_67D_illumina
updating 005_67D igvf_005/nova2 measurement set to 005_67D_illumina
updating 005_67E igvf_005/nova1 measurement set to 005_67E_illumina
updating 005_67E igvf_005/nova2 measurement set to 005_67E_illumina
updating 005_67F igvf_005/nova1 measurement set to 005_67F_illumina
updating 005_67F igvf_005/nova2 measurement set to 005_67F_illumina
updating 005_67G igvf_005/nova1 measurement set to 005_67G_illumina
updating 005_67G igvf_005/nova2 measurement set to 005_67G_illumina
updating 005_67H igvf_005/nova1 measurement set to 005_67H_illumina
updating 005_67H igvf_005/nova2 measurement set to 005_67H_illumina
Nothing found for {'plate__name': 'IGVF_007', 'name': '007_13A', 'index': '4', 'nuclei': 13000, 'selection_type': 'EX'} igvf_007/nextseq2/007_13A_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_007', 'name': '007_13A', 'index': '4', 'nuclei': 13000, 'selection_type': 'EX'} igvf_007/nextseq2/007_13A_R2.fastq.gz
Unable to import {row.filename}
updating 007_67I igvf_007/nova1 measurement set to 007_67I_illumina
updating 007_67I igvf_007/nova2 measurement set to 007_67I_illumina
updating 007_67J igvf_007/nova1 measurement set to 007_67J_illumina

updating 007_67J igvf_007/nova2 measurement set to 007_67J_illumina
updating 007_67K igvf_007/nova1 measurement set to 007_67K_illumina
updating 007_67K igvf_007/nova2 measurement set to 007_67K_illumina
updating 007_67L igvf_007/nova1 measurement set to 007_67L_illumina
updating 007_67L igvf_007/nova2 measurement set to 007_67L_illumina
updating 007_67M igvf_007/nova1 measurement set to 007_67M_illumina
updating 007_67M igvf_007/nova2 measurement set to 007_67M_illumina
updating 007_67N igvf_007/nova1 measurement set to 007_67N_illumina
updating 007_67N igvf_007/nova2 measurement set to 007_67N_illumina
updating 007_67O igvf_007/nova1 measurement set to 007_67O_illumina
updating 007_67O igvf_007/nova2 measurement set to 007_67O_illumina
updating 007_67A igvf_007/nova1 measurement set to 007_67A_illumina
updating 007_67A igvf_007/nova2 measurement set to 007_67A_illumina
updating 007_67B igvf_007/nova1 measurement set to 007_67B_illumina
updating 007_67B igvf_007/nova2 measurement set to 007_67B_illumina
updating 007_67C igvf_007/nova1 measurement set to 007_67C_illumina
updating 007_67C igvf_007/nova2 measurement set to 007_67C_illumina
updating 007_67D igvf_007/nova1 measurement set to 007_67D_illumina
updating 007_67D igvf_007/nova2 measurement set to 007_67D_illumina
updating 007_67E igvf_007/nova1 measurement set to 007_67E_illumina
updating 007_67E igvf_007/nova2 measurement set to 007_67E_illumina
updating 007_67F igvf_007/nova1 measurement set to 007_67F_illumina
updating 007_67F igvf_007/nova2 measurement set to 007_67F_illumina
updating 007_67G igvf_007/nova1 measurement set to 007_67G_illumina
updating 007_67G igvf_007/nova2 measurement set to 007_67G_illumina
updating 007_67H igvf_007/nova1 measurement set to 007_67H_illumina
updating 007_67H igvf_007/nova2 measurement set to 007_67H_illumina
updating 008_67C igvf_008/nextseq measurement set to 008_67C_illumina
updating 008_67G igvf_008/nextseq measurement set to 008_67G_illumina
updating 008_67I igvf_008/nova1 measurement set to 008_67I_illumina
updating 008_67A igvf_008/nova1 measurement set to 008_67A_illumina
updating 008_67B igvf_008/nova1 measurement set to 008_67B_illumina
updating 008_67C igvf_008/nova1 measurement set to 008_67C_illumina
updating 008_67D igvf_008/nova1 measurement set to 008_67D_illumina
updating 008_67E igvf_008/nova1 measurement set to 008_67E_illumina
updating 008_67F igvf_008/nova1 measurement set to 008_67F_illumina
updating 008_67G igvf_008/nova1 measurement set to 008_67G_illumina
updating 008_67H igvf_008/nova1 measurement set to 008_67H_illumina
Nothing found for {'plate__name': 'IGVF_008B', 'name': '008B_13A', 'index': '5', 'nuclei': 13000, 'selection_type': 'EX'} igvf_008b/nextseq2/008B_13A_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_008B', 'name': '008B_13A', 'index': '5', 'nuclei': 13000, 'selection_type': 'EX'} igvf_008b/nextseq2/008B_13A_R2.fastq.gz
Unable to import {row.filename}
updating 008B_67G igvf_008b/nextseq measurement set to 008B_67G_illumina
updating 008B_67I igvf_008b/nextseq measurement set to 008B_67I_illumina
updating 008B_67I igvf_008b/nova1 measurement set to 008B_67I_illumina
updating 008B_67J igvf_008b/nova1 measurement set to 008B_67J_illumina
updating 008B_67A igvf_008b/nova1 measurement set to 008B_67A_illumina
updating 008B_67B igvf_008b/nova1 measurement set to 008B_67B_illumina
updating 008B_67C igvf_008b/nova1 measurement set to 008B_67C_illumina
updating 008B_67D igvf_008b/nova1 measurement set to 008B_67D_illumina
updating 008B_67E igvf_008b/nova1 measurement set to 008B_67E_illumina
updating 008B_67F igvf_008b/nova1 measurement set to 008B_67F_illumina
updating 008B_67G igvf_008b/nova1 measurement set to 008B_67G_illumina
updating 008B_67H igvf_008b/nova1 measurement set to 008B_67H_illumina
Nothing found for {'plate__name': 'IGVF_009', 'name': '009_13A', 'index': '6', 'nuclei': 13000, 'selection_type': 'EX'} igvf_009/nextseq2/009_13A_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_009', 'name': '009_13A', 'index': '6', 'nuclei': 13000, 'selection_type': 'EX'} igvf_009/nextseq2/009_13A_R2.fastq.gz
Unable to import {row.filename}
updating 009_67A igvf_009/nextseq measurement set to 009_67A_illumina
updating 009_67O igvf_009/nextseq measurement set to 009_67O_illumina
updating 009_67I igvf_009/nova1 measurement set to 009_67I_illumina
updating 009_67I igvf_009/nova2 measurement set to 009_67I_illumina
updating 009_67J igvf_009/nova1 measurement set to 009_67J_illumina
updating 009_67J igvf_009/nova2 measurement set to 009_67J_illumina
updating 009_67K igvf_009/nova1 measurement set to 009_67K_illumina
updating 009_67K igvf_009/nova2 measurement set to 009_67K_illumina
updating 009_67L igvf_009/nova1 measurement set to 009_67L_illumina
updating 009_67L igvf_009/nova2 measurement set to 009_67L_illumina
updating 009_67M igvf_009/nova1 measurement set to 009_67M_illumina
updating 009_67M igvf_009/nova2 measurement set to 009_67M_illumina
updating 009_67N igvf_009/nova1 measurement set to 009_67N_illumina
updating 009_67N igvf_009/nova2 measurement set to 009_67N_illumina
updating 009_67O igvf_009/nova1 measurement set to 009_67O_illumina
updating 009_67O igvf_009/nova2 measurement set to 009_67O_illumina
updating 009_67A igvf_009/nova1 measurement set to 009_67A_illumina
updating 009_67A igvf_009/nova2 measurement set to 009_67A_illumina
updating 009_67B igvf_009/nova1 measurement set to 009_67B_illumina
updating 009_67B igvf_009/nova2 measurement set to 009_67B_illumina
updating 009_67C igvf_009/nova1 measurement set to 009_67C_illumina
updating 009_67C igvf_009/nova2 measurement set to 009_67C_illumina
updating 009_67D igvf_009/nova1 measurement set to 009_67D_illumina
updating 009_67D igvf_009/nova2 measurement set to 009_67D_illumina
updating 009_67E igvf_009/nova1 measurement set to 009_67E_illumina
updating 009_67E igvf_009/nova2 measurement set to 009_67E_illumina
updating 009_67F igvf_009/nova1 measurement set to 009_67F_illumina
updating 009_67F igvf_009/nova2 measurement set to 009_67F_illumina
updating 009_67G igvf_009/nova1 measurement set to 009_67G_illumina
updating 009_67G igvf_009/nova2 measurement set to 009_67G_illumina
updating 009_67H igvf_009/nova1 measurement set to 009_67H_illumina
updating 009_67H igvf_009/nova2 measurement set to 009_67H_illumina
Nothing found for {'plate__name': 'IGVF_010', 'name': '010_13A', 'index': '7', 'nuclei': 13000, 'selection_type': 'EX'} igvf_010/nextseq2/010_13A_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_010', 'name': '010_13A', 'index': '7', 'nuclei': 13000, 'selection_type': 'EX'} igvf_010/nextseq2/010_13A_R2.fastq.gz
Unable to import {row.filename}
updating 010_67D igvf_010/nextseq measurement set to 010_67D_illumina
updating 010_67O igvf_010/nextseq measurement set to 010_67O_illumina
updating 010_67I igvf_010/nova1 measurement set to 010_67I_illumina
updating 010_67I igvf_010/nova2 measurement set to 010_67I_illumina
updating 010_67J igvf_010/nova1 measurement set to 010_67J_illumina
updating 010_67J igvf_010/nova2 measurement set to 010_67J_illumina
updating 010_67K igvf_010/nova1 measurement set to 010_67K_illumina
updating 010_67K igvf_010/nova2 measurement set to 010_67K_illumina
updating 010_67L igvf_010/nova1 measurement set to 010_67L_illumina
updating 010_67L igvf_010/nova2 measurement set to 010_67L_illumina
updating 010_67M igvf_010/nova1 measurement set to 010_67M_illumina
updating 010_67M igvf_010/nova2 measurement set to 010_67M_illumina
updating 010_67N igvf_010/nova1 measurement set to 010_67N_illumina
updating 010_67N igvf_010/nova2 measurement set to 010_67N_illumina
updating 010_67O igvf_010/nova1 measurement set to 010_67O_illumina
updating 010_67O igvf_010/nova2 measurement set to 010_67O_illumina
updating 010_67A igvf_010/nova1 measurement set to 010_67A_illumina
updating 010_67A igvf_010/nova2 measurement set to 010_67A_illumina
updating 010_67B igvf_010/nova1 measurement set to 010_67B_illumina
updating 010_67B igvf_010/nova2 measurement set to 010_67B_illumina

updating 010_67C igvf_010/nova1 measurement set to 010_67C_illumina
updating 010_67C igvf_010/nova2 measurement set to 010_67C_illumina
updating 010_67D igvf_010/nova1 measurement set to 010_67D_illumina
updating 010_67D igvf_010/nova2 measurement set to 010_67D_illumina
updating 010_67E igvf_010/nova1 measurement set to 010_67E_illumina
updating 010_67E igvf_010/nova2 measurement set to 010_67E_illumina
updating 010_67F igvf_010/nova1 measurement set to 010_67F_illumina
updating 010_67F igvf_010/nova2 measurement set to 010_67F_illumina
updating 010_67G igvf_010/nova1 measurement set to 010_67G_illumina
updating 010_67G igvf_010/nova2 measurement set to 010_67G_illumina
updating 010_67H igvf_010/nova1 measurement set to 010_67H_illumina
updating 010_67H igvf_010/nova2 measurement set to 010_67H_illumina
Nothing found for {'plate__name': 'IGVF_011', 'name': '011_13A', 'index': '8', 'nuclei': 13000, 'selection_type': 'EX'} igvf_011/nextseq2/011_13A_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_011', 'name': '011_13A', 'index': '8', 'nuclei': 13000, 'selection_type': 'EX'} igvf_011/nextseq2/011_13A_R2.fastq.gz
Unable to import {row.filename}
updating 011_67M igvf_011/nextseq measurement set to 011_67M_illumina
updating 011_67O igvf_011/nextseq measurement set to 011_67O_illumina
updating 011_67I igvf_011/nova1 measurement set to 011_67I_illumina
updating 011_67I igvf_011/nova2 measurement set to 011_67I_illumina
updating 011_67J igvf_011/nova1 measurement set to 011_67J_illumina
updating 011_67J igvf_011/nova2 measurement set to 011_67J_illumina
updating 011_67K igvf_011/nova1 measurement set to 011_67K_illumina
updating 011_67K igvf_011/nova2 measurement set to 011_67K_illumina
updating 011_67L igvf_011/nova1 measurement set to 011_67L_illumina
updating 011_67L igvf_011/nova2 measurement set to 011_67L_illumina
updating 011_67M igvf_011/nova1 measurement set to 011_67M_illumina
updating 011_67M igvf_011/nova2 measurement set to 011_67M_illumina
updating 011_67N igvf_011/nova1 measurement set to 011_67N_illumina
updating 011_67N igvf_011/nova2 measurement set to 011_67N_illumina
updating 011_67O igvf_011/nova1 measurement set to 011_67O_illumina
updating 011_67O igvf_011/nova2 measurement set to 011_67O_illumina
updating 011_67A igvf_011/nova1 measurement set to 011_67A_illumina
updating 011_67A igvf_011/nova2 measurement set to 011_67A_illumina
updating 011_67B igvf_011/nova1 measurement set to 011_67B_illumina
updating 011_67B igvf_011/nova2 measurement set to 011_67B_illumina
updating 011_67C igvf_011/nova1 measurement set to 011_67C_illumina
updating 011_67C igvf_011/nova2 measurement set to 011_67C_illumina
updating 011_67D igvf_011/nova1 measurement set to 011_67D_illumina
updating 011_67D igvf_011/nova2 measurement set to 011_67D_illumina
updating 011_67E igvf_011/nova1 measurement set to 011_67E_illumina
updating 011_67E igvf_011/nova2 measurement set to 011_67E_illumina
updating 011_67F igvf_011/nova1 measurement set to 011_67F_illumina
updating 011_67F igvf_011/nova2 measurement set to 011_67F_illumina
updating 011_67G igvf_011/nova1 measurement set to 011_67G_illumina
updating 011_67G igvf_011/nova2 measurement set to 011_67G_illumina
updating 011_67H igvf_011/nova1 measurement set to 011_67H_illumina
updating 011_67H igvf_011/nova2 measurement set to 011_67H_illumina
updating 012_13A igvf_012/nextseq measurement set to 012_13A_illumina
updating 012_13B igvf_012/nextseq measurement set to 012_13B_illumina
updating 012_13C igvf_012/nextseq measurement set to 012_13C_illumina
updating 012_13D igvf_012/nextseq measurement set to 012_13D_illumina
updating 012_13E igvf_012/nextseq measurement set to 012_13E_illumina
updating 012_13F igvf_012/nextseq measurement set to 012_13F_illumina
updating 012_13G igvf_012/nextseq measurement set to 012_13G_illumina
updating 012_13H igvf_012/nextseq measurement set to 012_13H_illumina
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_13A', 'index': 'UDI01', 'nuclei': 13000} igvf_013/nextseq/013_13A_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_13A', 'index': 'UDI01', 'nuclei': 13000} igvf_013/nextseq/013_13A_R2.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67A', 'index': 'UDI02', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_2_S1_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L001_I2_001.fastq.gz
Unable to import {row.filename}

Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67B', 'index': 'UDI03', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_3_S2_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67C', 'index': 'UDI04', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_4_S3_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L003_I1_001.fastq.gz
Unable to import {row.filename}

Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67D', 'index': 'UDI05', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_5_S4_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67E', 'index': 'UDI06', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_6_S5_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67F', 'index': 'UDI07', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_7_S6_L004_R2_001.fastq.gz
Unable to import {row.filename}

Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67G', 'index': 'UDI08', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_8_S7_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_9_S8_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000} igvf_013/nextseq/013_67H_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67H', 'index': 'UDI09', 'nuclei': 67000} igvf_013/nextseq/013_67H_R2.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L002_I1_001.fastq.gz
Unable to import {row.filename}

Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67I', 'index': 'UDI10', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_10_S9_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_11_S10_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000} igvf_013/nextseq/013_67J_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67J', 'index': 'UDI11', 'nuclei': 67000} igvf_013/nextseq/013_67J_R2.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L003_I2_001.fastq.gz
Unable to import {row.filename}

Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67K', 'index': 'UDI12', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_12_S11_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67L', 'index': 'UDI13', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_13_S12_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L001_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67M', 'index': 'UDI14', 'nuclei': 67000, 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_14_S13_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L001_I1_001.fastq.gz
Unable to import {row.filename}

Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L001_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L001_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L001_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L002_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L002_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L002_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L002_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L003_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L003_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L003_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L003_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L004_I1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L004_I2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L004_R1_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_013', 'name': '013_67N', 'index': 'UDI15', 'selection_type': 'NO'} igvf_013/nova1/Sublibrary_15_S14_L004_R2_001.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13A', 'index': 'UDI17', 'nuclei': 13000} igvf_014/nextseq/014_13A_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13A', 'index': 'UDI17', 'nuclei': 13000} igvf_014/nextseq/014_13A_R2.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13B', 'index': 'UDI18', 'nuclei': 13000} igvf_014/nextseq/014_13B_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13B', 'index': 'UDI18', 'nuclei': 13000} igvf_014/nextseq/014_13B_R2.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13C', 'index': 'UDI19', 'nuclei': 13000} igvf_014/nextseq/014_13C_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13C', 'index': 'UDI19', 'nuclei': 13000} igvf_014/nextseq/014_13C_R2.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13D', 'index': 'UDI20', 'nuclei': 13000} igvf_014/nextseq/014_13D_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13D', 'index': 'UDI20', 'nuclei': 13000} igvf_014/nextseq/014_13D_R2.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13E', 'index': 'UDI21', 'nuclei': 13000} igvf_014/nextseq/014_13E_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13E', 'index': 'UDI21', 'nuclei': 13000} igvf_014/nextseq/014_13E_R2.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13F', 'index': 'UDI22', 'nuclei': 13000} igvf_014/nextseq/014_13F_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13F', 'index': 'UDI22', 'nuclei': 13000} igvf_014/nextseq/014_13F_R2.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13G', 'index': 'UDI23', 'nuclei': 13000} igvf_014/nextseq/014_13G_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13G', 'index': 'UDI23', 'nuclei': 13000} igvf_014/nextseq/014_13G_R2.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13H', 'index': 'UDI24'} igvf_014/nextseq/014_13H_R1.fastq.gz
Unable to import {row.filename}
Nothing found for {'plate__name': 'IGVF_014', 'name': '014_13H', 'index': 'UDI24'} igvf_014/nextseq/014_13H_R2.fastq.gz
Unable to import {row.filename}
updating B01_13A igvf_b01/next2 measurement set to B01_13A_illumina
updating B01_13A igvf_b01/next1 measurement set to B01_13A_illumina
updating B01_13B igvf_b01/next2 measurement set to B01_13B_illumina
updating B01_13B igvf_b01/next1 measurement set to B01_13B_illumina
updating B01_13C igvf_b01/next2 measurement set to B01_13C_illumina
updating B01_13C igvf_b01/next1 measurement set to B01_13C_illumina
updating B01_13D igvf_b01/next2 measurement set to B01_13D_illumina
updating B01_13D igvf_b01/next1 measurement set to B01_13D_illumina
updating B01_13E igvf_b01/next2 measurement set to B01_13E_illumina
updating B01_13E igvf_b01/next1 measurement set to B01_13E_illumina
updating B01_13F igvf_b01/next2 measurement set to B01_13F_illumina
updating B01_13F igvf_b01/next1 measurement set to B01_13F_illumina
updating B01_13G igvf_b01/next2 measurement set to B01_13G_illumina
updating B01_13G igvf_b01/next1 measurement set to B01_13G_illumina
updating B01_13H igvf_b01/next2 measurement set to B01_13H_illumina
updating B01_13H igvf_b01/next1 measurement set to B01_13H_illumina
total plates 13
total sequencing runs 27
total subpools 222
total subpool in run 271
total subpool in run files 2857

In [71]:
for q in models.Subpool.objects.filter(plate__name="IGVF_014", index="UDI24"):
    print(q.name, q.index, q.nuclei, q.selection_type)

In [72]:
[(x.name, x.index, x.selection_type) for x in models.Subpool.objects.filter(plate__name="IGVF_013")]

[]

In [73]:
def print_subpool_submission_status(fastqs):
    for i, row in fastqs.iterrows():
        plate_name = normalize_plate_name(row.experiment)
        index_id = row.index_id
        fastq_relative = Path(row.filename)
        sequencing_run_name = str(Path(fastq_relative.parts[0])/fastq_relative.parts[1])
        sequencer = row.get("sequencer")
        run_date = row["ctime"]
        md5sum = row["md5sum"]

        #if row["read_id"] in ('I1',):
        #    continue

        subpool = get_subpool_from_fastq_row(row)
        current_plate = subpool.plate

        platform = {
            "A00850": models.Platform.objects.get(display_name="Novaseq 6000"),
            "VH00582": models.Platform.objects.get(display_name="Nextseq 2000"),
            "minion": models.Platform.objects.get(name="minion"),
            "promethion": models.Platform.objects.get(name="promethion"),
        }[sequencer]

        subpool_status = {
            "Yes": models.RunStatus.PASS,
            "No": models.RunStatus.FAILED,
            None: models.RunStatus.FAILED,
        }[submittable_subpools.get(subpool.name)]

        #sequencing_run = get_or_create_sequencing_run(sequencing_run_name, run_date, platform, current_plate, accessions=None)
        #subpool_run = get_or_create_subpool_in_run(subpool=subpool, sequencing_run=sequencing_run, status=subpool_status)
        print(row.filename, row.index_id, sequencing_run_name, run_date, subpool, subpool_status)

#print_subpool_submission_status(fastqs)

In [74]:
md5counts = Counter(fastqs["md5sum"])
dupmd5s = set()
for md5sum in md5counts:
    if md5counts[md5sum] > 1:
        dupmd5s.add(md5sum)
        
dupfiles = fastqs[fastqs["md5sum"].isin(dupmd5s)].sort_values(["experiment", "md5sum", "filename"])
print(dupfiles.shape)
dupfiles

(0, 20)

Empty DataFrame
Columns: [experiment, family, filename, md5sum, size, ctime, plate_id, subpool_name, fragment, compression, sequencer, sequencer_run, flowcell_id, nuclei, read, barcode, index_id, sample_id, lane, exome_capture]
Index: []

In [75]:
print(dupfiles.to_csv(index=False))

experiment,family,filename,md5sum,size,ctime,plate_id,subpool_name,fragment,compression,sequencer,sequencer_run,flowcell_id,nuclei,read,barcode,index_id,sample_id,lane,exome_capture

In [76]:
models.SexEnum.choices

[('M', 'male'), ('F', 'female'), ('U', 'unknown'), ('O', 'other')]

In [77]:
# In case of interrupted upload

if 0:
    EC = str(Path("~/proj/encoded_client").expanduser())
    if EC not in sys.path:
        sys.path.append(EC)

    from encoded_client.encoded import ENCODED

    server = ENCODED("api.data.igvf.org")

    submitted_tissues = load_submitted_tissues()
    for tissue_id in submitted_tissues:
        for record in submitted_tissues[tissue_id]:
            if pandas.isnull(record["uuid"] ):
                tissue = server.get_json(record["see_also"])
                print("{}\t{}".format(record["name"], tissue["uuid"]))

In [78]:
models.SubpoolInRunFile.objects.get(md5sum="2a5a07155767a2f541cfb20e7d0636e0")

remember to flip the assert back on?