# Introduction

Using the models we have try to fill in the metadata spreadsheet & submit test records to the IGVF test portal.

This try had all the files from each platform type attached to one measurement set. But with Jennifer we decided this is probably a poor idea.

In [1]:
import bz2
from collections import Counter, namedtuple
import datetime
import json
import numpy
import os
import pandas
from pathlib import Path
import re
from subprocess import run, PIPE
from tqdm import tqdm
import sys
import zoneinfo

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mousedemo.settings')
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

import django
from django.contrib.auth import get_user_model
from django.db import DEFAULT_DB_ALIAS

MOUSEDEMO = str(Path("mousedemo").absolute())
if MOUSEDEMO not in sys.path:
    sys.path.append(MOUSEDEMO)

django.setup()

from mousedemo import settings
from igvf_mice import models

In [2]:
EC = str(Path("~/proj/encoded_client").expanduser())
if EC not in sys.path:
    sys.path.append(EC)
    
from encoded_client import encoded

In [3]:
#server_name = "api.sandbox.igvf.org"
#accession_prefix = "igvftst"
#upload_target = "sandbox"
server_name = "api.data.igvf.org"
accession_prefix = "igvf"
upload_target = "production"

#server_name = "igvfd-test-igvf-532-sandbox-db.demo.igvf.org"
assert "/" not in server_name
assert ".." not in server_name

server = encoded.ENCODED(server_name)

validator = encoded.DCCValidator(server)

In [4]:
award = "/awards/HG012077/"
labs = ["/labs/lior-pachter/", "/labs/grant-macgregor/", "/labs/barbara-wold/", "/labs/ali-mortazavi/"]
lab = labs[-1]
jax = "/sources/jackson-labs/"
species = 'Mus musculus'

In [5]:
def str_or_none(x):
    if pandas.isnull(x):
        return None
    elif len(x) == 0:
        return None
    else:
        return x
    
assert str_or_none("") is None

In [6]:
test_run_name =  "IGVF_014"
plate = models.SplitSeqPlate.objects.get(name=test_run_name)
plate

In [7]:
tissues = {}
mice = {}
for well in plate.splitseqwell_set.all():
    for biosample in well.biosample.all():
        for tissue in biosample.extraction.tissue.all():
            tissues[tissue.name] = tissue
            mice[tissue.mouse.name] = tissue.mouse

# rodent_donor

In [23]:
def format_sex(value):
    if models.SexEnum.MALE == value:
        return "male"
    elif models.SexEnum.FEMALE == value:
        return "female"

def get_accession_string_or_none(record, accession_prefix):
    accessions = record.accession.filter(accession_prefix=accession_prefix)
    if len(accessions) == 0:
        return None
    elif len(accessions) == 1:
        return accessions[0].name
    else:
        raise ValueError("There should only be one accession per namespace {}".format(accessions))
        
def convert_strain_background(name):
    if name == 'NZO/HlLtJ (NZO)':
        return 'NZO/H1LtJ (NZO)'
    else:
        return name
    
rodent_donor = []
for mouse_name in sorted(mice):
    mouse = mice[mouse_name]
    dcc_row = {
        #"#response": None,
        #"#response_time": None,
        "accession": get_accession_string_or_none(mouse, accession_prefix),
        "uuid": None, 
        "aliases:array": f"ali-mortazavi:{mouse.name}",
        "award": award,
        "lab": lab,
        "taxa": species,
        "sex": format_sex(mouse.sex),
        "strain": mouse.strain.name,
        "references": None,
        "url": mouse.strain.see_also if pandas.notnull(mouse.strain.see_also) else None,
        "sources:array": jax,
        "lot_id": None,
        "product_id": str_or_none(mouse.strain.jax_catalog_number),
        "documents": None,
        "alternate_accessions": None,
        "submitter_comment": None,
        "description": None,
        "parents": None,
        "traits": None,
        "phenotypic_features": None,
        "external_resources": None,
        "strain_background": convert_strain_background(mouse.strain.igvf_id),
        "genotype": None,
        "individual_rodent:boolean": True,
        "rodent_identifier": mouse.name,
    }
    rodent_donor.append(dcc_row)
    
rodent_donor = pandas.DataFrame(rodent_donor)

dry_run = True

created = server.post_sheet("rodent_donor", rodent_donor, dry_run=dry_run, verbose=True, validator=validator)
print(len(created))
#if len(created) > 0 and not dry_run:
#    rodent_donor.to_excel("rodent_donor.{}.xlsx".format(server_name))
rodent_donor

Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:170_B6NODF1J_10F'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'taxa': 'Mus musculus', 'sex': 'female', 'strain': 'B6NODF1J', 'sources': ['/sources/jackson-labs/'], 'product_id': 'Custom C56BL/6J crossed NOD/ShiLtJ', 'individual_rodent': True, 'rodent_identifier': '170_B6NODF1J_10F', 'accession': 'IGVFDO4255NQNV', 'status': 'in progress', 'schema_version': '10', 'creation_timestamp': '2023-10-26T18:36:33.092311+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/rodent-donors/IGVFDO4255NQNV/', '@type': ['RodentDonor', 'Donor', 'Item'], 'uuid': 'dc5134c6-b2e2-444c-89b4-c896005762b4', 'summary': 'IGVFDO4255NQNV'}]}
row 0 created: IGVFDO4255NQNV
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:198_B6CASTF1J_10F'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'taxa': 'Mus musculus', 'sex': 'female', 'strain': 'B6CASTF1J', 'sources': ['/sources/jackson-labs/'], 'product_id': 'Custom C56BL/6J crossed CAST/EiJ', 'individual_rodent': True, 'rodent_identifier': '198_B6CASTF1J_10F', 'accession': 'IGVFDO7584QEOX', 'status': 'in progress', 'schema_version': '10', 'creation_timestamp': '2023-10-26T18:36:33.474296+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/rodent-donors/IGVFDO7584QEOX/', '@type': ['RodentDonor', 'Donor', 'Item'], 'uuid': '25a9c85e-7ee1-4b71-b3b4-31003d1cd09a', 'summary': 'IGVFDO7584QEOX'}]}
row 1 created: IGVFDO7584QEOX
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:206_B6CASTF1J_10F'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'taxa': 'Mus musculus', 'sex': 'female', 'strain': 'B6CASTF1J', 'sources': ['/sources/jackson-labs/'], 'product_id': 'Custom C56BL/6J crossed CAST/EiJ', 'individual_rodent': True, 'rodent_identifier': '206_B6CASTF1J_10F', 'accession': 'IGVFDO9239QBJY', 'status': 'in progress', 'schema_version': '10', 'creation_timestamp': '2023-10-26T18:36:33.834056+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/rodent-donors/IGVFDO9239QBJY/', '@type': ['RodentDonor', 'Donor', 'Item'], 'uuid': '1855e0b9-0b5e-4cdc-b577-2f72860d18f2', 'summary': 'IGVFDO9239QBJY'}]}
row 2 created: IGVFDO9239QBJY
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:208_B6PWKF1J_10F'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'taxa': 'Mus musculus', 'sex': 'female', 'strain': 'B6PWKF1J', 'sources': ['/sources/jackson-labs/'], 'product_id': 'Custom C56BL/6J crossed PWK/PhJ', 'individual_rodent': True, 'rodent_identifier': '208_B6PWKF1J_10F', 'accession': 'IGVFDO0654QHHA', 'status': 'in progress', 'schema_version': '10', 'creation_timestamp': '2023-10-26T18:36:34.196349+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/rodent-donors/IGVFDO0654QHHA/', '@type': ['RodentDonor', 'Donor', 'Item'], 'uuid': 'aff36034-84bf-4c01-b299-c8d51f2bed9c', 'summary': 'IGVFDO0654QHHA'}]}
row 3 created: IGVFDO0654QHHA
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:228_B6WSBF1J_10F'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'taxa': 'Mus musculus', 'sex': 'female', 'strain': 'B6WSBF1J', 'url': 'https://www.jax.org/strain/019019', 'sources': ['/sources/jackson-labs/'], 'product_id': '019019', 'individual_rodent': True, 'rodent_identifier': '228_B6WSBF1J_10F', 'accession': 'IGVFDO5216CAMJ', 'status': 'in progress', 'schema_version': '10', 'creation_timestamp': '2023-10-26T18:36:34.417244+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/rodent-donors/IGVFDO5216CAMJ/', '@type': ['RodentDonor', 'Donor', 'Item'], 'uuid': '1653b26f-4529-46cf-96d1-874a1b7280f7', 'summary': 'IGVFDO5216CAMJ'}]}
row 4 created: IGVFDO5216CAMJ
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:255_B6J_10M'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'taxa': 'Mus musculus', 'sex': 'male', 'strain': 'B6J', 'url': 'https://www.jax.org/strain/000664', 'sources': ['/sources/jackson-labs/'], 'product_id': '000664', 'strain_background': 'C57BL/6J (B6)', 'individual_rodent': True, 'rodent_identifier': '255_B6J_10M', 'accession': 'IGVFDO6294BKKV', 'status': 'in progress', 'schema_version': '10', 'creation_timestamp': '2023-10-26T18:36:34.832078+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/rodent-donors/IGVFDO6294BKKV/', '@type': ['RodentDonor', 'Donor', 'Item'], 'uuid': '3afa45fc-86cc-4a84-804c-7c8e35078252', 'summary': 'IGVFDO6294BKKV'}]}
row 5 created: IGVFDO6294BKKV
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:256_B6J_10F'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'taxa': 'Mus musculus', 'sex': 'female', 'strain': 'B6J', 'url': 'https://www.jax.org/strain/000664', 'sources': ['/sources/jackson-labs/'], 'product_id': '000664', 'strain_background': 'C57BL/6J (B6)', 'individual_rodent': True, 'rodent_identifier': '256_B6J_10F', 'accession': 'IGVFDO4258RYAV', 'status': 'in progress', 'schema_version': '10', 'creation_timestamp': '2023-10-26T18:36:35.169763+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/rodent-donors/IGVFDO4258RYAV/', '@type': ['RodentDonor', 'Donor', 'Item'], 'uuid': 'd5b29064-c8c3-43a4-8c51-3fa5909e3e60', 'summary': 'IGVFDO4258RYAV'}]}
row 6 created: IGVFDO4258RYAV
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:257_B6J_10M'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'taxa': 'Mus musculus', 'sex': 'male', 'strain': 'B6J', 'url': 'https://www.jax.org/strain/000664', 'sources': ['/sources/jackson-labs/'], 'product_id': '000664', 'strain_background': 'C57BL/6J (B6)', 'individual_rodent': True, 'rodent_identifier': '257_B6J_10M', 'accession': 'IGVFDO5893GZJR', 'status': 'in progress', 'schema_version': '10', 'creation_timestamp': '2023-10-26T18:36:35.388356+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/rodent-donors/IGVFDO5893GZJR/', '@type': ['RodentDonor', 'Donor', 'Item'], 'uuid': '2138676f-45b3-4fdd-b351-fac83c45caa6', 'summary': 'IGVFDO5893GZJR'}]}
row 7 created: IGVFDO5893GZJR
8

,accession,uuid,aliases:array,award,lab,taxa,sex,strain,references,url,...,submitter_comment,description,parents,traits,phenotypic_features,external_resources,strain_background,genotype,individual_rodent:boolean,rodent_identifier
0,IGVFDO4255NQNV,dc5134c6-b2e2-444c-89b4-c896005762b4,ali-mortazavi:170_B6NODF1J_10F,/awards/HG012077/,/labs/ali-mortazavi/,Mus musculus,female,B6NODF1J,None,None,...,None,None,None,None,None,None,None,None,True,170_B6NODF1J_10F
1,IGVFDO7584QEOX,25a9c85e-7ee1-4b71-b3b4-31003d1cd09a,ali-mortazavi:198_B6CASTF1J_10F,/awards/HG012077/,/labs/ali-mortazavi/,Mus musculus,female,B6CASTF1J,None,None,...,None,None,None,None,None,None,None,None,True,198_B6CASTF1J_10F
2,IGVFDO9239QBJY,1855e0b9-0b5e-4cdc-b577-2f72860d18f2,ali-mortazavi:206_B6CASTF1J_10F,/awards/HG012077/,/labs/ali-mortazavi/,Mus musculus,female,B6CASTF1J,None,None,...,None,None,None,None,None,None,None,None,True,206_B6CASTF1J_10F
3,IGVFDO0654QHHA,aff36034-84bf-4c01-b299-c8d51f2bed9c,ali-mortazavi:208_B6PWKF1J_10F,/awards/HG012077/,/labs/ali-mortazavi/,Mus musculus,female,B6PWKF1J,None,None,...,None,None,None,None,None,None,None,None,True,208_B6PWKF1J_10F
4,IGVFDO5216CAMJ,1653b26f-4529-46cf-96d1-874a1b7280f7,ali-mortazavi:228_B6WSBF1J_10F,/awards/HG012077/,/labs/ali-mortazavi/,Mus musculus,female,B6WSBF1J,None,https://www.jax.org/strain/019019,...,None,None,None,None,None,None,None,None,True,228_B6WSBF1J_10F
5,IGVFDO6294BKKV,3afa45fc-86cc-4a84-804c-7c8e35078252,ali-mortazavi:255_B6J_10M,/awards/HG012077/,/labs/ali-mortazavi/,Mus musculus,male,B6J,None,https://www.jax.org/strain/000664,...,None,None,None,None,None,None,C57BL/6J (B6),None,True,255_B6J_10M
6,IGVFDO4258RYAV,d5b29064-c8c3-43a4-8c51-3fa5909e3e60,ali-mortazavi:256_B6J_10F,/awards/HG012077/,/labs/ali-mortazavi/,Mus musculus,female,B6J,None,https://www.jax.org/strain/000664,...,None,None,None,None,None,None,C57BL/6J (B6),None,True,256_B6J_10F
7,IGVFDO5893GZJR,2138676f-45b3-4fdd-b351-fac83c45caa6,ali-mortazavi:257_B6J_10M,/awards/HG012077/,/labs/ali-mortazavi/,Mus musculus,male,B6J,None,https://www.jax.org/strain/000664,...,None,None,None,None,None,None,C57BL/6J (B6),None,True,257_B6J_10M

In [9]:
import re

re.match("^(\\S+(\\s|\\S)*\\S+|\\S)$", "custom b6 female x cast male F1 progeny")

# tissue

In [24]:
def get_accession_list_or_none(record, accession_prefix, length):
    accessions = record.accession.filter(accession_prefix=accession_prefix)
    if len(accessions) == 0:
        return [None] * length
    elif len(accessions) == length:
        return [x.name for x in accessions]
    else:
        raise ValueError("Unexpected number of accessions {} {}".format(accessions, length))

tissue_sheet = []
for tissue_name in tissues:
    tissue = tissues[tissue_name]
    donor_alias = f"ali-mortazavi:{tissue.mouse.name}"
    ontology_terms = tissue.ontology_term.all()
    accessions = get_accession_list_or_none(tissue, accession_prefix, len(ontology_terms))
    for term, accession_id in zip(ontology_terms, accessions):
        curie = term.curie.replace(":", "_")
        alias = f"ali-mortazavi:{tissue.name}_{curie}"
        sample_term = "/sample-terms/{}/".format(curie)
        if numpy.all(pandas.isnull(accession_id)):
            accession_id = None
        dcc_row = {
            "accession": accession_id,
            "uuid": None,
            "aliases:array": alias,
            "award": award,
            "lab": lab,
            "sources:array": jax,
            "donors:array": donor_alias,
            "sample_terms:array": sample_term,
            "term_names:skip": term.name,
        }
        tissue_sheet.append(dcc_row)
    
tissue_sheet = pandas.DataFrame(tissue_sheet)

dry_run = True
created = server.post_sheet("tissue", tissue_sheet, dry_run=dry_run, verbose=True, validator=validator)
print(len(created))
#if len(created) > 0 and not dry_run:
#    tissue_sheet.to_excel("tissue_sheet.{}.xlsx".format(server_name))
tissue_sheet

Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:255_B6J_10M_20_CL_2000001'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'sources': ['/sources/jackson-labs/'], 'donors': ['/rodent-donors/IGVFDO6294BKKV/'], 'sample_terms': ['/sample-terms/CL_2000001/'], 'accession': 'IGVFSM0442UOPQ', 'status': 'in progress', 'schema_version': '15', 'creation_timestamp': '2023-10-26T18:36:47.574837+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/tissues/IGVFSM0442UOPQ/', '@type': ['Tissue', 'Biosample', 'Sample', 'Item'], 'uuid': '43e44458-85d2-4234-bd9d-14c405e7d88d', 'summary': 'peripheral blood mononuclear cell tissue, male, Mus musculus B6J', 'file_sets': [], 'multiplexed_in': [], 'sex': 'male', 'age': 'unknown', 'taxa': 'Mus musculus', 'classification': 'tissue'}]}
row 0 created: IGVFSM0442UOPQ
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:256_B6J_10F_20_CL_2000001'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'sources': ['/sources/jackson-labs/'], 'donors': ['/rodent-donors/IGVFDO4258RYAV/'], 'sample_terms': ['/sample-terms/CL_2000001/'], 'accession': 'IGVFSM0557OIVT', 'status': 'in progress', 'schema_version': '15', 'creation_timestamp': '2023-10-26T18:36:47.811591+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/tissues/IGVFSM0557OIVT/', '@type': ['Tissue', 'Biosample', 'Sample', 'Item'], 'uuid': '9a957c3f-1b24-4ee2-b776-f4b12754e268', 'summary': 'peripheral blood mononuclear cell tissue, female, Mus musculus B6J', 'file_sets': [], 'multiplexed_in': [], 'sex': 'female', 'age': 'unknown', 'taxa': 'Mus musculus', 'classification': 'tissue'}]}
row 1 created: IGVFSM0557OIVT
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:257_B6J_10M_20_CL_2000001'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'sources': ['/sources/jackson-labs/'], 'donors': ['/rodent-donors/IGVFDO5893GZJR/'], 'sample_terms': ['/sample-terms/CL_2000001/'], 'accession': 'IGVFSM8807AADG', 'status': 'in progress', 'schema_version': '15', 'creation_timestamp': '2023-10-26T18:36:48.156937+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/tissues/IGVFSM8807AADG/', '@type': ['Tissue', 'Biosample', 'Sample', 'Item'], 'uuid': '1d5609c0-f9c2-449a-aa76-81ae994ab064', 'summary': 'peripheral blood mononuclear cell tissue, male, Mus musculus B6J', 'file_sets': [], 'multiplexed_in': [], 'sex': 'male', 'age': 'unknown', 'taxa': 'Mus musculus', 'classification': 'tissue'}]}
row 2 created: IGVFSM8807AADG
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:198_B6CASTF1J_10F_20_CL_2000001'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'sources': ['/sources/jackson-labs/'], 'donors': ['/rodent-donors/IGVFDO7584QEOX/'], 'sample_terms': ['/sample-terms/CL_2000001/'], 'accession': 'IGVFSM9622JHKX', 'status': 'in progress', 'schema_version': '15', 'creation_timestamp': '2023-10-26T18:36:48.495746+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/tissues/IGVFSM9622JHKX/', '@type': ['Tissue', 'Biosample', 'Sample', 'Item'], 'uuid': 'ce4c7ad8-e797-401f-8d59-bd43e77d207f', 'summary': 'peripheral blood mononuclear cell tissue, female, Mus musculus B6CASTF1J', 'file_sets': [], 'multiplexed_in': [], 'sex': 'female', 'age': 'unknown', 'taxa': 'Mus musculus', 'classification': 'tissue'}]}
row 3 created: IGVFSM9622JHKX
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:206_B6CASTF1J_10F_20_CL_2000001'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'sources': ['/sources/jackson-labs/'], 'donors': ['/rodent-donors/IGVFDO9239QBJY/'], 'sample_terms': ['/sample-terms/CL_2000001/'], 'accession': 'IGVFSM4826GDRP', 'status': 'in progress', 'schema_version': '15', 'creation_timestamp': '2023-10-26T18:36:48.724999+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/tissues/IGVFSM4826GDRP/', '@type': ['Tissue', 'Biosample', 'Sample', 'Item'], 'uuid': '99067cf2-f250-4d59-a50f-b0c0bd658b9a', 'summary': 'peripheral blood mononuclear cell tissue, female, Mus musculus B6CASTF1J', 'file_sets': [], 'multiplexed_in': [], 'sex': 'female', 'age': 'unknown', 'taxa': 'Mus musculus', 'classification': 'tissue'}]}
row 4 created: IGVFSM4826GDRP
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:208_B6PWKF1J_10F_20_CL_2000001'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'sources': ['/sources/jackson-labs/'], 'donors': ['/rodent-donors/IGVFDO0654QHHA/'], 'sample_terms': ['/sample-terms/CL_2000001/'], 'accession': 'IGVFSM7316AFZJ', 'status': 'in progress', 'schema_version': '15', 'creation_timestamp': '2023-10-26T18:36:48.955420+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/tissues/IGVFSM7316AFZJ/', '@type': ['Tissue', 'Biosample', 'Sample', 'Item'], 'uuid': '3cdfb470-1e9a-44ee-8251-e30867dac9c3', 'summary': 'peripheral blood mononuclear cell tissue, female, Mus musculus B6PWKF1J', 'file_sets': [], 'multiplexed_in': [], 'sex': 'female', 'age': 'unknown', 'taxa': 'Mus musculus', 'classification': 'tissue'}]}
row 5 created: IGVFSM7316AFZJ
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:228_B6WSBF1J_10F_20_CL_2000001'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'sources': ['/sources/jackson-labs/'], 'donors': ['/rodent-donors/IGVFDO5216CAMJ/'], 'sample_terms': ['/sample-terms/CL_2000001/'], 'accession': 'IGVFSM7526UDOL', 'status': 'in progress', 'schema_version': '15', 'creation_timestamp': '2023-10-26T18:36:49.196932+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/tissues/IGVFSM7526UDOL/', '@type': ['Tissue', 'Biosample', 'Sample', 'Item'], 'uuid': 'eae108f6-8358-4831-9019-8fa076433de4', 'summary': 'peripheral blood mononuclear cell tissue, female, Mus musculus B6WSBF1J', 'file_sets': [], 'multiplexed_in': [], 'sex': 'female', 'age': 'unknown', 'taxa': 'Mus musculus', 'classification': 'tissue'}]}
row 6 created: IGVFSM7526UDOL
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:170_B6NODF1J_10F_20_CL_2000001'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'sources': ['/sources/jackson-labs/'], 'donors': ['/rodent-donors/IGVFDO4255NQNV/'], 'sample_terms': ['/sample-terms/CL_2000001/'], 'accession': 'IGVFSM9353XAPN', 'status': 'in progress', 'schema_version': '15', 'creation_timestamp': '2023-10-26T18:36:49.578378+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/tissues/IGVFSM9353XAPN/', '@type': ['Tissue', 'Biosample', 'Sample', 'Item'], 'uuid': '0b1831a9-bad4-47e4-8b87-800eeb40bbfd', 'summary': 'peripheral blood mononuclear cell tissue, female, Mus musculus B6NODF1J', 'file_sets': [], 'multiplexed_in': [], 'sex': 'female', 'age': 'unknown', 'taxa': 'Mus musculus', 'classification': 'tissue'}]}
row 7 created: IGVFSM9353XAPN
8

,accession,uuid,aliases:array,award,lab,sources:array,donors:array,sample_terms:array,term_names:skip
0,IGVFSM0442UOPQ,43e44458-85d2-4234-bd9d-14c405e7d88d,ali-mortazavi:255_B6J_10M_20_CL_2000001,/awards/HG012077/,/labs/ali-mortazavi/,/sources/jackson-labs/,ali-mortazavi:255_B6J_10M,/sample-terms/CL_2000001/,peripheral blood mononuclear cell
1,IGVFSM0557OIVT,9a957c3f-1b24-4ee2-b776-f4b12754e268,ali-mortazavi:256_B6J_10F_20_CL_2000001,/awards/HG012077/,/labs/ali-mortazavi/,/sources/jackson-labs/,ali-mortazavi:256_B6J_10F,/sample-terms/CL_2000001/,peripheral blood mononuclear cell
2,IGVFSM8807AADG,1d5609c0-f9c2-449a-aa76-81ae994ab064,ali-mortazavi:257_B6J_10M_20_CL_2000001,/awards/HG012077/,/labs/ali-mortazavi/,/sources/jackson-labs/,ali-mortazavi:257_B6J_10M,/sample-terms/CL_2000001/,peripheral blood mononuclear cell
3,IGVFSM9622JHKX,ce4c7ad8-e797-401f-8d59-bd43e77d207f,ali-mortazavi:198_B6CASTF1J_10F_20_CL_2000001,/awards/HG012077/,/labs/ali-mortazavi/,/sources/jackson-labs/,ali-mortazavi:198_B6CASTF1J_10F,/sample-terms/CL_2000001/,peripheral blood mononuclear cell
4,IGVFSM4826GDRP,99067cf2-f250-4d59-a50f-b0c0bd658b9a,ali-mortazavi:206_B6CASTF1J_10F_20_CL_2000001,/awards/HG012077/,/labs/ali-mortazavi/,/sources/jackson-labs/,ali-mortazavi:206_B6CASTF1J_10F,/sample-terms/CL_2000001/,peripheral blood mononuclear cell
5,IGVFSM7316AFZJ,3cdfb470-1e9a-44ee-8251-e30867dac9c3,ali-mortazavi:208_B6PWKF1J_10F_20_CL_2000001,/awards/HG012077/,/labs/ali-mortazavi/,/sources/jackson-labs/,ali-mortazavi:208_B6PWKF1J_10F,/sample-terms/CL_2000001/,peripheral blood mononuclear cell
6,IGVFSM7526UDOL,eae108f6-8358-4831-9019-8fa076433de4,ali-mortazavi:228_B6WSBF1J_10F_20_CL_2000001,/awards/HG012077/,/labs/ali-mortazavi/,/sources/jackson-labs/,ali-mortazavi:228_B6WSBF1J_10F,/sample-terms/CL_2000001/,peripheral blood mononuclear cell
7,IGVFSM9353XAPN,0b1831a9-bad4-47e4-8b87-800eeb40bbfd,ali-mortazavi:170_B6NODF1J_10F_20_CL_2000001,/awards/HG012077/,/labs/ali-mortazavi/,/sources/jackson-labs/,ali-mortazavi:170_B6NODF1J_10F,/sample-terms/CL_2000001/,peripheral blood mononuclear cell

# multiplexed_tissue

In [11]:
def get_samples_donors(plate):
    samples = {}
    donors = {}

    for well in plate.splitseqwell_set.all():
        for biosample in well.biosample.all():
            for tissue in biosample.extraction.tissue.all():
                mouse_alias = f"ali-mortazavi:{tissue.mouse.name}"
                # I need an ordered set of donors
                donors[mouse_alias] = tissue.mouse
                for term in tissue.ontology_term.all():
                    curie = term.curie.replace(":", "_")
                    tissue_alias = f"ali-mortazavi:{tissue.name}_{curie}"
                    samples[tissue_alias] = None

    return {
        "samples": list(samples.keys()),
        "donor": list(donors.keys()),
        "source": set([donors[donor_id].source.igvf_id for donor_id in donors],)
    }

In [25]:
def get_subpool_accession(alias, subpool):
    if subpool is None:
        try:
            posted = server.get_json(alias)
            return posted["accession"]
        except encoded.HTTPError as e:
            if e.response.status_code == 404:
                pass
            else:
                print("HTTPError", e)
        return None

    accessions = subpool.accession.filter(accession_prefix=accession_prefix)
    if len(accessions) > 1:
        raise RuntimeError("Too many accessions")
    elif len(accessions) == 1:
        return accessions[0].name

    return None


multiplexed_tissue = []

plate_details = get_samples_donors(plate)
if len(plate_details["source"]) == 0:
    raise ValueError(f"Empty plate details for {plate}")
elif len(plate_details["source"]) > 1:
    raise ValueError("Not sure what do with mixed sources yet. {}".format(plate_details["source"]))

source = next(iter(plate_details["source"]))
multiplexed_sample = []
for subpool in plate.subpool_set.all():
    if subpool.subpoolinrun_set.filter(status="P").count() > 0:
        alias = "ali-mortazavi:subpool_{}".format(subpool.name)
        multiplexed_sample.append({
            "accession": get_subpool_accession(alias, subpool),
            "uuid": None,
            "aliases:array": alias,
            "cellular_sub_pool": subpool.name,
            "award": award,
            "lab": lab,
            "multiplexed_samples:array": ",".join(plate_details["samples"]),
        })
#print(json.dumps(multiplexed_sample, indent=2))
multiplexed_sample = pandas.DataFrame(multiplexed_sample)


dry_run = True
created = server.post_sheet("multiplexed_sample", multiplexed_sample, dry_run=dry_run, verbose=True, validator=validator)
print(len(created))
#if len(created) > 0 and not dry_run:
#    multiplexed_sample.to_excel("multiplexed_sample.{}.xlsx".format(server_name), index=False)
multiplexed_sample

Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:subpool_014_13A'], 'cellular_sub_pool': '014_13A', 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'multiplexed_samples': ['/tissues/IGVFSM0442UOPQ/', '/tissues/IGVFSM0557OIVT/', '/tissues/IGVFSM8807AADG/', '/tissues/IGVFSM9622JHKX/', '/tissues/IGVFSM4826GDRP/', '/tissues/IGVFSM7316AFZJ/', '/tissues/IGVFSM7526UDOL/', '/tissues/IGVFSM9353XAPN/'], 'accession': 'IGVFSM8067OJHZ', 'status': 'in progress', 'schema_version': '4', 'creation_timestamp': '2023-10-26T18:54:21.673263+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/multiplexed-samples/IGVFSM8067OJHZ/', '@type': ['MultiplexedSample', 'Sample', 'Item'], 'uuid': 'b7829abc-32c2-48d7-956e-a085550ebf54', 'summary': 'multiplexed sample of peripheral blood mononuclear cell tissue, female, Mus musculus B6J, peripheral blood mononuclear cell tissue, male, Mus musculus B6J, ... and 6 more samples', 'file_sets': [], 'multiplexed_in': [], 'sample_terms': ['/sample-terms/CL_2000001/'], 'disease_terms': [], 'treatments': [], 'modifications': [], 'donors': ['/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5216CAMJ/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO9239QBJY/'], 'biomarkers': [], 'sources': ['/sources/jackson-labs/'], 'construct_library_sets': [], 'classification': 'multiplexed sample'}]}
row 0 created: IGVFSM8067OJHZ
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:subpool_014_13B'], 'cellular_sub_pool': '014_13B', 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'multiplexed_samples': ['/tissues/IGVFSM0442UOPQ/', '/tissues/IGVFSM0557OIVT/', '/tissues/IGVFSM8807AADG/', '/tissues/IGVFSM9622JHKX/', '/tissues/IGVFSM4826GDRP/', '/tissues/IGVFSM7316AFZJ/', '/tissues/IGVFSM7526UDOL/', '/tissues/IGVFSM9353XAPN/'], 'accession': 'IGVFSM5384UHCR', 'status': 'in progress', 'schema_version': '4', 'creation_timestamp': '2023-10-26T18:54:22.143921+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/multiplexed-samples/IGVFSM5384UHCR/', '@type': ['MultiplexedSample', 'Sample', 'Item'], 'uuid': 'd19a5af5-b9b5-45b8-8e21-4ffb714f0167', 'summary': 'multiplexed sample of peripheral blood mononuclear cell tissue, female, Mus musculus B6J, peripheral blood mononuclear cell tissue, male, Mus musculus B6J, ... and 6 more samples', 'file_sets': [], 'multiplexed_in': [], 'sample_terms': ['/sample-terms/CL_2000001/'], 'disease_terms': [], 'treatments': [], 'modifications': [], 'donors': ['/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5216CAMJ/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO9239QBJY/'], 'biomarkers': [], 'sources': ['/sources/jackson-labs/'], 'construct_library_sets': [], 'classification': 'multiplexed sample'}]}
row 1 created: IGVFSM5384UHCR
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:subpool_014_13C'], 'cellular_sub_pool': '014_13C', 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'multiplexed_samples': ['/tissues/IGVFSM0442UOPQ/', '/tissues/IGVFSM0557OIVT/', '/tissues/IGVFSM8807AADG/', '/tissues/IGVFSM9622JHKX/', '/tissues/IGVFSM4826GDRP/', '/tissues/IGVFSM7316AFZJ/', '/tissues/IGVFSM7526UDOL/', '/tissues/IGVFSM9353XAPN/'], 'accession': 'IGVFSM6472IKNB', 'status': 'in progress', 'schema_version': '4', 'creation_timestamp': '2023-10-26T18:54:22.584178+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/multiplexed-samples/IGVFSM6472IKNB/', '@type': ['MultiplexedSample', 'Sample', 'Item'], 'uuid': '9c1c3979-0c78-41f9-9a79-81262d85bc89', 'summary': 'multiplexed sample of peripheral blood mononuclear cell tissue, female, Mus musculus B6J, peripheral blood mononuclear cell tissue, male, Mus musculus B6J, ... and 6 more samples', 'file_sets': [], 'multiplexed_in': [], 'sample_terms': ['/sample-terms/CL_2000001/'], 'disease_terms': [], 'treatments': [], 'modifications': [], 'donors': ['/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5216CAMJ/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO9239QBJY/'], 'biomarkers': [], 'sources': ['/sources/jackson-labs/'], 'construct_library_sets': [], 'classification': 'multiplexed sample'}]}
row 2 created: IGVFSM6472IKNB
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:subpool_014_13D'], 'cellular_sub_pool': '014_13D', 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'multiplexed_samples': ['/tissues/IGVFSM0442UOPQ/', '/tissues/IGVFSM0557OIVT/', '/tissues/IGVFSM8807AADG/', '/tissues/IGVFSM9622JHKX/', '/tissues/IGVFSM4826GDRP/', '/tissues/IGVFSM7316AFZJ/', '/tissues/IGVFSM7526UDOL/', '/tissues/IGVFSM9353XAPN/'], 'accession': 'IGVFSM5754CVHL', 'status': 'in progress', 'schema_version': '4', 'creation_timestamp': '2023-10-26T18:54:23.073798+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/multiplexed-samples/IGVFSM5754CVHL/', '@type': ['MultiplexedSample', 'Sample', 'Item'], 'uuid': '392480a2-f9d5-46ac-94d4-510c03d751a6', 'summary': 'multiplexed sample of peripheral blood mononuclear cell tissue, female, Mus musculus B6J, peripheral blood mononuclear cell tissue, male, Mus musculus B6J, ... and 6 more samples', 'file_sets': [], 'multiplexed_in': [], 'sample_terms': ['/sample-terms/CL_2000001/'], 'disease_terms': [], 'treatments': [], 'modifications': [], 'donors': ['/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5216CAMJ/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO9239QBJY/'], 'biomarkers': [], 'sources': ['/sources/jackson-labs/'], 'construct_library_sets': [], 'classification': 'multiplexed sample'}]}
row 3 created: IGVFSM5754CVHL
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:subpool_014_13E'], 'cellular_sub_pool': '014_13E', 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'multiplexed_samples': ['/tissues/IGVFSM0442UOPQ/', '/tissues/IGVFSM0557OIVT/', '/tissues/IGVFSM8807AADG/', '/tissues/IGVFSM9622JHKX/', '/tissues/IGVFSM4826GDRP/', '/tissues/IGVFSM7316AFZJ/', '/tissues/IGVFSM7526UDOL/', '/tissues/IGVFSM9353XAPN/'], 'accession': 'IGVFSM2943LQAO', 'status': 'in progress', 'schema_version': '4', 'creation_timestamp': '2023-10-26T18:54:23.550309+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/multiplexed-samples/IGVFSM2943LQAO/', '@type': ['MultiplexedSample', 'Sample', 'Item'], 'uuid': 'b7bf4643-93e7-45fa-8738-f752c25d427c', 'summary': 'multiplexed sample of peripheral blood mononuclear cell tissue, female, Mus musculus B6J, peripheral blood mononuclear cell tissue, male, Mus musculus B6J, ... and 6 more samples', 'file_sets': [], 'multiplexed_in': [], 'sample_terms': ['/sample-terms/CL_2000001/'], 'disease_terms': [], 'treatments': [], 'modifications': [], 'donors': ['/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5216CAMJ/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO9239QBJY/'], 'biomarkers': [], 'sources': ['/sources/jackson-labs/'], 'construct_library_sets': [], 'classification': 'multiplexed sample'}]}
row 4 created: IGVFSM2943LQAO

Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:subpool_014_13F'], 'cellular_sub_pool': '014_13F', 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'multiplexed_samples': ['/tissues/IGVFSM0442UOPQ/', '/tissues/IGVFSM0557OIVT/', '/tissues/IGVFSM8807AADG/', '/tissues/IGVFSM9622JHKX/', '/tissues/IGVFSM4826GDRP/', '/tissues/IGVFSM7316AFZJ/', '/tissues/IGVFSM7526UDOL/', '/tissues/IGVFSM9353XAPN/'], 'accession': 'IGVFSM6217PCCA', 'status': 'in progress', 'schema_version': '4', 'creation_timestamp': '2023-10-26T18:54:23.905674+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/multiplexed-samples/IGVFSM6217PCCA/', '@type': ['MultiplexedSample', 'Sample', 'Item'], 'uuid': '9b709de1-375d-46f6-a537-5678d8019ea4', 'summary': 'multiplexed sample of peripheral blood mononuclear cell tissue, female, Mus musculus B6J, peripheral blood mononuclear cell tissue, male, Mus musculus B6J, ... and 6 more samples', 'file_sets': [], 'multiplexed_in': [], 'sample_terms': ['/sample-terms/CL_2000001/'], 'disease_terms': [], 'treatments': [], 'modifications': [], 'donors': ['/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5216CAMJ/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO9239QBJY/'], 'biomarkers': [], 'sources': ['/sources/jackson-labs/'], 'construct_library_sets': [], 'classification': 'multiplexed sample'}]}
row 5 created: IGVFSM6217PCCA
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:subpool_014_13G'], 'cellular_sub_pool': '014_13G', 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'multiplexed_samples': ['/tissues/IGVFSM0442UOPQ/', '/tissues/IGVFSM0557OIVT/', '/tissues/IGVFSM8807AADG/', '/tissues/IGVFSM9622JHKX/', '/tissues/IGVFSM4826GDRP/', '/tissues/IGVFSM7316AFZJ/', '/tissues/IGVFSM7526UDOL/', '/tissues/IGVFSM9353XAPN/'], 'accession': 'IGVFSM1754MJSQ', 'status': 'in progress', 'schema_version': '4', 'creation_timestamp': '2023-10-26T18:54:24.397815+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/multiplexed-samples/IGVFSM1754MJSQ/', '@type': ['MultiplexedSample', 'Sample', 'Item'], 'uuid': '0b56346c-81a2-407a-921d-6c01e61eaffe', 'summary': 'multiplexed sample of peripheral blood mononuclear cell tissue, female, Mus musculus B6J, peripheral blood mononuclear cell tissue, male, Mus musculus B6J, ... and 6 more samples', 'file_sets': [], 'multiplexed_in': [], 'sample_terms': ['/sample-terms/CL_2000001/'], 'disease_terms': [], 'treatments': [], 'modifications': [], 'donors': ['/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5216CAMJ/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO9239QBJY/'], 'biomarkers': [], 'sources': ['/sources/jackson-labs/'], 'construct_library_sets': [], 'classification': 'multiplexed sample'}]}
row 6 created: IGVFSM1754MJSQ
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:subpool_014_13H'], 'cellular_sub_pool': '014_13H', 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'multiplexed_samples': ['/tissues/IGVFSM0442UOPQ/', '/tissues/IGVFSM0557OIVT/', '/tissues/IGVFSM8807AADG/', '/tissues/IGVFSM9622JHKX/', '/tissues/IGVFSM4826GDRP/', '/tissues/IGVFSM7316AFZJ/', '/tissues/IGVFSM7526UDOL/', '/tissues/IGVFSM9353XAPN/'], 'accession': 'IGVFSM5239HNPO', 'status': 'in progress', 'schema_version': '4', 'creation_timestamp': '2023-10-26T18:54:24.739937+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', 'virtual': False, '@id': '/multiplexed-samples/IGVFSM5239HNPO/', '@type': ['MultiplexedSample', 'Sample', 'Item'], 'uuid': 'afbe2416-626c-4019-88c1-7d3edebd15a5', 'summary': 'multiplexed sample of peripheral blood mononuclear cell tissue, female, Mus musculus B6J, peripheral blood mononuclear cell tissue, male, Mus musculus B6J, ... and 6 more samples', 'file_sets': [], 'multiplexed_in': [], 'sample_terms': ['/sample-terms/CL_2000001/'], 'disease_terms': [], 'treatments': [], 'modifications': [], 'donors': ['/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5216CAMJ/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO9239QBJY/'], 'biomarkers': [], 'sources': ['/sources/jackson-labs/'], 'construct_library_sets': [], 'classification': 'multiplexed sample'}]}
row 7 created: IGVFSM5239HNPO
8

,accession,uuid,aliases:array,cellular_sub_pool,award,lab,multiplexed_samples:array
0,IGVFSM8067OJHZ,b7829abc-32c2-48d7-956e-a085550ebf54,ali-mortazavi:subpool_014_13A,014_13A,/awards/HG012077/,/labs/ali-mortazavi/,"ali-mortazavi:255_B6J_10M_20_CL_2000001,ali-mo..."
1,IGVFSM5384UHCR,d19a5af5-b9b5-45b8-8e21-4ffb714f0167,ali-mortazavi:subpool_014_13B,014_13B,/awards/HG012077/,/labs/ali-mortazavi/,"ali-mortazavi:255_B6J_10M_20_CL_2000001,ali-mo..."
2,IGVFSM6472IKNB,9c1c3979-0c78-41f9-9a79-81262d85bc89,ali-mortazavi:subpool_014_13C,014_13C,/awards/HG012077/,/labs/ali-mortazavi/,"ali-mortazavi:255_B6J_10M_20_CL_2000001,ali-mo..."
3,IGVFSM5754CVHL,392480a2-f9d5-46ac-94d4-510c03d751a6,ali-mortazavi:subpool_014_13D,014_13D,/awards/HG012077/,/labs/ali-mortazavi/,"ali-mortazavi:255_B6J_10M_20_CL_2000001,ali-mo..."
4,IGVFSM2943LQAO,b7bf4643-93e7-45fa-8738-f752c25d427c,ali-mortazavi:subpool_014_13E,014_13E,/awards/HG012077/,/labs/ali-mortazavi/,"ali-mortazavi:255_B6J_10M_20_CL_2000001,ali-mo..."
5,IGVFSM6217PCCA,9b709de1-375d-46f6-a537-5678d8019ea4,ali-mortazavi:subpool_014_13F,014_13F,/awards/HG012077/,/labs/ali-mortazavi/,"ali-mortazavi:255_B6J_10M_20_CL_2000001,ali-mo..."
6,IGVFSM1754MJSQ,0b56346c-81a2-407a-921d-6c01e61eaffe,ali-mortazavi:subpool_014_13G,014_13G,/awards/HG012077/,/labs/ali-mortazavi/,"ali-mortazavi:255_B6J_10M_20_CL_2000001,ali-mo..."
7,IGVFSM5239HNPO,afbe2416-626c-4019-88c1-7d3edebd15a5,ali-mortazavi:subpool_014_13H,014_13H,/awards/HG012077/,/labs/ali-mortazavi/,"ali-mortazavi:255_B6J_10M_20_CL_2000001,ali-mo..."

In [ ]:
for well in plate.splitseqwell_set.all():
    print(well)
    for biosample in well.biosample.all():
        print(biosample)
        for tissue in biosample.extraction.tissue.all():
            print(tissue)
            #mouse_alias = f"ali-mortazavi:{tissue.mouse.name}"
            # I need an ordered set of donors
            #donors[mouse_alias] = tissue.mouse
            for term in tissue.ontology_term.all():
                print(term)
                #curie = term.curie.replace(":", "_")
                #tissue_alias = f"ali-mortazavi:{tissue.name}_{curie}"
                #samples[tissue_alias] = None

In [14]:
#get_samples_donors(plate)

# measurement_set

In [15]:
for run in models.SequencingRun.objects.all():
    print(run.platform.name, run.name, run.plate, run.subpoolinrun_set.count())

nextseq2000 igvf_003/nextseq2 IGVF_003 1
nextseq2000 igvf_003/nextseq IGVF_003 3
minion igvf_003/nanopore IGVF_003 1
novaseq6000 igvf_003/nova1 IGVF_003 15
novaseq6000 igvf_003/nova2 IGVF_003 15
nextseq2000 igvf_004/nextseq2 IGVF_004 1
nextseq2000 igvf_004/nextseq IGVF_004 3
novaseq6000 igvf_004/nova1 IGVF_004 15
novaseq6000 igvf_004/nova2 IGVF_004 15
nextseq2000 igvf_005/nextseq2 IGVF_005 1
novaseq6000 igvf_005/nova1 IGVF_005 15
novaseq6000 igvf_005/nova2 IGVF_005 15
nextseq2000 igvf_007/nextseq2 IGVF_007 1
novaseq6000 igvf_007/nova1 IGVF_007 15
novaseq6000 igvf_007/nova2 IGVF_007 15
nextseq2000 igvf_008/nextseq IGVF_008 3
novaseq6000 igvf_008/nova1 IGVF_008 9
nextseq2000 igvf_008b/nextseq2 IGVF_008B 1
nextseq2000 igvf_008b/nextseq IGVF_008B 2
novaseq6000 igvf_008b/nova1 IGVF_008B 10
nextseq2000 igvf_009/nextseq2 IGVF_009 1
nextseq2000 igvf_009/nextseq IGVF_009 2
novaseq6000 igvf_009/nova1 IGVF_009 15
novaseq6000 igvf_009/nova2 IGVF_009 15
nextseq2000 igvf_010/nextseq2 IGVF_010 1
nextseq2000 igvf_010/nextseq IGVF_010 2
novaseq6000 igvf_010/nova1 IGVF_010 15
novaseq6000 igvf_010/nova2 IGVF_010 15
nextseq2000 igvf_011/nextseq2 IGVF_011 1
nextseq2000 igvf_011/nextseq IGVF_011 2
novaseq6000 igvf_011/nova1 IGVF_011 15
novaseq6000 igvf_011/nova2 IGVF_011 15
nextseq2000 igvf_012/nextseq IGVF_012 8
nextseq2000 igvf_013/nextseq IGVF_013 3
novaseq6000 igvf_013/nova1 IGVF_013 14
nextseq2000 igvf_014/nextseq IGVF_014 8
nextseq2000 igvf_b01/next2 IGVF_B01 8
nextseq2000 igvf_b01/next1 IGVF_B01 8

In [16]:
run.subpoolinrun_set.count()

8

In [17]:
measurement_sets = {}
for run in models.SequencingRun.objects.all():
    platform = run.platform.family
    for subpoolinrun in run.subpoolinrun_set.filter(status="P"):
        #print(run.name, run.plate.name, run.platform.name, subpoolrun.id, subpoolrun.subpool.name, subpoolrun.subpoolrunfile_set.count())
        name = "{}_{}".format(subpoolinrun.subpool.name, platform)
        alias = f"ali-mortazavi:{name}"
        measurement_sets.setdefault(alias, set()).add(subpoolinrun)

In [26]:
def get_measurement_set_accession(alias, measurement_set):
    if measurement_set is None:
        try:
            posted = server.get_json(alias)
            return posted["accession"]
        except encoded.HTTPError as e:
            if e.response.status_code == 404:
                pass
            else:
                print("HTTPError", e)
        return None

    accessions = measurement_set.accession.filter(namespace__accession_prefix=accession_prefix)
    if len(accessions) > 1:
        raise RuntimeError("Too many accessions")
    elif len(accessions) == 1:
        return accessions[0].name

    return None

measurements = []
sequence_data = []
#plate_cache = {}

sequencing_library_type_map = {
    "NO": 'mRNA enriched',
    "EX": "exome capture",
}

subcompartment_assay = {
    "C": "/assay-terms/OBI_0002631/",
    "N": "/assay-terms/OBI_0003109/",
}

assay_id_to_term_name = {
    "/assay-terms/OBI_0002631/": "scRNA-seq",
    "/assay-terms/OBI_0003109/": "snRNA-seq",
}

for alias in measurement_sets:
    run = next(iter(measurement_sets[alias]))
    subpool = run.subpool
    plate_details = run.sequencing_run.plate
    if plate_details.name == test_run_name:   
        #plate_details = plate_cache.setdefault(plate, get_samples_donors(plate))
        # FIXME: It's possible to have both on the same plate.
        subcellular_component = subpool.plate.splitseqwell_set.first().biosample.first().extraction.cellular_component
        assay_term_id = subcompartment_assay[subcellular_component]
        assay_term_name = assay_id_to_term_name[assay_term_id]
        measurement_row = {
            "accession": get_measurement_set_accession(alias, run.measurement_set),
            "uuid": None,
            "aliases:array": alias,
            "award": award,
            "lab": lab,
            "assay_term": assay_term_id,
            "assay_term_name:skip": assay_term_name,
            "preferred_assay_title": "Parse Split-seq",
            "sequencing_library_types:array": ",".join([sequencing_library_type_map[subpool.selection_type]]),
            "documents": None,
            "alternate_accessions": None,
            #"submitter_comment": None,
            "description": None,
            # old attach all the samples to the measurement_set
            #"samples:array": ",".join(plate_details["samples"]),
            # New attach the multiplexed_sample to the measurement_set
            "samples:array": "ali-mortazavi:subpool_{}".format(subpool.name),
            "protocol": None,
        }
        measurements.append(measurement_row)
            
measurements = pandas.DataFrame(measurements)
#if 1:
#    measurements.to_excel("measurement_set.{}.xlsx".format(server_name), index=False)

dry_run = True
created = server.post_sheet("measurement_set", measurements, dry_run=dry_run, verbose=True, validator=validator)
print(len(created))
#if len(created) > 0 and not dry_run:
#    measurements.to_excel("measurement_set.{}.xlsx".format(server_name), index=False)
measurements

Error http status: 404 for https://api.data.igvf.org/ali-mortazavi:014_13A_illumina
Error http status: 404 for https://api.data.igvf.org/ali-mortazavi:014_13B_illumina
Error http status: 404 for https://api.data.igvf.org/ali-mortazavi:014_13C_illumina
Error http status: 404 for https://api.data.igvf.org/ali-mortazavi:014_13D_illumina
Error http status: 404 for https://api.data.igvf.org/ali-mortazavi:014_13E_illumina
Error http status: 404 for https://api.data.igvf.org/ali-mortazavi:014_13F_illumina
Error http status: 404 for https://api.data.igvf.org/ali-mortazavi:014_13G_illumina
Error http status: 404 for https://api.data.igvf.org/ali-mortazavi:014_13H_illumina

Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:014_13A_illumina'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'assay_term': '/assay-terms/OBI_0003109/', 'preferred_assay_title': 'Parse Split-seq', 'sequencing_library_types': ['mRNA enriched'], 'samples': ['/multiplexed-samples/IGVFSM8067OJHZ/'], 'accession': 'IGVFDS8381SGFM', 'status': 'in progress', 'schema_version': '9', 'creation_timestamp': '2023-10-26T18:55:09.273047+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', '@id': '/measurement-sets/IGVFDS8381SGFM/', '@type': ['MeasurementSet', 'FileSet', 'Item'], 'uuid': '983e4c8c-2d00-4ea8-b0bf-f375c419577c', 'summary': 'single-nucleus RNA sequencing assay (Parse Split-seq)', 'files': [], 'control_for': [], 'donors': ['/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO9239QBJY/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO5216CAMJ/']}]}
row 0 created: IGVFDS8381SGFM
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:014_13B_illumina'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'assay_term': '/assay-terms/OBI_0003109/', 'preferred_assay_title': 'Parse Split-seq', 'sequencing_library_types': ['mRNA enriched'], 'samples': ['/multiplexed-samples/IGVFSM5384UHCR/'], 'accession': 'IGVFDS1863PKHG', 'status': 'in progress', 'schema_version': '9', 'creation_timestamp': '2023-10-26T18:55:09.635894+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', '@id': '/measurement-sets/IGVFDS1863PKHG/', '@type': ['MeasurementSet', 'FileSet', 'Item'], 'uuid': '548941d3-86af-42f0-bb13-c1633f2b41d5', 'summary': 'single-nucleus RNA sequencing assay (Parse Split-seq)', 'files': [], 'control_for': [], 'donors': ['/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO9239QBJY/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO5216CAMJ/']}]}
row 1 created: IGVFDS1863PKHG
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:014_13C_illumina'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'assay_term': '/assay-terms/OBI_0003109/', 'preferred_assay_title': 'Parse Split-seq', 'sequencing_library_types': ['mRNA enriched'], 'samples': ['/multiplexed-samples/IGVFSM6472IKNB/'], 'accession': 'IGVFDS0002EUAT', 'status': 'in progress', 'schema_version': '9', 'creation_timestamp': '2023-10-26T18:55:10.024306+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', '@id': '/measurement-sets/IGVFDS0002EUAT/', '@type': ['MeasurementSet', 'FileSet', 'Item'], 'uuid': '06bf3adc-9e0f-4e1a-b031-69985ccd4d55', 'summary': 'single-nucleus RNA sequencing assay (Parse Split-seq)', 'files': [], 'control_for': [], 'donors': ['/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO9239QBJY/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO5216CAMJ/']}]}
row 2 created: IGVFDS0002EUAT
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:014_13D_illumina'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'assay_term': '/assay-terms/OBI_0003109/', 'preferred_assay_title': 'Parse Split-seq', 'sequencing_library_types': ['mRNA enriched'], 'samples': ['/multiplexed-samples/IGVFSM5754CVHL/'], 'accession': 'IGVFDS9856ONKI', 'status': 'in progress', 'schema_version': '9', 'creation_timestamp': '2023-10-26T18:55:10.426238+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', '@id': '/measurement-sets/IGVFDS9856ONKI/', '@type': ['MeasurementSet', 'FileSet', 'Item'], 'uuid': '017ffe92-ac5c-4aa7-8034-13e95be146c2', 'summary': 'single-nucleus RNA sequencing assay (Parse Split-seq)', 'files': [], 'control_for': [], 'donors': ['/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO9239QBJY/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO5216CAMJ/']}]}
row 3 created: IGVFDS9856ONKI
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:014_13E_illumina'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'assay_term': '/assay-terms/OBI_0003109/', 'preferred_assay_title': 'Parse Split-seq', 'sequencing_library_types': ['mRNA enriched'], 'samples': ['/multiplexed-samples/IGVFSM2943LQAO/'], 'accession': 'IGVFDS3816YLEC', 'status': 'in progress', 'schema_version': '9', 'creation_timestamp': '2023-10-26T18:55:10.927080+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', '@id': '/measurement-sets/IGVFDS3816YLEC/', '@type': ['MeasurementSet', 'FileSet', 'Item'], 'uuid': 'bbb851eb-1cb1-4aee-a418-6708425b229c', 'summary': 'single-nucleus RNA sequencing assay (Parse Split-seq)', 'files': [], 'control_for': [], 'donors': ['/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO9239QBJY/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO5216CAMJ/']}]}
row 4 created: IGVFDS3816YLEC
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:014_13F_illumina'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'assay_term': '/assay-terms/OBI_0003109/', 'preferred_assay_title': 'Parse Split-seq', 'sequencing_library_types': ['mRNA enriched'], 'samples': ['/multiplexed-samples/IGVFSM6217PCCA/'], 'accession': 'IGVFDS4633VNVI', 'status': 'in progress', 'schema_version': '9', 'creation_timestamp': '2023-10-26T18:55:11.301387+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', '@id': '/measurement-sets/IGVFDS4633VNVI/', '@type': ['MeasurementSet', 'FileSet', 'Item'], 'uuid': '6afc288b-0afe-4ad0-b9b8-75fa3da232b0', 'summary': 'single-nucleus RNA sequencing assay (Parse Split-seq)', 'files': [], 'control_for': [], 'donors': ['/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO9239QBJY/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO5216CAMJ/']}]}
row 5 created: IGVFDS4633VNVI
Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:014_13G_illumina'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'assay_term': '/assay-terms/OBI_0003109/', 'preferred_assay_title': 'Parse Split-seq', 'sequencing_library_types': ['mRNA enriched'], 'samples': ['/multiplexed-samples/IGVFSM1754MJSQ/'], 'accession': 'IGVFDS1481OFSB', 'status': 'in progress', 'schema_version': '9', 'creation_timestamp': '2023-10-26T18:55:11.672149+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', '@id': '/measurement-sets/IGVFDS1481OFSB/', '@type': ['MeasurementSet', 'FileSet', 'Item'], 'uuid': '186660ee-eb69-4081-ba9b-91758b9c1e86', 'summary': 'single-nucleus RNA sequencing assay (Parse Split-seq)', 'files': [], 'control_for': [], 'donors': ['/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO9239QBJY/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO5216CAMJ/']}]}
row 6 created: IGVFDS1481OFSB

Reponse {'status': 'success', '@type': ['result'], '@graph': [{'aliases': ['ali-mortazavi:014_13H_illumina'], 'award': '/awards/HG012077/', 'lab': '/labs/ali-mortazavi/', 'assay_term': '/assay-terms/OBI_0003109/', 'preferred_assay_title': 'Parse Split-seq', 'sequencing_library_types': ['mRNA enriched'], 'samples': ['/multiplexed-samples/IGVFSM5239HNPO/'], 'accession': 'IGVFDS7742UGBF', 'status': 'in progress', 'schema_version': '9', 'creation_timestamp': '2023-10-26T18:55:12.051614+00:00', 'submitted_by': '/users/ebd1025b-e3ab-4e51-bfcd-1415f278281a/', '@id': '/measurement-sets/IGVFDS7742UGBF/', '@type': ['MeasurementSet', 'FileSet', 'Item'], 'uuid': '7eecae2c-e84a-402b-95c8-fa786ac6e07d', 'summary': 'single-nucleus RNA sequencing assay (Parse Split-seq)', 'files': [], 'control_for': [], 'donors': ['/rodent-donors/IGVFDO7584QEOX/', '/rodent-donors/IGVFDO6294BKKV/', '/rodent-donors/IGVFDO4258RYAV/', '/rodent-donors/IGVFDO5893GZJR/', '/rodent-donors/IGVFDO9239QBJY/', '/rodent-donors/IGVFDO4255NQNV/', '/rodent-donors/IGVFDO0654QHHA/', '/rodent-donors/IGVFDO5216CAMJ/']}]}
row 7 created: IGVFDS7742UGBF
8

,accession,uuid,aliases:array,award,lab,assay_term,assay_term_name:skip,preferred_assay_title,sequencing_library_types:array,documents,alternate_accessions,description,samples:array,protocol
0,IGVFDS8381SGFM,983e4c8c-2d00-4ea8-b0bf-f375c419577c,ali-mortazavi:014_13A_illumina,/awards/HG012077/,/labs/ali-mortazavi/,/assay-terms/OBI_0003109/,snRNA-seq,Parse Split-seq,mRNA enriched,None,None,None,ali-mortazavi:subpool_014_13A,None
1,IGVFDS1863PKHG,548941d3-86af-42f0-bb13-c1633f2b41d5,ali-mortazavi:014_13B_illumina,/awards/HG012077/,/labs/ali-mortazavi/,/assay-terms/OBI_0003109/,snRNA-seq,Parse Split-seq,mRNA enriched,None,None,None,ali-mortazavi:subpool_014_13B,None
2,IGVFDS0002EUAT,06bf3adc-9e0f-4e1a-b031-69985ccd4d55,ali-mortazavi:014_13C_illumina,/awards/HG012077/,/labs/ali-mortazavi/,/assay-terms/OBI_0003109/,snRNA-seq,Parse Split-seq,mRNA enriched,None,None,None,ali-mortazavi:subpool_014_13C,None
3,IGVFDS9856ONKI,017ffe92-ac5c-4aa7-8034-13e95be146c2,ali-mortazavi:014_13D_illumina,/awards/HG012077/,/labs/ali-mortazavi/,/assay-terms/OBI_0003109/,snRNA-seq,Parse Split-seq,mRNA enriched,None,None,None,ali-mortazavi:subpool_014_13D,None
4,IGVFDS3816YLEC,bbb851eb-1cb1-4aee-a418-6708425b229c,ali-mortazavi:014_13E_illumina,/awards/HG012077/,/labs/ali-mortazavi/,/assay-terms/OBI_0003109/,snRNA-seq,Parse Split-seq,mRNA enriched,None,None,None,ali-mortazavi:subpool_014_13E,None
5,IGVFDS4633VNVI,6afc288b-0afe-4ad0-b9b8-75fa3da232b0,ali-mortazavi:014_13F_illumina,/awards/HG012077/,/labs/ali-mortazavi/,/assay-terms/OBI_0003109/,snRNA-seq,Parse Split-seq,mRNA enriched,None,None,None,ali-mortazavi:subpool_014_13F,None
6,IGVFDS1481OFSB,186660ee-eb69-4081-ba9b-91758b9c1e86,ali-mortazavi:014_13G_illumina,/awards/HG012077/,/labs/ali-mortazavi/,/assay-terms/OBI_0003109/,snRNA-seq,Parse Split-seq,mRNA enriched,None,None,None,ali-mortazavi:subpool_014_13G,None
7,IGVFDS7742UGBF,7eecae2c-e84a-402b-95c8-fa786ac6e07d,ali-mortazavi:014_13H_illumina,/awards/HG012077/,/labs/ali-mortazavi/,/assay-terms/OBI_0003109/,snRNA-seq,Parse Split-seq,mRNA enriched,None,None,None,ali-mortazavi:subpool_014_13H,None

In [19]:
def resolve_aliases(entities):
    resolved = []
    for element in entities:
        if ":" in element:
            obj = server.get_json(element)
            resolved.append(obj["@id"])
        else:
            resolved.append(element)
    return resolved

#resolve_aliases(["ali-mortazavi:118_B6J_10F_21_NTR_0000646","ali-mortazavi:117_B6J_10M_21_NTR_0000646","ali-mortazavi:106_CASTJ_10F_21_NTR_0000646"])

In [20]:
# if need to fix sample list in measurement set.
if 0:
    for i, row in measurements.iterrows():
        measurement_set = server.get_json(row["accession"])
        desired_biosample = resolve_aliases(row["samples:array"].split(","))

        payload = {}
        different_biosample = set(desired_biosample).symmetric_difference(measurement_set["samples"])
        if len(different_biosample) > 0:
            payload.update({"samples": desired_biosample})
           

        sequencing_library_type = row["sequencing_library_type:array"].split(",")
        if measurement_set.get("sequencing_library_type") != sequencing_library_type:
            payload.update({"sequencing_library_type": sequencing_library_type})
            
        print(measurement_set["@id"], payload)
        #if True and len(payload) > 0:
        #    print(server.patch_json(measurement_set["@id"], payload))
    measurements.to_excel("measurement_set.{}.xlsx".format(server_name), index=False)
    
    for i, row in measurements.iterrows():
        if not (pandas.isnull(row["accession"]) or row["accession"] == "would create"):
            dcc = server.get_json("/measurement_set/{}/".format(row["accession"]))
            print(row["accession"], len(dcc["samples"]), len(row["samples:array"].split(",")))

In [21]:
sequence_file = []
plate_cache = {}

for alias in sorted(measurement_sets):
    run_break = None
    run_id = 1    
    for run in measurement_sets[alias]:
        #print(type(run), run.id, run.subpool.name, run.sequencing_run.name, run.measurement_set)
        current_plate = run.sequencing_run.plate
        if current_plate.name == test_run_name:
            plate_details = plate_cache.setdefault(current_plate, get_samples_donors(current_plate))
            
            for run_file in run.subpoolinrunfile_set.order_by("subpool_run", "lane", "read"):
                # Need to lookup accession
                if run_file.read in ("I1",):
                    continue
                
                current_break = (run_file.subpool_run.sequencing_run.id, run_file.subpool_run.id, run_file.lane)
                if run_break is None:
                    run_break = current_break
                elif run_break != current_break:
                    run_id += 1
                    run_break = current_break
                
                accession = run_file.accession.filter(accession_prefix=accession_prefix)
                if len(accession) > 1:
                    print("Several accessions? {} {}".format(run_file.filename, ",".join(accessions)))
                    accession = accession[0].name
                elif len(accession) == 1:
                    accession = accession[0].name
                else:
                    accession = None
                
                file_row = {
                    "accession": accession,
                    "uuid": None,
                    #"aliases": None,
                    "award": award,
                    "lab": lab,
                    "md5sum": run_file.md5sum,
                    "file_format": "fastq",
                    "file_set": alias,
                    "content_type": "reads",
                    "sequencing_run:integer": run_id,
                    "documents:array": None,
                    "submitter_comment": None,
                    "description": None,
                    "dbxrefs": None,
                    "derived_from": None,
                    "seqspec": None,
                    "sequencing_platform": run_file.sequencing_run.platform.igvf_id,
                    "submitted_file_name": run_file.filename,
                    "flowcell_id": run_file.flowcell_id,
                    "lane:integer": run_file.lane,
                    "illumina_read_type": run_file.read,
                }
                sequence_file.append(file_row)                
        

sequence_file = pandas.DataFrame(sequence_file)

# we want to validate these objects, but the actual posting will happen on the computer with the files.
#created = server.post_sheet("sequence_file", sequence_file, dry_run=True, verbose=True, validator=validator)

sequence_file.to_excel("sequence_file.{}.xlsx".format(server_name), index=False)
sequence_file

,accession,uuid,award,lab,md5sum,file_format,file_set,content_type,sequencing_run:integer,documents:array,submitter_comment,description,dbxrefs,derived_from,seqspec,sequencing_platform,submitted_file_name,flowcell_id,lane:integer,illumina_read_type
0,None,None,/awards/HG012077/,/labs/ali-mortazavi/,8b0b63571a98c699694c0459e219a7af,fastq,ali-mortazavi:014_13A_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13A_R1.fastq.gz,AAC3H2WHV,None,R1
1,None,None,/awards/HG012077/,/labs/ali-mortazavi/,0b644d82d966dddeee5f274bb9c5f5ca,fastq,ali-mortazavi:014_13A_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13A_R2.fastq.gz,AAC3H2WHV,None,R2
2,None,None,/awards/HG012077/,/labs/ali-mortazavi/,9c2fad499df014d209f03a35a3e837a9,fastq,ali-mortazavi:014_13B_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13B_R1.fastq.gz,AAC3H2WHV,None,R1
3,None,None,/awards/HG012077/,/labs/ali-mortazavi/,2e707aa83228da26e84109a758887352,fastq,ali-mortazavi:014_13B_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13B_R2.fastq.gz,AAC3H2WHV,None,R2
4,None,None,/awards/HG012077/,/labs/ali-mortazavi/,51b730523ba8e77c569cc28ceeb60b6c,fastq,ali-mortazavi:014_13C_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13C_R1.fastq.gz,AAC3H2WHV,None,R1
5,None,None,/awards/HG012077/,/labs/ali-mortazavi/,8d440c1ac342f7e81a12e9b61cab1f37,fastq,ali-mortazavi:014_13C_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13C_R2.fastq.gz,AAC3H2WHV,None,R2
6,None,None,/awards/HG012077/,/labs/ali-mortazavi/,63c2f08516a357842c910eb51a27345a,fastq,ali-mortazavi:014_13D_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13D_R1.fastq.gz,AAC3H2WHV,None,R1
7,None,None,/awards/HG012077/,/labs/ali-mortazavi/,54f64d7579053fb9d27050f051292b30,fastq,ali-mortazavi:014_13D_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13D_R2.fastq.gz,AAC3H2WHV,None,R2
8,None,None,/awards/HG012077/,/labs/ali-mortazavi/,1465f7820f2997ca7e5338d3e58cf567,fastq,ali-mortazavi:014_13E_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13E_R1.fastq.gz,AAC3H2WHV,None,R1
9,None,None,/awards/HG012077/,/labs/ali-mortazavi/,4fe6d28d13ef7063c1a84c01f8946645,fastq,ali-mortazavi:014_13E_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13E_R2.fastq.gz,AAC3H2WHV,None,R2
10,None,None,/awards/HG012077/,/labs/ali-mortazavi/,3ca315ec672c9083f706451e735c77c1,fastq,ali-mortazavi:014_13F_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13F_R1.fastq.gz,AAC3H2WHV,None,R1
11,None,None,/awards/HG012077/,/labs/ali-mortazavi/,d85e036ea64ae171bb1a4e2e1c667c13,fastq,ali-mortazavi:014_13F_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13F_R2.fastq.gz,AAC3H2WHV,None,R2
12,None,None,/awards/HG012077/,/labs/ali-mortazavi/,30135f1bc26bad4e7cc2839838960591,fastq,ali-mortazavi:014_13G_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13G_R1.fastq.gz,AAC3H2WHV,None,R1
13,None,None,/awards/HG012077/,/labs/ali-mortazavi/,6a148ed8687a7614d72f4da6003e2512,fastq,ali-mortazavi:014_13G_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13G_R2.fastq.gz,AAC3H2WHV,None,R2
14,None,None,/awards/HG012077/,/labs/ali-mortazavi/,515753b5caeb6d4606ef99aea4320ce2,fastq,ali-mortazavi:014_13H_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13H_R1.fastq.gz,AAC3H2WHV,None,R1
15,None,None,/awards/HG012077/,/labs/ali-mortazavi/,04dd00bc4706252a232edc8777d7ce8b,fastq,ali-mortazavi:014_13H_illumina,reads,1,None,None,None,None,None,None,/platform-terms/EFO_0010963/,igvf_014/nextseq/014_13H_R2.fastq.gz,AAC3H2WHV,None,R2

In [27]:
with pandas.ExcelWriter("{}_{}.xlsx".format(test_run_name, upload_target)) as book:
    rodent_donor.to_excel(book, sheet_name="rodent_donor", index=None)
    tissue_sheet.to_excel(book, sheet_name="tissue", index=None)
    multiplexed_sample.to_excel(book, sheet_name="multiplexed_sample", index=None)
    measurements.to_excel(book, sheet_name="measurement_set", index=None)
    sequence_file.to_excel(book, sheet_name="sequence_file", index=None)

print("Wrote {}_{}.xlsx".format(test_run_name, upload_target))

Wrote IGVF_014_production.xlsx